<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title> 3 Análisis de datos básico en R | Introducción al software estadístico R</title>
  <meta name="description" content="Material del curso de Formación en R Euskaltel">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content=" 3 Análisis de datos básico en R | Introducción al software estadístico R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Material del curso de Formación en R Euskaltel" />
  <meta name="github-repo" content="idaejin/xxx" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 3 Análisis de datos básico en R | Introducción al software estadístico R" />
  
  <meta name="twitter:description" content="Material del curso de Formación en R Euskaltel" />
  

<meta name="author" content="Dae-Jin Lee &lt; dlee@bcamath.org &gt;">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="intro.html">
<link rel="next" href="introduccion-a-la-programacion-basica-con-r.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Curso de formación en R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Información y pre-requisitos</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introducción al software estadístico <code>R</code></a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#algunas-cuestiones-a-tener-en-cuenta-sobre-r"><i class="fa fa-check"></i><b>2.1</b> Algunas cuestiones a tener en cuenta sobre <code>R</code></a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#rstudio"><i class="fa fa-check"></i><b>2.2</b> Rstudio</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#instalar-un-paquete-de-r"><i class="fa fa-check"></i><b>2.3</b> Instalar un paquete de <code>R</code></a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#empezando-con-r"><i class="fa fa-check"></i><b>2.4</b> Empezando con <code>R</code></a></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#cargar-librerias-en-r"><i class="fa fa-check"></i><b>2.5</b> Cargar librerías en <code>R</code></a></li>
<li class="chapter" data-level="2.6" data-path="intro.html"><a href="intro.html#lectura-de-datos"><i class="fa fa-check"></i><b>2.6</b> Lectura de datos</a></li>
<li class="chapter" data-level="2.7" data-path="intro.html"><a href="intro.html#importar-datos"><i class="fa fa-check"></i><b>2.7</b> Importar datos</a></li>
<li class="chapter" data-level="2.8" data-path="intro.html"><a href="intro.html#exportar-datos"><i class="fa fa-check"></i><b>2.8</b> Exportar datos</a></li>
<li class="chapter" data-level="2.9" data-path="intro.html"><a href="intro.html#vectores"><i class="fa fa-check"></i><b>2.9</b> Vectores</a></li>
<li class="chapter" data-level="2.10" data-path="intro.html"><a href="intro.html#estadistica-basica"><i class="fa fa-check"></i><b>2.10</b> Estadística básica</a></li>
<li class="chapter" data-level="2.11" data-path="intro.html"><a href="intro.html#vectores-caracteres-y-variables-factor"><i class="fa fa-check"></i><b>2.11</b> Vectores caracteres y variables factor</a></li>
<li class="chapter" data-level="2.12" data-path="intro.html"><a href="intro.html#data-frames"><i class="fa fa-check"></i><b>2.12</b> Data frames</a><ul>
<li class="chapter" data-level="2.12.1" data-path="intro.html"><a href="intro.html#trabajando-con-data-frames"><i class="fa fa-check"></i><b>2.12.1</b> Trabajando con data frames</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="intro.html"><a href="intro.html#vectores-logicos"><i class="fa fa-check"></i><b>2.13</b> Vectores lógicos</a></li>
<li class="chapter" data-level="2.14" data-path="intro.html"><a href="intro.html#trabajando-con-vectores"><i class="fa fa-check"></i><b>2.14</b> Trabajando con vectores</a></li>
<li class="chapter" data-level="2.15" data-path="intro.html"><a href="intro.html#matrices-y-arrays"><i class="fa fa-check"></i><b>2.15</b> Matrices y arrays</a></li>
<li class="chapter" data-level="2.16" data-path="intro.html"><a href="intro.html#factores"><i class="fa fa-check"></i><b>2.16</b> Factores</a></li>
<li class="chapter" data-level="2.17" data-path="intro.html"><a href="intro.html#indexando-vectores-con-condiciones-logicas"><i class="fa fa-check"></i><b>2.17</b> Indexando vectores con condiciones lógicas</a></li>
<li class="chapter" data-level="2.18" data-path="intro.html"><a href="intro.html#valores-faltantes"><i class="fa fa-check"></i><b>2.18</b> Valores faltantes</a></li>
<li class="chapter" data-level="2.19" data-path="intro.html"><a href="intro.html#trabajando-con-data-frames-1"><i class="fa fa-check"></i><b>2.19</b> Trabajando con data frames</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basic.html"><a href="basic.html"><i class="fa fa-check"></i><b>3</b> Análisis de datos básico en <code>R</code></a><ul>
<li class="chapter" data-level="3.1" data-path="basic.html"><a href="basic.html#graficos-sencillos"><i class="fa fa-check"></i><b>3.1</b> Gráficos sencillos</a></li>
<li class="chapter" data-level="3.2" data-path="basic.html"><a href="basic.html#scatterplots"><i class="fa fa-check"></i><b>3.2</b> Scatterplots</a></li>
<li class="chapter" data-level="3.3" data-path="basic.html"><a href="basic.html#mas-opciones-graficas"><i class="fa fa-check"></i><b>3.3</b> Más opciones gráficas</a></li>
<li class="chapter" data-level="3.4" data-path="basic.html"><a href="basic.html#tablas-de-clasificacion-cruzada-o-de-contigencia"><i class="fa fa-check"></i><b>3.4</b> Tablas de clasificación cruzada o de contigencia</a></li>
<li class="chapter" data-level="3.5" data-path="basic.html"><a href="basic.html#datos-cualitativos"><i class="fa fa-check"></i><b>3.5</b> Datos cualitativos</a></li>
<li class="chapter" data-level="3.6" data-path="basic.html"><a href="basic.html#datos-cuantitativos"><i class="fa fa-check"></i><b>3.6</b> Datos cuantitativos</a><ul>
<li class="chapter" data-level="3.6.1" data-path="basic.html"><a href="basic.html#distribuciones-de-frecuencias"><i class="fa fa-check"></i><b>3.6.1</b> Distribuciones de frecuencias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html"><i class="fa fa-check"></i><b>4</b> Introducción a la programación básica con <code>R</code></a><ul>
<li class="chapter" data-level="4.1" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#condicionales"><i class="fa fa-check"></i><b>4.1</b> Condicionales</a></li>
<li class="chapter" data-level="4.2" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#operadores-logicos"><i class="fa fa-check"></i><b>4.2</b> Operadores Lógicos</a></li>
<li class="chapter" data-level="4.3" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#if"><i class="fa fa-check"></i><b>4.3</b> <code>if</code></a></li>
<li class="chapter" data-level="4.4" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#ifelse"><i class="fa fa-check"></i><b>4.4</b> <code>ifelse</code></a></li>
<li class="chapter" data-level="4.5" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#loops-o-bucles"><i class="fa fa-check"></i><b>4.5</b> Loops o Bucles</a><ul>
<li class="chapter" data-level="4.5.1" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#for"><i class="fa fa-check"></i><b>4.5.1</b> <code>for</code></a></li>
<li class="chapter" data-level="4.5.2" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#while"><i class="fa fa-check"></i><b>4.5.2</b> <code>while</code></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#famila-de-funciones-apply"><i class="fa fa-check"></i><b>4.6</b> Famila de funciones <code>apply</code></a></li>
<li class="chapter" data-level="4.7" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#other-loops"><i class="fa fa-check"></i><b>4.7</b> Other Loops</a></li>
<li class="chapter" data-level="4.8" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#improving-speed-performance-of-loops"><i class="fa fa-check"></i><b>4.8</b> Improving Speed Performance of Loops</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html"><i class="fa fa-check"></i><b>5</b> Distribuciones de probabilidad en R</a><ul>
<li class="chapter" data-level="5.1" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribucion-binomial-binnp"><i class="fa fa-check"></i><b>5.1</b> Distribución binomial <span class="math inline">\(Bin(n,p)\)</span></a></li>
<li class="chapter" data-level="5.2" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribucion-de-poisson-poislambda"><i class="fa fa-check"></i><b>5.2</b> Distribución de Poisson <span class="math inline">\(Pois(\lambda)\)</span></a><ul>
<li class="chapter" data-level="5.2.1" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#aproximacion-de-binomial-como-poisson"><i class="fa fa-check"></i><b>5.2.1</b> Aproximación de Binomial como Poisson</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribution-exponencial-explambda"><i class="fa fa-check"></i><b>5.3</b> Distribution Exponencial <span class="math inline">\(Exp(\lambda)\)</span></a></li>
<li class="chapter" data-level="5.4" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribution-normal-mathcalnmusigma2"><i class="fa fa-check"></i><b>5.4</b> Distribution Normal <span class="math inline">\(\mathcal{N}(\mu,\sigma^2)\)</span></a></li>
<li class="chapter" data-level="5.5" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribucion-uniforme-uab"><i class="fa fa-check"></i><b>5.5</b> Distribución Uniforme <span class="math inline">\(U(a,b)\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html"><i class="fa fa-check"></i><b>6</b> Modelos lineales y análisis de la varianza</a><ul>
<li class="chapter" data-level="6.1" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#principios-de-la-modelizacion-estadistica"><i class="fa fa-check"></i><b>6.1</b> Principios de la modelización estadística</a><ul>
<li class="chapter" data-level="6.1.1" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#identificar-y-caracterizar-variables"><i class="fa fa-check"></i><b>6.1.1</b> Identificar y Caracterizar Variables</a></li>
<li class="chapter" data-level="6.1.2" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#tipos-de-variables-y-tipo-de-modelo"><i class="fa fa-check"></i><b>6.1.2</b> Tipos de variables y tipo de modelo</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#el-modelo-lineal-general"><i class="fa fa-check"></i><b>6.2</b> El modelo lineal general</a></li>
<li class="chapter" data-level="6.3" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#definicion-de-modelos-en-r"><i class="fa fa-check"></i><b>6.3</b> Definición de modelos en <code>R</code></a><ul>
<li class="chapter" data-level="6.3.1" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#ejemplo-datos-de-precios-de-viviendas-en-boston"><i class="fa fa-check"></i><b>6.3.1</b> Ejemplo: Datos de precios de viviendas en Boston</a></li>
<li class="chapter" data-level="6.3.2" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#regresion-lineal-multiple"><i class="fa fa-check"></i><b>6.3.2</b> Regresión lineal múltiple</a></li>
<li class="chapter" data-level="6.3.3" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#ejemplo"><i class="fa fa-check"></i><b>6.3.3</b> Ejemplo:</a></li>
<li class="chapter" data-level="6.3.4" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#modelos-con-interacciones"><i class="fa fa-check"></i><b>6.3.4</b> Modelos con interacciones</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regresion-logistica.html"><a href="regresion-logistica.html"><i class="fa fa-check"></i><b>7</b> Regresión logística</a><ul>
<li class="chapter" data-level="7.1" data-path="regresion-logistica.html"><a href="regresion-logistica.html#ejemplo-datos-de-credito-en-alemania-credit-scoring"><i class="fa fa-check"></i><b>7.1</b> Ejemplo: Datos de crédito en Alemania (<em>Credit scoring</em>)</a></li>
<li class="chapter" data-level="7.2" data-path="regresion-logistica.html"><a href="regresion-logistica.html#ejemplo-predecir-el-salario-de-los-trabajadores"><i class="fa fa-check"></i><b>7.2</b> Ejemplo: Predecir el salario de los trabajadores</a></li>
<li class="chapter" data-level="7.3" data-path="regresion-logistica.html"><a href="regresion-logistica.html#ejemplo-datos-de-los-supervivientes-del-titanic"><i class="fa fa-check"></i><b>7.3</b> Ejemplo: Datos de los supervivientes del Titanic</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html"><i class="fa fa-check"></i><b>8</b> Modelos Aditivos Generalizados</a></li>
<li class="chapter" data-level="9" data-path="analisis-de-componentes-principales-clasificacion-y-clustering.html"><a href="analisis-de-componentes-principales-clasificacion-y-clustering.html"><i class="fa fa-check"></i><b>9</b> Análisis de Componentes Principales, Clasificación y Clustering</a></li>
<li class="chapter" data-level="10" data-path="introduccion-al-machine-learning.html"><a href="introduccion-al-machine-learning.html"><i class="fa fa-check"></i><b>10</b> Introducción al machine learning</a></li>
<li class="chapter" data-level="11" data-path="extras.html"><a href="extras.html"><i class="fa fa-check"></i><b>11</b> Extras</a></li>
<li class="divider"></li>
<li><a href="http://idaejin.github.io/" target="blank">Mi página personal</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introducción al software estadístico <code>R</code></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="basic" class="section level1">
<h1><span class="header-section-number"> 3</span> Análisis de datos básico en <code>R</code></h1>
<div id="graficos-sencillos" class="section level2">
<h2><span class="header-section-number">3.1</span> Gráficos sencillos</h2>
<ul>
<li>Scatterplot</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(mtcars)
<span class="kw">plot</span>(wt, mpg, <span class="dt">main=</span><span class="st">&quot;Scatterplot Example&quot;</span>,
   <span class="dt">xlab=</span><span class="st">&quot;Car Weight &quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Miles Per Gallon &quot;</span>, <span class="dt">pch=</span><span class="dv">19</span>) </code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<ul>
<li>Matriz scatterplot</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pairs</span>(<span class="op">~</span>mpg<span class="op">+</span>disp<span class="op">+</span>drat<span class="op">+</span>wt,<span class="dt">data=</span>mtcars,
   <span class="dt">main=</span><span class="st">&quot;Simple Scatterplot Matrix&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<ul>
<li>Barplot o diagrama de barras</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tab &lt;-<span class="st"> </span><span class="kw">table</span>(mtcars[,<span class="kw">c</span>(<span class="st">&quot;cyl&quot;</span>)])
<span class="kw">barplot</span>(tab)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<ul>
<li>Piechart o diagrama de tarta</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pie</span>(tab)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><strong>Ejercicio:</strong></p>
<ol style="list-style-type: decimal">
<li>El <code>data.frame</code> <code>VADeaths</code> contiene las tasas de mortalidad por cada 1000 habitantes en Virginia (EEUU) en 1940</li>
</ol>
<ul>
<li>Las tasas de mortalidad se miden cada 1000 habitantes por año. Se encuentran clasificadas por grupo de edad (filas) y grupo de población (columnas). Los grupos de edad son: 50-54, 55-59, 60-64, 65-69, 70-74 y los grupos de población: <code>Rural/Male</code>, <code>Rural/Female</code>, <code>Urban/Male</code> and <code>Urban/Female</code>.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(VADeaths)
VADeaths</code></pre></div>
<pre><code>##       Rural Male Rural Female Urban Male Urban Female
## 50-54       11.7          8.7       15.4          8.4
## 55-59       18.1         11.7       24.3         13.6
## 60-64       26.9         20.3       37.0         19.3
## 65-69       41.0         30.9       54.6         35.1
## 70-74       66.0         54.3       71.1         50.0</code></pre>
<ul>
<li><p>Calcula la media para cada grupo de edad.</p>
<ul>
<li><strong>Result:</strong></li>
</ul></li>
</ul>
<pre><code>##  50-54  55-59  60-64  65-69  70-74 
## 11.050 16.925 25.875 40.400 60.350</code></pre>
<ul>
<li><p>Calcula la media para cada grupo de población.</p>
<ul>
<li><strong>Resultado:</strong></li>
</ul></li>
</ul>
<pre><code>##   Rural Male Rural Female   Urban Male Urban Female 
##        32.74        25.18        40.48        25.28</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>El <code>data.frame</code> <code>rainforest</code> contiene diferentes variables de <code>species</code></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(DAAG)</code></pre></div>
<pre><code>## Loading required package: lattice</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rainforest
?rainforest
<span class="kw">names</span>(rainforest)</code></pre></div>
<ul>
<li><p>Crear una tabla de conteos para cada <code>species</code> y realiza un gráfico descriptivo.</p>
<ul>
<li><strong>Resultado:</strong></li>
</ul></li>
</ul>
<pre><code>## 
## Acacia mabellae      C. fraseri  Acmena smithii   B. myrtifolia 
##              16              12              26              11</code></pre>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<ol start="3" style="list-style-type: decimal">
<li>El <code>data.frame</code> <code>Acmena</code> est? creado a partir de <code>rainforest</code> mediante la función <code>subset</code>.</li>
</ol>
<ul>
<li>Realiza un gráfico que relacione la biomasa de la madera (<code>wood</code>) y el di?metro a la altura del pecho (<code>dbh</code>). Utiliza tambi?n la escala logarítmica.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Acmena &lt;-<span class="st"> </span><span class="kw">subset</span>(rainforest, species <span class="op">==</span><span class="st"> &quot;Acmena smithii&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-11-1.png" width="960" /></p>
<ul>
<li>Calcula un histograma de la variable <code>dbh</code> mediante la función <code>hist</code></li>
</ul>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<ol start="4" style="list-style-type: decimal">
<li><p>Crea un vector de n?meros enteros positivos impares the longitud 100 y calcula los valores entre 60 y 80.</p>
<ul>
<li><strong>Result:</strong></li>
</ul></li>
</ol>
<pre><code>##  [1] 61 63 65 67 69 71 73 75 77 79</code></pre>
<!-- * [Soluciones aquí](http://idaejin.github.io/bcam-courses/rbasics/rbasics_sol.R) -->
<hr />
</div>
<div id="scatterplots" class="section level2">
<h2><span class="header-section-number">3.2</span> Scatterplots</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(MASS)
<span class="kw">data</span>(<span class="st">&quot;mammals&quot;</span>)
?mammals
<span class="kw">head</span>(mammals)</code></pre></div>
<pre><code>##                    body brain
## Arctic fox        3.385  44.5
## Owl monkey        0.480  15.5
## Mountain beaver   1.350   8.1
## Cow             465.000 423.0
## Grey wolf        36.330 119.5
## Goat             27.660 115.0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(mammals)
species &lt;-<span class="st"> </span><span class="kw">row.names</span>(mammals)
x &lt;-<span class="st"> </span>body
y &lt;-<span class="st"> </span>brain</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(calibrate)
<span class="co"># scatterplot</span>
<span class="kw">plot</span>(x,y, <span class="dt">xlab =</span> <span class="st">&quot;body weight in kgr&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;brain weight in gr&quot;</span>, 
     <span class="dt">main=</span><span class="st">&quot;Body vs Brain weight </span><span class="ch">\n</span><span class="st"> for 62 Species of Land Mammals&quot;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">8500</span>))
<span class="kw">textxy</span>(x,y,<span class="dt">labs=</span>species,<span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>,<span class="dt">cex=</span><span class="fl">0.85</span>) </code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Identificar un punto en el scatterplot</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">identify</span>(x,y,species)</code></pre></div>
<p>En escala logarítmica</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">log</span>(x),<span class="kw">log</span>(y), <span class="dt">xlab =</span> <span class="st">&quot;log body weight in kgr&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;log brain weight in gr&quot;</span>, 
     <span class="dt">main=</span><span class="st">&quot;log Body vs log Brain weight </span><span class="ch">\n</span><span class="st"> for 62 Species of Land Mammals&quot;</span>)
<span class="kw">textxy</span>(<span class="kw">log</span>(x),<span class="kw">log</span>(y),<span class="dt">labs=</span>species,<span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>,<span class="dt">cex=</span><span class="fl">0.85</span>) </code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-17-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Identificar un punto en la escala logarítmica</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">identify</span>(<span class="kw">log</span>(x),<span class="kw">log</span>(y),species)</code></pre></div>
</div>
<div id="mas-opciones-graficas" class="section level2">
<h2><span class="header-section-number">3.3</span> Más opciones gráficas</h2>
<p><strong>Varios conjuntos de datos en un sólo gráfico</strong></p>
<p>Una vez realizado un <code>plot</code>, el comando <code>points</code> permite añadir nuevas observaciones.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)
 x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dt">sd=</span><span class="dv">5</span>,<span class="dt">mean=</span><span class="dv">20</span>)
 y &lt;-<span class="st"> </span><span class="fl">2.5</span><span class="op">*</span>x <span class="op">-</span><span class="st"> </span><span class="fl">1.0</span> <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dt">sd=</span><span class="dv">9</span>,<span class="dt">mean=</span><span class="dv">0</span>)
 <span class="kw">cor</span>(x,y)</code></pre></div>
<pre><code>## [1] 0.7512194</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">plot</span>(x,y,<span class="dt">xlab=</span><span class="st">&quot;Independent&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Dependent&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Random plot&quot;</span>)
 x1 &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">8</span>,<span class="dv">15</span>,<span class="dv">25</span>)
 y1 &lt;-<span class="st"> </span><span class="fl">2.5</span><span class="op">*</span>x1 <span class="op">-</span><span class="st"> </span><span class="fl">1.0</span> <span class="op">+</span><span class="st"> </span><span class="kw">runif</span>(<span class="dv">8</span>,<span class="op">-</span><span class="dv">6</span>,<span class="dv">6</span>)
 <span class="kw">points</span>(x1,y1,<span class="dt">col=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>con la leyenda</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)
x2 &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">8</span>,<span class="dv">15</span>,<span class="dv">25</span>)
y2 &lt;-<span class="st"> </span><span class="fl">2.5</span><span class="op">*</span>x2 <span class="op">-</span><span class="st"> </span><span class="fl">1.0</span> <span class="op">+</span><span class="st"> </span><span class="kw">runif</span>(<span class="dv">8</span>,<span class="op">-</span><span class="dv">6</span>,<span class="dv">6</span>)
 <span class="kw">plot</span>(x,y,<span class="dt">xlab=</span><span class="st">&quot;Independent&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Dependent&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Random plot&quot;</span>)
 <span class="kw">points</span>(x1,y1,<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">pch=</span><span class="dv">3</span>)
 <span class="kw">points</span>(x2,y2,<span class="dt">col=</span><span class="dv">4</span>,<span class="dt">pch=</span><span class="dv">5</span>)
 <span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="kw">c</span>(<span class="st">&quot;Original&quot;</span>,<span class="st">&quot;one&quot;</span>,<span class="st">&quot;two&quot;</span>),<span class="dt">col=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>),<span class="dt">pch=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>))</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<!-- **Errors bars:** -->
<!-- ```{r,fig.width=8,fig.height=6} -->
<!-- plot(x,y,xlab="Independent",ylab="Dependent",main="Random plot",ylim=c(20,90)) -->
<!-- xHigh <- x -->
<!-- yHigh <- y + abs(rnorm(10,sd=3.5)) -->
<!-- xLow <- x -->
<!-- yLow <- y - abs(rnorm(10,sd=3.1)) -->
<!-- arrows(xHigh,yHigh,xLow,yLow,col=2,angle=90,length=0.1,code=3) -->
<!-- ``` -->
<!-- ```{r,fig.width=8,fig.height=6} -->
<!-- plot(1:20,0*(1:20),pch=1:20,cex=2) -->
<!-- ``` -->
<p><strong>Varios gráficos en un sola imagen</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)
 <span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))
 <span class="kw">boxplot</span>(<span class="kw">rnorm</span>(<span class="dv">100</span>),<span class="dt">main=</span><span class="st">&quot;first plot&quot;</span>)
 <span class="kw">boxplot</span>(<span class="kw">rgamma</span>(<span class="dv">100</span>,<span class="dv">2</span>),<span class="dt">main=</span><span class="st">&quot;second plot&quot;</span>, <span class="dt">horizontal=</span><span class="ot">TRUE</span>,<span class="dt">col=</span><span class="st">&quot;bisque&quot;</span>)
 <span class="kw">plot</span>(<span class="kw">rnorm</span>(<span class="dv">100</span>),<span class="dt">xlab=</span><span class="st">&quot;third plot&quot;</span>,
      <span class="dt">ylab=</span><span class="st">&quot;y-label&quot;</span>,<span class="dt">main=</span><span class="st">&quot;x-label&quot;</span>)
 <span class="kw">hist</span>(<span class="kw">rnorm</span>(<span class="dv">100</span>),<span class="dt">main=</span><span class="st">&quot;fourth plot&quot;</span>,<span class="dt">col=</span><span class="st">&quot;lightgrey&quot;</span>)
 <span class="kw">hist</span>(<span class="kw">rexp</span>(<span class="dv">100</span>),<span class="dt">main=</span><span class="st">&quot;fifth plot&quot;</span>,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)
 <span class="kw">plot</span>(<span class="kw">rnorm</span>(<span class="dv">100</span>),<span class="kw">rexp</span>(<span class="dv">100</span>),<span class="dt">main=</span><span class="st">&quot;sixth plot&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p><strong>Relaciones entre variables</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">uData &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>)
vData &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>,<span class="dt">mean=</span><span class="dv">5</span>)
wData &lt;-<span class="st"> </span>uData <span class="op">+</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span>vData <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>,<span class="dt">sd=</span><span class="fl">0.5</span>)
xData &lt;-<span class="st"> </span><span class="op">-</span><span class="dv">2</span><span class="op">*</span>uData<span class="op">+</span><span class="kw">rnorm</span>(<span class="dv">20</span>,<span class="dt">sd=</span><span class="fl">0.1</span>)
yData &lt;-<span class="st">  </span><span class="dv">3</span><span class="op">*</span>vData<span class="op">+</span><span class="kw">rnorm</span>(<span class="dv">20</span>,<span class="dt">sd=</span><span class="fl">2.5</span>)
d &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">u=</span>uData,<span class="dt">v=</span>vData,<span class="dt">w=</span>wData,<span class="dt">x=</span>xData,<span class="dt">y=</span>yData)
<span class="kw">pairs</span>(d)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p><strong>Gráfico de correlaciones</strong></p>
<p>La función <code>corrplot</code> de la librer?a <code>corrplot</code> permite visualizar una matriz de correlaciones calculada mediante la función <code>cor</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(corrplot)</code></pre></div>
<pre><code>## corrplot 0.84 loaded</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M &lt;-<span class="st"> </span><span class="kw">cor</span>(d)
<span class="kw">corrplot</span>(M, <span class="dt">method=</span><span class="st">&quot;circle&quot;</span>,<span class="dt">type=</span><span class="st">&quot;upper&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-23-1.png" width="768" /></p>
<p><strong>Gráficos de superficies: <code>image</code>, <code>contour</code> y <code>persp</code></strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">2</span><span class="op">*</span>pi,<span class="dt">by=</span>pi<span class="op">/</span><span class="dv">50</span>)
y &lt;-<span class="st"> </span>x
xg &lt;-<span class="st"> </span>(x<span class="op">*</span><span class="dv">0</span><span class="op">+</span><span class="dv">1</span>) <span class="op">%*%</span><span class="st"> </span><span class="kw">t</span>(y)
yg &lt;-<span class="st"> </span>(x) <span class="op">%*%</span><span class="st"> </span><span class="kw">t</span>(y<span class="op">*</span><span class="dv">0</span><span class="op">+</span><span class="dv">1</span>)
f &lt;-<span class="st"> </span><span class="kw">sin</span>(xg<span class="op">*</span>yg)

<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">image</span>(x,y,f)
<span class="kw">contour</span>(x,y,f)
<span class="kw">contour</span>(x,y,f,<span class="dt">nlevels=</span><span class="dv">4</span>)
<span class="kw">image</span>(x,y,f,<span class="dt">col=</span><span class="kw">grey.colors</span>(<span class="dv">100</span>))
<span class="kw">contour</span>(x,y,f,<span class="dt">nlevels=</span><span class="dv">4</span>,<span class="dt">add=</span><span class="ot">TRUE</span>,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-24-1.png" width="960" /></p>
<p>Podemos utilizar la función <code>persp</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">persp</span>(x,y,f,<span class="dt">theta=</span><span class="op">-</span><span class="dv">30</span>,<span class="dt">phi=</span><span class="dv">55</span>,<span class="dt">col=</span><span class="st">&quot;lightgrey&quot;</span>,<span class="dt">shade=</span>.<span class="dv">01</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-25-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>o representar im?genes</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(fields)
<span class="kw">data</span>(lennon)
<span class="kw">image</span>(lennon,<span class="dt">col=</span><span class="kw">grey</span>(<span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dt">l=</span><span class="dv">256</span>)))</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-26-1.png" width="960" /></p>
</div>
<div id="tablas-de-clasificacion-cruzada-o-de-contigencia" class="section level2">
<h2><span class="header-section-number">3.4</span> Tablas de clasificación cruzada o de contigencia</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(MASS)
<span class="kw">data</span>(quine)
<span class="kw">head</span>(quine)</code></pre></div>
<pre><code>##   Eth Sex Age Lrn Days
## 1   A   M  F0  SL    2
## 2   A   M  F0  SL   11
## 3   A   M  F0  SL   14
## 4   A   M  F0  AL    5
## 5   A   M  F0  AL    5
## 6   A   M  F0  AL   13</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(quine)
<span class="kw">table</span>(Sex)</code></pre></div>
<pre><code>## Sex
##  F  M 
## 80 66</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(Sex,Age)</code></pre></div>
<pre><code>##    Age
## Sex F0 F1 F2 F3
##   F 10 32 19 19
##   M 17 14 21 14</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># or xtabs</span>
<span class="kw">xtabs</span>(<span class="op">~</span>Sex<span class="op">+</span>Age,<span class="dt">data=</span>quine)</code></pre></div>
<pre><code>##    Age
## Sex F0 F1 F2 F3
##   F 10 32 19 19
##   M 17 14 21 14</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">xtabs</span>(<span class="op">~</span>Sex<span class="op">+</span>Age<span class="op">+</span>Eth,<span class="dt">data=</span>quine)</code></pre></div>
<pre><code>## , , Eth = A
## 
##    Age
## Sex F0 F1 F2 F3
##   F  5 15  9  9
##   M  8  5 11  7
## 
## , , Eth = N
## 
##    Age
## Sex F0 F1 F2 F3
##   F  5 17 10 10
##   M  9  9 10  7</code></pre>
<p><strong>Cálculos sobre tablas de contigencia</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(Days,Age,mean)</code></pre></div>
<pre><code>##       F0       F1       F2       F3 
## 14.85185 11.15217 21.05000 19.60606</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(Days,<span class="kw">list</span>(Sex,Age),mean)</code></pre></div>
<pre><code>##         F0       F1       F2       F3
## F 18.70000 12.96875 18.42105 14.00000
## M 12.58824  7.00000 23.42857 27.21429</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(Days,<span class="kw">list</span>(Sex,Age),<span class="cf">function</span>(x) <span class="kw">sqrt</span>(<span class="kw">var</span>(x)<span class="op">/</span><span class="kw">length</span>(x)))</code></pre></div>
<pre><code>##         F0       F1       F2       F3
## F 4.208589 2.329892 5.299959 2.940939
## M 3.768151 1.418093 3.766122 4.569582</code></pre>
</div>
<div id="datos-cualitativos" class="section level2">
<h2><span class="header-section-number">3.5</span> Datos cualitativos</h2>
<p>Supongamos unos datos cualquiera de las variables <code>treatment</code> y <code>improvement</code> de pacientes a una enfermedad determinada.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">treatment &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="kw">c</span>(<span class="dv">43</span>, <span class="dv">41</span>)), <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>),
                    <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;placebo&quot;</span>, <span class="st">&quot;treated&quot;</span>))
improved &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="kw">c</span>(<span class="dv">29</span>, <span class="dv">7</span>, <span class="dv">7</span>, <span class="dv">13</span>, <span class="dv">7</span>, <span class="dv">21</span>)),
                   <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),
                   <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;none&quot;</span>, <span class="st">&quot;some&quot;</span>, <span class="st">&quot;marked&quot;</span>))</code></pre></div>
<p>Tabla de contigencia</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">xtabs</span>(<span class="op">~</span>treatment<span class="op">+</span>improved)</code></pre></div>
<pre><code>##          improved
## treatment none some marked
##   placebo   29    7      7
##   treated   13    7     21</code></pre>
<p>De manera gráfica,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">spineplot</span>(improved <span class="op">~</span><span class="st"> </span>treatment)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>El conjunto de datos de <code>R</code>, <code>UCBAdmissions</code>contiene los datos agregadps de los solicitantes a universidad de Berkeley a los seis departamentos más grandes en 1973 clasificados por sexo y admisión.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&quot;UCBAdmissions&quot;</span>)
?UCBAdmissions
<span class="kw">apply</span>(UCBAdmissions, <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>), sum)</code></pre></div>
<pre><code>##         Admit
## Gender   Admitted Rejected
##   Male       1198     1493
##   Female      557     1278</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">prop.table</span>(<span class="kw">apply</span>(UCBAdmissions, <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>), sum))</code></pre></div>
<pre><code>##         Admit
## Gender    Admitted  Rejected
##   Male   0.2646929 0.3298719
##   Female 0.1230667 0.2823685</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ftable</span>(UCBAdmissions)</code></pre></div>
<pre><code>##                 Dept   A   B   C   D   E   F
## Admit    Gender                             
## Admitted Male        512 353 120 138  53  22
##          Female       89  17 202 131  94  24
## Rejected Male        313 207 205 279 138 351
##          Female       19   8 391 244 299 317</code></pre>
<p>Con <code>ftable</code> podemos presentar la información con mayor claridad</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ftable</span>(<span class="kw">round</span>(<span class="kw">prop.table</span>(UCBAdmissions), <span class="dv">3</span>),
       <span class="dt">row.vars=</span><span class="st">&quot;Dept&quot;</span>, <span class="dt">col.vars =</span> <span class="kw">c</span>(<span class="st">&quot;Gender&quot;</span>, <span class="st">&quot;Admit&quot;</span>))</code></pre></div>
<pre><code>##      Gender     Male            Female         
##      Admit  Admitted Rejected Admitted Rejected
## Dept                                           
## A              0.113    0.069    0.020    0.004
## B              0.078    0.046    0.004    0.002
## C              0.027    0.045    0.045    0.086
## D              0.030    0.062    0.029    0.054
## E              0.012    0.030    0.021    0.066
## F              0.005    0.078    0.005    0.070</code></pre>
<p>Resulta más intereseante mostrar la información por género <code>Gender</code> y <code>Dept</code> combinados (dimensiones 2 y 3 del array). Nótese que las tasas de admisión por <code>male</code> y <code>female</code> son más o menos similares en todos los departamentos, excepto en “A”, donde las tasas de las mujeres es mayor.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># prop.table(UCBAdmissions, c(2,3))</span>
<span class="kw">ftable</span>(<span class="kw">round</span>(<span class="kw">prop.table</span>(UCBAdmissions, <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)), <span class="dv">2</span>),
       <span class="dt">row.vars=</span><span class="st">&quot;Dept&quot;</span>, <span class="dt">col.vars =</span> <span class="kw">c</span>(<span class="st">&quot;Gender&quot;</span>, <span class="st">&quot;Admit&quot;</span>))</code></pre></div>
<pre><code>##      Gender     Male            Female         
##      Admit  Admitted Rejected Admitted Rejected
## Dept                                           
## A               0.62     0.38     0.82     0.18
## B               0.63     0.37     0.68     0.32
## C               0.37     0.63     0.34     0.66
## D               0.33     0.67     0.35     0.65
## E               0.28     0.72     0.24     0.76
## F               0.06     0.94     0.07     0.93</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Data aggregated over departments
<span class="kw">apply</span>(UCBAdmissions, <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), sum)</code></pre></div>
<pre><code>##           Gender
## Admit      Male Female
##   Admitted 1198    557
##   Rejected 1493   1278</code></pre>
<p>Gráficamente</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">spineplot</span>(<span class="kw">margin.table</span>(UCBAdmissions, <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">2</span>)),
           <span class="dt">main =</span> <span class="st">&quot;Applications at UCB&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">spineplot</span>(<span class="kw">margin.table</span>(UCBAdmissions, <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">1</span>)),
           <span class="dt">main =</span> <span class="st">&quot;Admissions at UCB&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-38-2.png" width="672" /></p>
<p>Estos datos ilustran la denominada <em>paradoja de Simpson</em>. Este hecho ha sido analizado como un posible caso de discriminación por sexo en las tasas de admisión en Berkeley. De los 2691 hombres que solicitaron se admitidos, 1198 (44.5%) fueron admitidos, comparado con las 1835 mujeres de las cuales tan s?lo 557 (30.4%) fueron admitidas. Se podr?a por tanto concluir que los hombres tienes tasas de admisión mayores que las mujeres. <a href="https://en.wikipedia.org/wiki/Simpson%27s_paradox#UC_Berkeley_gender_bias">Wikipedia: Gender Bias UC Berkeley</a>.</p>
<p>Otro ejemplo de la Paradoja de Simpson:</p>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-39-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="datos-cuantitativos" class="section level2">
<h2><span class="header-section-number">3.6</span> Datos cuantitativos</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(faithful)</code></pre></div>
<pre><code>##   eruptions waiting
## 1     3.600      79
## 2     1.800      54
## 3     3.333      74
## 4     2.283      62
## 5     4.533      85
## 6     2.883      55</code></pre>
<p>Consideremos los datos del geyser Old Faithful en el parque nacional de Yellowstone, EEUU.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(faithful)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<div id="distribuciones-de-frecuencias" class="section level3">
<h3><span class="header-section-number">3.6.1</span> Distribuciones de frecuencias</h3>
<p>Vamos a utilizar el conjunto de datos <code>faithful</code>, para ilustrar el concepto de distribuci?n de frecuencias que consistir? en crear una series de categor?as o intervalos, en los que contaremos el n?mero de observaciones en cada categor?a.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">duration &lt;-<span class="st"> </span>faithful<span class="op">$</span>eruptions
<span class="kw">range</span>(duration)</code></pre></div>
<pre><code>## [1] 1.6 5.1</code></pre>
<p>Crearemos los sub-intervalos entre <code>[1.6, 5.1]</code> y la secuencia <code>{ 1.5, 2.0, 2.5, ... }</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">breaks &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="fl">1.5</span>,<span class="fl">5.5</span>,<span class="dt">by=</span><span class="fl">0.5</span>)
breaks</code></pre></div>
<pre><code>## [1] 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5</code></pre>
<p>La función <code>cut</code> nos permite divider el rango en los intervalos que especifiquemos, con el argumento <code>right=FALSE</code>, consideramos el intervalo cerrado por la derecha.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">duration.cut =<span class="st"> </span><span class="kw">cut</span>(duration, breaks, <span class="dt">right=</span><span class="ot">FALSE</span>) </code></pre></div>
<p>Con <code>table</code> generamos las frecuencias</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">duration.freq =<span class="st"> </span><span class="kw">table</span>(duration.cut) 
duration.freq</code></pre></div>
<pre><code>## duration.cut
## [1.5,2) [2,2.5) [2.5,3) [3,3.5) [3.5,4) [4,4.5) [4.5,5) [5,5.5) 
##      51      41       5       7      30      73      61       4</code></pre>
<p>Con <code>hist</code> podemos realizarlo de manera autom?tica:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">freq &lt;-<span class="st"> </span><span class="kw">hist</span>(duration)
freq</code></pre></div>
<pre><code>## $breaks
## [1] 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5
## 
## $counts
## [1] 55 37  5  9 34 75 54  3
## 
## $density
## [1] 0.40441176 0.27205882 0.03676471 0.06617647 0.25000000 0.55147059
## [7] 0.39705882 0.02205882
## 
## $mids
## [1] 1.75 2.25 2.75 3.25 3.75 4.25 4.75 5.25
## 
## $xname
## [1] &quot;duration&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">freq &lt;-<span class="st"> </span><span class="kw">hist</span>(duration,<span class="dt">breaks =</span> breaks)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(duration,<span class="dv">50</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-46-2.png" width="672" /></p>
<p><strong>Estimación de densidad</strong> construye una estimación dada una distribucion de probabilidad para una muestra dada.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(graphics)
d &lt;-<span class="st"> </span><span class="kw">density</span>(faithful<span class="op">$</span>eruptions)
d</code></pre></div>
<pre><code>## 
## Call:
##  density.default(x = faithful$eruptions)
## 
## Data: faithful$eruptions (272 obs.); Bandwidth &#39;bw&#39; = 0.3348
## 
##        x                y            
##  Min.   :0.5957   Min.   :0.0002262  
##  1st Qu.:1.9728   1st Qu.:0.0514171  
##  Median :3.3500   Median :0.1447010  
##  Mean   :3.3500   Mean   :0.1813462  
##  3rd Qu.:4.7272   3rd Qu.:0.3086071  
##  Max.   :6.1043   Max.   :0.4842095</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(d)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>En dos dimensiones:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(gplots)
h2 &lt;-<span class="st"> </span><span class="kw">hist2d</span>(faithful, <span class="dt">nbins=</span><span class="dv">30</span>,<span class="dt">xlab=</span><span class="st">&quot;Duration in minutes&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Waiting&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">h2</code></pre></div>
<pre><code>## 
## ----------------------------
## 2-D Histogram Object
## ----------------------------
## 
## Call: hist2d(x = faithful, nbins = 30, xlab = &quot;Duration in minutes&quot;, 
##     ylab = &quot;Waiting&quot;)
## 
## Number of data points:  272 
## Number of grid bins:  30 x 30 
## X range: ( 1.6 , 5.1 )
## Y range: ( 43 , 96 )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(h2)</code></pre></div>
<pre><code>## [1] &quot;counts&quot;   &quot;x.breaks&quot; &quot;y.breaks&quot; &quot;x&quot;        &quot;y&quot;        &quot;nobs&quot;    
## [7] &quot;call&quot;</code></pre>
<p>Frecuencias relativas</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">duration.relfreq &lt;-<span class="st"> </span>duration.freq <span class="op">/</span><span class="st"> </span><span class="kw">nrow</span>(faithful) 
tab &lt;-<span class="st"> </span><span class="kw">cbind</span>(duration.freq, duration.relfreq) 
<span class="kw">apply</span>(tab,<span class="dv">2</span>,sum)</code></pre></div>
<pre><code>##    duration.freq duration.relfreq 
##              272                1</code></pre>
<p>Distribución de frecuencias acumuladas:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cumsum</span>(duration.freq)</code></pre></div>
<pre><code>## [1.5,2) [2,2.5) [2.5,3) [3,3.5) [3.5,4) [4,4.5) [4.5,5) [5,5.5) 
##      51      92      97     104     134     207     268     272</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cumsum</span>(duration.relfreq)</code></pre></div>
<pre><code>##   [1.5,2)   [2,2.5)   [2.5,3)   [3,3.5)   [3.5,4)   [4,4.5)   [4.5,5) 
## 0.1875000 0.3382353 0.3566176 0.3823529 0.4926471 0.7610294 0.9852941 
##   [5,5.5) 
## 1.0000000</code></pre>
<!-- We can plot the cumulative relative frequency graph of a quantitative variable, which is a curve graphically showing the cumulative relative frequency distribution.  -->
<!-- The e.c.d.f. (empirical cumulative distribution function) $F_n$ is a step function with jumps $i/n$ at observation values, where $i$ is the number of tied observations at that value. Missing values are ignored. -->
<!-- For observations $x = (x_1,x_2, ... x_n)$, $F_n$ is the fraction of observations less or equal to $t$, i.e., -->
<!-- $$ -->
<!-- F_n(t) = \#{x_i <= t}/n = 1/n \sum_{i=1}^n I(x_i \leq t). -->
<!-- $$ -->
<!-- where $I$ is an indication function. -->
<!-- ```{r} -->
<!-- plot(ecdf(duration)) -->
<!-- ``` -->
<p><strong>Estimación bivariante tipo kernel</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&quot;faithful&quot;</span>)
<span class="kw">attach</span>(faithful)
Dens2d&lt;-<span class="kw">kde2d</span>(eruptions,waiting)
<span class="kw">image</span>(Dens2d,<span class="dt">xlab=</span><span class="st">&quot;eruptions&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;waiting&quot;</span>)
<span class="kw">contour</span>(Dens2d,<span class="dt">add=</span><span class="ot">TRUE</span>,<span class="dt">col=</span><span class="st">&quot;black&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">nlevels=</span><span class="dv">5</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(<span class="st">&quot;faithful&quot;</span>)</code></pre></div>
<p><strong>Gráficos <code>persp</code></strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">persp</span>(Dens2d,<span class="dt">phi=</span><span class="dv">30</span>,<span class="dt">theta=</span><span class="dv">20</span>,<span class="dt">d=</span><span class="dv">5</span>,<span class="dt">xlab=</span><span class="st">&quot;eruptions&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;waiting&quot;</span>,<span class="dt">zlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">shade=</span>.<span class="dv">2</span>,<span class="dt">col=</span><span class="st">&quot;lightblue&quot;</span>,<span class="dt">expand=</span>.<span class="dv">85</span>,<span class="dt">ticktype =</span> <span class="st">&quot;detailed&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduccion-a-la-programacion-basica-con-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"download": ["cursoR_Euskaltel.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
