<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title> 6 Modelos lineales y análisis de la varianza | Introducción al software estadístico R</title>
  <meta name="description" content="Material del curso de Formación en R Euskaltel">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content=" 6 Modelos lineales y análisis de la varianza | Introducción al software estadístico R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Material del curso de Formación en R Euskaltel" />
  <meta name="github-repo" content="idaejin/xxx" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 6 Modelos lineales y análisis de la varianza | Introducción al software estadístico R" />
  
  <meta name="twitter:description" content="Material del curso de Formación en R Euskaltel" />
  

<meta name="author" content="Dae-Jin Lee &lt; dlee@bcamath.org &gt;">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="distribuciones-de-probabilidad-en-r.html">
<link rel="next" href="regresion-logistica.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Curso de formación en R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Información y pre-requisitos</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introducción al software estadístico <code>R</code></a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#algunas-cuestiones-a-tener-en-cuenta-sobre-r"><i class="fa fa-check"></i><b>2.1</b> Algunas cuestiones a tener en cuenta sobre <code>R</code></a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#rstudio"><i class="fa fa-check"></i><b>2.2</b> Rstudio</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#instalar-un-paquete-de-r"><i class="fa fa-check"></i><b>2.3</b> Instalar un paquete de <code>R</code></a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#empezando-con-r"><i class="fa fa-check"></i><b>2.4</b> Empezando con <code>R</code></a></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#cargar-librerias-en-r"><i class="fa fa-check"></i><b>2.5</b> Cargar librerías en <code>R</code></a></li>
<li class="chapter" data-level="2.6" data-path="intro.html"><a href="intro.html#lectura-de-datos"><i class="fa fa-check"></i><b>2.6</b> Lectura de datos</a></li>
<li class="chapter" data-level="2.7" data-path="intro.html"><a href="intro.html#importar-datos"><i class="fa fa-check"></i><b>2.7</b> Importar datos</a></li>
<li class="chapter" data-level="2.8" data-path="intro.html"><a href="intro.html#exportar-datos"><i class="fa fa-check"></i><b>2.8</b> Exportar datos</a></li>
<li class="chapter" data-level="2.9" data-path="intro.html"><a href="intro.html#vectores"><i class="fa fa-check"></i><b>2.9</b> Vectores</a></li>
<li class="chapter" data-level="2.10" data-path="intro.html"><a href="intro.html#estadistica-basica"><i class="fa fa-check"></i><b>2.10</b> Estadística básica</a></li>
<li class="chapter" data-level="2.11" data-path="intro.html"><a href="intro.html#vectores-caracteres-y-variables-factor"><i class="fa fa-check"></i><b>2.11</b> Vectores caracteres y variables factor</a></li>
<li class="chapter" data-level="2.12" data-path="intro.html"><a href="intro.html#data-frames"><i class="fa fa-check"></i><b>2.12</b> Data frames</a><ul>
<li class="chapter" data-level="2.12.1" data-path="intro.html"><a href="intro.html#trabajando-con-data-frames"><i class="fa fa-check"></i><b>2.12.1</b> Trabajando con data frames</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="intro.html"><a href="intro.html#vectores-logicos"><i class="fa fa-check"></i><b>2.13</b> Vectores lógicos</a></li>
<li class="chapter" data-level="2.14" data-path="intro.html"><a href="intro.html#trabajando-con-vectores"><i class="fa fa-check"></i><b>2.14</b> Trabajando con vectores</a></li>
<li class="chapter" data-level="2.15" data-path="intro.html"><a href="intro.html#matrices-y-arrays"><i class="fa fa-check"></i><b>2.15</b> Matrices y arrays</a></li>
<li class="chapter" data-level="2.16" data-path="intro.html"><a href="intro.html#factores"><i class="fa fa-check"></i><b>2.16</b> Factores</a></li>
<li class="chapter" data-level="2.17" data-path="intro.html"><a href="intro.html#indexando-vectores-con-condiciones-logicas"><i class="fa fa-check"></i><b>2.17</b> Indexando vectores con condiciones lógicas</a></li>
<li class="chapter" data-level="2.18" data-path="intro.html"><a href="intro.html#valores-faltantes"><i class="fa fa-check"></i><b>2.18</b> Valores faltantes</a></li>
<li class="chapter" data-level="2.19" data-path="intro.html"><a href="intro.html#trabajando-con-data-frames-1"><i class="fa fa-check"></i><b>2.19</b> Trabajando con data frames</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basic.html"><a href="basic.html"><i class="fa fa-check"></i><b>3</b> Análisis de datos básico en <code>R</code></a><ul>
<li class="chapter" data-level="3.1" data-path="basic.html"><a href="basic.html#graficos-sencillos"><i class="fa fa-check"></i><b>3.1</b> Gráficos sencillos</a></li>
<li class="chapter" data-level="3.2" data-path="basic.html"><a href="basic.html#scatterplots"><i class="fa fa-check"></i><b>3.2</b> Scatterplots</a></li>
<li class="chapter" data-level="3.3" data-path="basic.html"><a href="basic.html#mas-opciones-graficas"><i class="fa fa-check"></i><b>3.3</b> Más opciones gráficas</a></li>
<li class="chapter" data-level="3.4" data-path="basic.html"><a href="basic.html#tablas-de-clasificacion-cruzada-o-de-contigencia"><i class="fa fa-check"></i><b>3.4</b> Tablas de clasificación cruzada o de contigencia</a></li>
<li class="chapter" data-level="3.5" data-path="basic.html"><a href="basic.html#datos-cualitativos"><i class="fa fa-check"></i><b>3.5</b> Datos cualitativos</a></li>
<li class="chapter" data-level="3.6" data-path="basic.html"><a href="basic.html#datos-cuantitativos"><i class="fa fa-check"></i><b>3.6</b> Datos cuantitativos</a><ul>
<li class="chapter" data-level="3.6.1" data-path="basic.html"><a href="basic.html#distribuciones-de-frecuencias"><i class="fa fa-check"></i><b>3.6.1</b> Distribuciones de frecuencias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html"><i class="fa fa-check"></i><b>4</b> Introducción a la programación básica con <code>R</code></a><ul>
<li class="chapter" data-level="4.1" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#condicionales"><i class="fa fa-check"></i><b>4.1</b> Condicionales</a></li>
<li class="chapter" data-level="4.2" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#operadores-logicos"><i class="fa fa-check"></i><b>4.2</b> Operadores Lógicos</a></li>
<li class="chapter" data-level="4.3" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#if"><i class="fa fa-check"></i><b>4.3</b> <code>if</code></a></li>
<li class="chapter" data-level="4.4" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#ifelse"><i class="fa fa-check"></i><b>4.4</b> <code>ifelse</code></a></li>
<li class="chapter" data-level="4.5" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#loops-o-bucles"><i class="fa fa-check"></i><b>4.5</b> Loops o Bucles</a><ul>
<li class="chapter" data-level="4.5.1" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#for"><i class="fa fa-check"></i><b>4.5.1</b> <code>for</code></a></li>
<li class="chapter" data-level="4.5.2" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#while"><i class="fa fa-check"></i><b>4.5.2</b> <code>while</code></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#famila-de-funciones-apply"><i class="fa fa-check"></i><b>4.6</b> Famila de funciones <code>apply</code></a></li>
<li class="chapter" data-level="4.7" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#other-loops"><i class="fa fa-check"></i><b>4.7</b> Other Loops</a></li>
<li class="chapter" data-level="4.8" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#improving-speed-performance-of-loops"><i class="fa fa-check"></i><b>4.8</b> Improving Speed Performance of Loops</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html"><i class="fa fa-check"></i><b>5</b> Distribuciones de probabilidad en R</a><ul>
<li class="chapter" data-level="5.1" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribucion-binomial-binnp"><i class="fa fa-check"></i><b>5.1</b> Distribución binomial <span class="math inline">\(Bin(n,p)\)</span></a></li>
<li class="chapter" data-level="5.2" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribucion-de-poisson-poislambda"><i class="fa fa-check"></i><b>5.2</b> Distribución de Poisson <span class="math inline">\(Pois(\lambda)\)</span></a><ul>
<li class="chapter" data-level="5.2.1" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#aproximacion-de-binomial-como-poisson"><i class="fa fa-check"></i><b>5.2.1</b> Aproximación de Binomial como Poisson</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribution-exponencial-explambda"><i class="fa fa-check"></i><b>5.3</b> Distribution Exponencial <span class="math inline">\(Exp(\lambda)\)</span></a></li>
<li class="chapter" data-level="5.4" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribution-normal-mathcalnmusigma2"><i class="fa fa-check"></i><b>5.4</b> Distribution Normal <span class="math inline">\(\mathcal{N}(\mu,\sigma^2)\)</span></a></li>
<li class="chapter" data-level="5.5" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribucion-uniforme-uab"><i class="fa fa-check"></i><b>5.5</b> Distribución Uniforme <span class="math inline">\(U(a,b)\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html"><i class="fa fa-check"></i><b>6</b> Modelos lineales y análisis de la varianza</a><ul>
<li class="chapter" data-level="6.1" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#principios-de-la-modelizacion-estadistica"><i class="fa fa-check"></i><b>6.1</b> Principios de la modelización estadística</a><ul>
<li class="chapter" data-level="6.1.1" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#identificar-y-caracterizar-variables"><i class="fa fa-check"></i><b>6.1.1</b> Identificar y Caracterizar Variables</a></li>
<li class="chapter" data-level="6.1.2" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#tipos-de-variables-y-tipo-de-modelo"><i class="fa fa-check"></i><b>6.1.2</b> Tipos de variables y tipo de modelo</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#el-modelo-lineal-general"><i class="fa fa-check"></i><b>6.2</b> El modelo lineal general</a></li>
<li class="chapter" data-level="6.3" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#definicion-de-modelos-en-r"><i class="fa fa-check"></i><b>6.3</b> Definición de modelos en <code>R</code></a><ul>
<li class="chapter" data-level="6.3.1" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#ejemplo-datos-de-precios-de-viviendas-en-boston"><i class="fa fa-check"></i><b>6.3.1</b> Ejemplo: Datos de precios de viviendas en Boston</a></li>
<li class="chapter" data-level="6.3.2" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#regresion-lineal-multiple"><i class="fa fa-check"></i><b>6.3.2</b> Regresión lineal múltiple</a></li>
<li class="chapter" data-level="6.3.3" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#ejemplo"><i class="fa fa-check"></i><b>6.3.3</b> Ejemplo:</a></li>
<li class="chapter" data-level="6.3.4" data-path="modelos-lineales-y-analisis-de-la-varianza.html"><a href="modelos-lineales-y-analisis-de-la-varianza.html#modelos-con-interacciones"><i class="fa fa-check"></i><b>6.3.4</b> Modelos con interacciones</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regresion-logistica.html"><a href="regresion-logistica.html"><i class="fa fa-check"></i><b>7</b> Regresión logística</a><ul>
<li class="chapter" data-level="7.1" data-path="regresion-logistica.html"><a href="regresion-logistica.html#ejemplo-datos-de-credito-en-alemania-credit-scoring"><i class="fa fa-check"></i><b>7.1</b> Ejemplo: Datos de crédito en Alemania (<em>Credit scoring</em>)</a></li>
<li class="chapter" data-level="7.2" data-path="regresion-logistica.html"><a href="regresion-logistica.html#ejemplo-predecir-el-salario-de-los-trabajadores"><i class="fa fa-check"></i><b>7.2</b> Ejemplo: Predecir el salario de los trabajadores</a></li>
<li class="chapter" data-level="7.3" data-path="regresion-logistica.html"><a href="regresion-logistica.html#ejemplo-datos-de-los-supervivientes-del-titanic"><i class="fa fa-check"></i><b>7.3</b> Ejemplo: Datos de los supervivientes del Titanic</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html"><i class="fa fa-check"></i><b>8</b> Modelos Aditivos Generalizados</a></li>
<li class="chapter" data-level="9" data-path="analisis-de-componentes-principales-clasificacion-y-clustering.html"><a href="analisis-de-componentes-principales-clasificacion-y-clustering.html"><i class="fa fa-check"></i><b>9</b> Análisis de Componentes Principales, Clasificación y Clustering</a></li>
<li class="chapter" data-level="10" data-path="introduccion-al-machine-learning.html"><a href="introduccion-al-machine-learning.html"><i class="fa fa-check"></i><b>10</b> Introducción al machine learning</a></li>
<li class="chapter" data-level="11" data-path="extras.html"><a href="extras.html"><i class="fa fa-check"></i><b>11</b> Extras</a></li>
<li class="divider"></li>
<li><a href="http://idaejin.github.io/" target="blank">Mi página personal</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introducción al software estadístico <code>R</code></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelos-lineales-y-analisis-de-la-varianza" class="section level1">
<h1><span class="header-section-number"> 6</span> Modelos lineales y análisis de la varianza</h1>
<div id="principios-de-la-modelizacion-estadistica" class="section level2">
<h2><span class="header-section-number">6.1</span> Principios de la modelización estadística</h2>
<ul>
<li><p>Dado un conjunto de variables, cada una de las cuales es un vector de lecturas de un rasgo específico de las muestras en un experimento.</p></li>
<li><p><strong>Problema:</strong> ¿De qué manera una variable <span class="math inline">\(Y\)</span> depende de otras variables <span class="math inline">\(X_1,...,X_n\)</span> en el estudio?</p></li>
<li><p>Un <strong>modelo estadístico</strong> define una relación matemática entre los <span class="math inline">\(X_i\)</span> y <span class="math inline">\(Y\)</span>. El modelo es una representación del real <span class="math inline">\(Y\)</span> que pretende reemplazarlo en la medida de lo posible. Al menos el modelo debería capturar la dependencia de <span class="math inline">\(Y\)</span> de los <span class="math inline">\(X_i\)</span>.</p></li>
</ul>
<div id="identificar-y-caracterizar-variables" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Identificar y Caracterizar Variables</h3>
<p>Este es el primer paso en el modelado:</p>
<ul>
<li><p>Qué variable es la variable de respuesta;</p></li>
<li><p>Qué variables son las variables explicativas;</p></li>
<li><p>¿Son las variables explicativas continuas, categóricas o una mezcla de ambas?</p></li>
<li><p>¿Cuál es la naturaleza de la variable de respuesta? ¿Es una medición contínua, un conteo, una proporción, una categoría o un tiempo hasta un evento?</p></li>
</ul>
</div>
<div id="tipos-de-variables-y-tipo-de-modelo" class="section level3">
<h3><span class="header-section-number">6.1.2</span> Tipos de variables y tipo de modelo</h3>
<ul>
<li>En función de las variables explicativas:</li>
</ul>
<table>
<colgroup>
<col width="33%" />
<col width="66%" />
</colgroup>
<thead>
<tr class="header">
<th><strong>Las variables explicativas</strong></th>
<th><strong>Modelo</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Todas las variables explicativas continuas</td>
<td>Regresión</td>
</tr>
<tr class="even">
<td>Todas las variables explicativas categóricas</td>
<td>Análisis de varianza (ANOVA)</td>
</tr>
<tr class="odd">
<td>Variables explicativas tanto continuas como categóricas</td>
<td>Regresión, Análisis de Covarianza (ANCOVA)</td>
</tr>
</tbody>
</table>
<p> </p>
<ul>
<li>En función de la variable respuesta:</li>
</ul>
<table>
<colgroup>
<col width="37%" />
<col width="62%" />
</colgroup>
<thead>
<tr class="header">
<th><em>La variable de respuesta</em></th>
<th><em>¿Qué tipo de datos es?</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Continuo</td>
<td>Regresión normal, Anova, Ancova</td>
</tr>
<tr class="even">
<td>Proporción</td>
<td>Regresión logística</td>
</tr>
<tr class="odd">
<td>Conteos</td>
<td>Modelos log-lineales (también conocidos como regresión de Poisson)</td>
</tr>
<tr class="even">
<td>Binario</td>
<td>Regresión logística binaria</td>
</tr>
<tr class="odd">
<td>Tiempo hasta evento</td>
<td>Análisis de supervivencia</td>
</tr>
</tbody>
</table>
<p> </p>
</div>
</div>
<div id="el-modelo-lineal-general" class="section level2">
<h2><span class="header-section-number">6.2</span> El modelo lineal general</h2>
<p>Los modelos lineales son una de las herramientas más importantes del análisis cuantitativo. Los utilizamos cuando queremos predecir –o explicar– una variable dependiente a partir de una o más variables independientes.</p>
<p>Se trata de un modelo para el <strong>análisis de regresión</strong>, que tiene como objetivo determinar una función matemática que describa el comportamiento de una variable dados los valores de otra u otras variables.</p>
<p>En el <strong>Análisis de regresión simple</strong>, se pretende estudiar y explicar el comportamiento de una variable que notamos <span class="math inline">\(y\)</span>, y que llamaremos <strong>variable respuesta</strong>, <strong>variable dependiente</strong> o <strong>variable de interés</strong>, a partir de otra variable, que notamos <span class="math inline">\(x\)</span>, y que llamamos <strong>variable explicativa</strong>, <strong>variable independiente</strong>, <strong>covariable</strong> o <strong>regresor</strong>. El principal objetivo de la regresión es encontrar la función que mejor explique la relación entre la variable dependiente y las independientes.</p>
<ul>
<li>Una forma muy general para el modelo sería</li>
</ul>
<p><span class="math display">\[
      y = f(x_1,x_2,...,x_p) + \epsilon,
\]</span></p>
<p>donde <span class="math inline">\(f\)</span> es una función desconocida y <span class="math inline">\(\epsilon\)</span> es el error en esta representación. Puesto que normalmente no tenemos suficientes datos para intentar estimar <span class="math inline">\(f\)</span> directamente (<em>problema inverso</em>), normalmente tenemos que asumir que tiene alguna forma restringida.</p>
<ul>
<li>La forma más simple y común es el <strong>modelo lineal (LM)</strong>.</li>
</ul>
<p><span class="math display">\[
    y = \beta_0 + \beta_1 x_1 + \beta_2 x_z + \epsilon,
\]</span></p>
<p>donde <span class="math inline">\(\beta_i\)</span> <span class="math inline">\(i=0,1,2\)</span> son parámetros <em>desconocidos</em>. <span class="math inline">\(\beta_0\)</span> se llama el término de intercepción. Por lo tanto, el problema se reduce a la estimación de cuatro valores en lugar de los complicados e infinitos <span class="math inline">\(f\)</span> dimensionales.</p>
<ul>
<li>Un modelo lineal simple con una sola variable exploratoria se define como:</li>
</ul>
<p><span class="math display">\[
         \hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x
\]</span></p>
<p>donde <span class="math inline">\(\hat y\)</span> son los valores ajustados para <span class="math inline">\(\hat{beta}_0\)</span> (intercepto) y <span class="math inline">\(\hat{\beta}_1\)</span> (pendiente). Luego por un <span class="math inline">\(x_i\)</span> dado obtenemos un <span class="math inline">\(\hat{y}_i\)</span> que se aproxima a <span class="math inline">\(y_i\)</span></p>
<p>Vamos a crear un ejemplo (con <span class="math inline">\(p=1\)</span>):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1</span>)
n &lt;-<span class="st"> </span><span class="dv">50</span> 

x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span>,n)
 beta0 &lt;-<span class="st"> </span><span class="dv">15</span>
 beta1 &lt;-<span class="st"> </span><span class="fl">0.5</span>

sigma &lt;-<span class="st"> </span><span class="dv">3</span> <span class="co"># desviación típica de los errores</span>
eps &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n,<span class="dt">mean=</span><span class="dv">0</span>,<span class="dt">sd=</span><span class="dv">3</span>) <span class="co"># generar errores aleatorios gaussianos</span>

<span class="co"># Generar datos aleatorios</span>
 y &lt;-<span class="st"> </span>beta0 <span class="op">+</span><span class="st"> </span>beta1<span class="op">*</span>x  <span class="op">+</span><span class="st">  </span>eps</code></pre></div>
<p>Representamos los datos</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(x,y,<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">8</span>,<span class="dv">45</span>), <span class="dt">cex=</span><span class="fl">1.3</span>, <span class="dt">xlab =</span> <span class="st">&quot;x&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;y&quot;</span>,<span class="dt">pch=</span><span class="dv">19</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Un procedimiento matemático para encontrar la curva que mejor se ajusta a un conjunto dado de puntos minimizando la suma de los cuadrados de los residuos de los puntos de la línea ajustada. Ilustración de los mínimos cuadrados de ajuste</p>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Podemos calcular directamente las cantidades de interés, es decir, la solución ordinaria de mínimos cuadrados:</p>
<p><span class="math display">\[
\min_{\beta_0,\beta_1} = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2  
\]</span></p>
<p>Donde</p>
<p><span class="math inline">\(\hat{\beta}_1 = \frac{\sum_{i=1}^{n}x_iy_i}{\sum_{i=1}^n x_i^2}\)</span> y <span class="math inline">\(\hat{\beta}_0 = \bar{y} - \hat{\beta}_1\bar{x}\)</span></p>
<p>En forma matricial, con <span class="math inline">\(X=[1:x_1:...:x_p]\)</span></p>
<p><span class="math display">\[
\hat{\beta}  = (X^\prime X)^{-1} X^\prime y
\]</span></p>
<p>donde <span class="math inline">\(\hat{\beta} = (\hat{\beta}_0,\hat{\beta}_1)\)</span></p>
</div>
<div id="definicion-de-modelos-en-r" class="section level2">
<h2><span class="header-section-number">6.3</span> Definición de modelos en <code>R</code></h2>
<p>Para completar una regresión lineal usando <code>R</code> primero es necesario entender la sintaxis para definir los modelos.</p>
<ul>
<li><p>Un aspecto fundamental de los modelos es el uso de fórmulas modelo para especificar las variables involucradas en el modelo y las posibles interacciones entre las variables explicativas incluidas en el modelo.</p></li>
<li><p>Una fórmula modelo se introduce en una función que realiza una regresión lineal o anova, por ejemplo.</p></li>
<li><p>Mientras que una fórmula modelo se parece un poco a una fórmula matemática, los símbolos de la “ecuación” significan cosas diferentes a las del álgebra.</p></li>
</ul>
<table>
<colgroup>
<col width="19%" />
<col width="30%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"><strong>Sintaxis</strong></th>
<th align="center"><strong>Modelo</strong></th>
<th align="center"><strong>Observaciones</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><code>y ~ x</code></td>
<td align="center"><span class="math inline">\(y = \beta_0+\beta_1x\)</span></td>
<td align="center">Línea recta con intercepto implícita</td>
</tr>
<tr class="even">
<td align="center"><code>y ~ -1 + x</code></td>
<td align="center"><span class="math inline">\(y = \beta_1x\)</span></td>
<td align="center">Línea recta sin intercepción; es decir, un ajuste forzado (0,0)</td>
</tr>
<tr class="odd">
<td align="center"><code>y ~ x + I(x^2)</code></td>
<td align="center"><span class="math inline">\(y = \beta_0+\beta_1x+\beta_2x^2\)</span></td>
<td align="center">Modelo Polinomial; <code>I()</code> permite símbolos matemáticos</td>
</tr>
<tr class="even">
<td align="center"><code>y ~ x + z</code></td>
<td align="center"><span class="math inline">\(y = \beta_0+\beta_1x+\beta_2z\)</span></td>
<td align="center">Regresión Lineal Múltiple</td>
</tr>
<tr class="odd">
<td align="center"><code>y ~ x:z</code></td>
<td align="center"><span class="math inline">\(y = \beta_0+\beta_1xz\)</span></td>
<td align="center">Modelo con interacción entre <span class="math inline">\(x\)</span> y <span class="math inline">\(z\)</span></td>
</tr>
<tr class="even">
<td align="center"><code>y ~ x*z</code></td>
<td align="center"><span class="math inline">\(y = \beta_0+\beta_1x+\beta_2z+\beta_3xz\)</span></td>
<td align="center">Equivalente a <code>y~x+z+x:z</code></td>
</tr>
</tbody>
</table>
<div id="ejemplo-datos-de-precios-de-viviendas-en-boston" class="section level3">
<h3><span class="header-section-number">6.3.1</span> Ejemplo: Datos de precios de viviendas en Boston</h3>
<p>La librería <code>MASS</code> contiene el conjunto de datos de Boston, que registra <code>medv</code> (valor mediano de la casa) de 506 vecindarios alrededor de Boston. Trataremos de predecir el medv usando 13 predictores tales como <code>rm</code> (número promedio de habitaciones por casa), <code>age</code> (edad promedio de las casas), y <code>lstat</code> (porcentaje de hogares con bajo estatus socioeconómico).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(MASS)
<span class="kw">data</span>(<span class="st">&quot;Boston&quot;</span>)
?Boston</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Gráficos</span>
<span class="kw">plot</span>(Boston<span class="op">$</span>crim,Boston<span class="op">$</span>medv,<span class="dt">col=</span><span class="dv">1</span><span class="op">+</span>Boston<span class="op">$</span>chas)
<span class="kw">legend</span>(<span class="st">&#39;topright&#39;</span>, <span class="dt">legend =</span> <span class="kw">levels</span>(<span class="kw">factor</span>(Boston<span class="op">$</span>chas)), <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>, <span class="dt">cex =</span> <span class="fl">0.8</span>, <span class="dt">pch =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-5-1.png" width="1152" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(Boston[Boston<span class="op">$</span>chas<span class="op">==</span><span class="dv">0</span>,<span class="kw">c</span>(<span class="st">&quot;crim&quot;</span>,<span class="st">&quot;medv&quot;</span>)],<span class="dt">xlim=</span><span class="kw">range</span>(Boston<span class="op">$</span>crim),<span class="dt">ylim=</span><span class="kw">range</span>(Boston<span class="op">$</span>medv),<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">cex=</span>.<span class="dv">35</span>)
<span class="kw">points</span>(Boston[Boston<span class="op">$</span>chas<span class="op">==</span><span class="dv">1</span>,<span class="kw">c</span>(<span class="st">&quot;crim&quot;</span>,<span class="st">&quot;medv&quot;</span>)],<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">pch=</span><span class="dv">2</span>)
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="kw">c</span>(<span class="st">&quot;CHAS = 0&quot;</span>, <span class="st">&quot;CHAS = 1&quot;</span>), <span class="dt">col=</span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">2</span>),<span class="dt">pch=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-5-2.png" width="1152" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(Boston)

<span class="kw">boxplot</span>(crim)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-5-3.png" width="1152" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(crim <span class="op">~</span><span class="st"> </span><span class="kw">factor</span>(chas), <span class="dt">data =</span> Boston,<span class="dt">xlab=</span><span class="st">&quot;CHAS&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;crim&quot;</span>,<span class="dt">col=</span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">2</span>),<span class="dt">varwidth=</span><span class="ot">TRUE</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-5-4.png" width="1152" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(medv <span class="op">~</span><span class="st"> </span><span class="kw">factor</span>(chas), <span class="dt">data =</span> Boston,<span class="dt">xlab=</span><span class="st">&quot;CHAS&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;crim&quot;</span>,<span class="dt">col=</span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">2</span>),<span class="dt">varwidth=</span><span class="ot">TRUE</span>)

<span class="kw">library</span>(ggplot2)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-5-5.png" width="1152" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qplot</span>(crim,medv,<span class="dt">data=</span>Boston, <span class="dt">colour=</span><span class="kw">factor</span>(chas))</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-5-6.png" width="1152" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qplot</span>(crim,medv,<span class="dt">data=</span>Boston, <span class="dt">colour=</span>tax)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-5-7.png" width="1152" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(lattice)
<span class="kw">xyplot</span>(medv<span class="op">~</span>crim,<span class="dt">groups=</span><span class="kw">factor</span>(chas),<span class="dt">auto.key =</span> <span class="ot">TRUE</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-5-8.png" width="1152" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">xyplot</span>(medv<span class="op">~</span>crim<span class="op">|</span><span class="kw">factor</span>(chas),<span class="dt">auto.key =</span> <span class="ot">TRUE</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-5-9.png" width="1152" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(Boston)</code></pre></div>
<pre><code>##  [1] &quot;crim&quot;    &quot;zn&quot;      &quot;indus&quot;   &quot;chas&quot;    &quot;nox&quot;     &quot;rm&quot;      &quot;age&quot;    
##  [8] &quot;dis&quot;     &quot;rad&quot;     &quot;tax&quot;     &quot;ptratio&quot; &quot;black&quot;   &quot;lstat&quot;   &quot;medv&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(Boston)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    506 obs. of  14 variables:
##  $ crim   : num  0.00632 0.02731 0.02729 0.03237 0.06905 ...
##  $ zn     : num  18 0 0 0 0 0 12.5 12.5 12.5 12.5 ...
##  $ indus  : num  2.31 7.07 7.07 2.18 2.18 2.18 7.87 7.87 7.87 7.87 ...
##  $ chas   : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ nox    : num  0.538 0.469 0.469 0.458 0.458 0.458 0.524 0.524 0.524 0.524 ...
##  $ rm     : num  6.58 6.42 7.18 7 7.15 ...
##  $ age    : num  65.2 78.9 61.1 45.8 54.2 58.7 66.6 96.1 100 85.9 ...
##  $ dis    : num  4.09 4.97 4.97 6.06 6.06 ...
##  $ rad    : int  1 2 2 3 3 3 5 5 5 5 ...
##  $ tax    : num  296 242 242 222 222 222 311 311 311 311 ...
##  $ ptratio: num  15.3 17.8 17.8 18.7 18.7 18.7 15.2 15.2 15.2 15.2 ...
##  $ black  : num  397 397 393 395 397 ...
##  $ lstat  : num  4.98 9.14 4.03 2.94 5.33 ...
##  $ medv   : num  24 21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 ...</code></pre>
<p> </p>
<p>Comenzaremos usando la función <code>lm()</code> para encajar un modelo de regresión lineal simple, con <code>medv</code> como respuesta y <code>lstat</code> como predictor. La sintaxis básica de <code>lm()</code> es <code>lm(y~x,data)</code>, donde <code>y</code> es la respuesta, <code>x</code> es el predictor, y los datos son el conjunto de datos en el que se guardan estas dos variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm.fit &lt;-<span class="st"> </span><span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span>lstat, <span class="dt">data=</span>Boston)</code></pre></div>
<p> </p>
<p>Si escribimos <code>lm.fit</code>, se obtiene información básica sobre el modelo. Para información más detallada, usamos <code>summary(lm.fit)</code>. Esto nos da valores de <span class="math inline">\(p\)</span> y errores estándar para los coeficientes, así como la estadística <span class="math inline">\(R^2\)</span> y el estadístico para el modelo.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm.fit</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ lstat, data = Boston)
## 
## Coefficients:
## (Intercept)        lstat  
##       34.55        -0.95</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(lm.fit)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ lstat, data = Boston)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.168  -3.990  -1.318   2.034  24.500 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 34.55384    0.56263   61.41   &lt;2e-16 ***
## lstat       -0.95005    0.03873  -24.53   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.216 on 504 degrees of freedom
## Multiple R-squared:  0.5441, Adjusted R-squared:  0.5432 
## F-statistic: 601.6 on 1 and 504 DF,  p-value: &lt; 2.2e-16</code></pre>
<p> </p>
<p>Podemos usar la función <code>names()</code> para averiguar qué otra información se almacena en <code>lm.fit</code>. Aunque podemos extraer estas cantidades por nombre - por ejemplo <code>lm.fit$coefficients</code> - es más seguro usar las funciones del extractor como <code>coef()</code> para acceder a ellas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(lm.fit)</code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm.fit<span class="op">$</span>coefficients</code></pre></div>
<pre><code>## (Intercept)       lstat 
##  34.5538409  -0.9500494</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm.fit[[<span class="dv">1</span>]]</code></pre></div>
<pre><code>## (Intercept)       lstat 
##  34.5538409  -0.9500494</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(lm.fit)</code></pre></div>
<pre><code>## (Intercept)       lstat 
##  34.5538409  -0.9500494</code></pre>
<p> </p>
<p>Para obtener un intervalo de confianza para las estimaciones del coeficiente, podemos usar el comando <code>confint()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(lm.fit, <span class="dt">level =</span> <span class="fl">0.95</span>)</code></pre></div>
<pre><code>##                 2.5 %     97.5 %
## (Intercept) 33.448457 35.6592247
## lstat       -1.026148 -0.8739505</code></pre>
<p> </p>
<p>Considere la posibilidad de construir un intervalo de confianza para <span class="math inline">\(\beta_1\)</span> utilizando la información proporcionada por el resumen de <code>lm.fit</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(lm.fit)<span class="op">$</span>coefficients</code></pre></div>
<pre><code>##               Estimate Std. Error   t value      Pr(&gt;|t|)
## (Intercept) 34.5538409 0.56262735  61.41515 3.743081e-236
## lstat       -0.9500494 0.03873342 -24.52790  5.081103e-88</code></pre>
<p> </p>
<p>La función <code>predict()</code> puede ser usada para producir intervalos de confianza e intervalos de predicción para la predicción de <code>medv</code> para un valor dado de <code>lstat</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">CI &lt;-<span class="st"> </span><span class="kw">predict</span>(<span class="dt">object =</span> lm.fit, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">lstat =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>)), 
              <span class="dt">interval =</span> <span class="st">&quot;confidence&quot;</span>)
CI</code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 29.80359 29.00741 30.59978
## 2 25.05335 24.47413 25.63256
## 3 20.30310 19.73159 20.87461</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">PI &lt;-<span class="st"> </span><span class="kw">predict</span>(<span class="dt">object =</span> lm.fit, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">lstat =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>)), 
              <span class="dt">interval =</span> <span class="st">&quot;predict&quot;</span>)
PI</code></pre></div>
<pre><code>##        fit       lwr      upr
## 1 29.80359 17.565675 42.04151
## 2 25.05335 12.827626 37.27907
## 3 20.30310  8.077742 32.52846</code></pre>
<p><em>NOTA:</em></p>
<p>Un <strong>intervalo de predicción</strong> es un intervalo asociado con una variable aleatoria que aún no ha sido observada (predicción).</p>
<p>Un <strong>intervalo de confianza</strong> es un intervalo asociado a un parámetro y es un concepto de frecuentista.</p>
<p> </p>
<p>Por ejemplo, el intervalo de confianza del 95% asociado con un valor “stat” de <span class="math inline">\(10\)</span> es <span class="math inline">\((24.474132, 25.6325627)\)</span> y el intervalo de predicción del 95% es <span class="math inline">\((12.8276263, 37.2790683)\)</span>. Como se esperaba, los intervalos de confianza y predicción se centran en el mismo punto (un valor predicho de 25,0533473 para medv cuando <code>lstat</code> es igual a 10), pero estos últimos son sustancialmente más amplios.</p>
<p> </p>
<p>Ahora trazaremos <code>medv</code> y <code>lstat</code> junto con la línea de regresión de los mínimos cuadrados usando las funciones <code>plot()</code> y <code>abline()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(medv <span class="op">~</span><span class="st"> </span>lstat, <span class="dt">data =</span> Boston)
<span class="kw">abline</span>(lm.fit)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-17-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Or using ggplot2</span>
<span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(<span class="dt">data =</span> Boston, <span class="kw">aes</span>(<span class="dt">x =</span> lstat, <span class="dt">y =</span> medv)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-18-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Hay alguna evidencia de no linealidad en la relación entre <code>lstat</code> y <code>medv</code>. Esta cuestión se discutirá más adelante.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(medv <span class="op">~</span><span class="st"> </span>lstat, <span class="dt">data =</span> Boston,<span class="dt">pch=</span><span class="dv">15</span>,<span class="dt">cex=</span>.<span class="dv">65</span>,<span class="dt">col=</span><span class="st">&quot;lightgrey&quot;</span>)
<span class="kw">abline</span>(lm.fit, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-19-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>La <code>librería(visreg)</code> permite visualizar las funciones de regresión</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># install.packages(&quot;visreg&quot;)</span>
<span class="kw">library</span>(visreg)
<span class="kw">visreg</span>(lm.fit)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-20-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>Opciones <code>pch</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">20</span>, <span class="dt">pch =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">20</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-21-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p><strong>Librería <code>ggplot2</code> con <code>lm</code></strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> Boston, <span class="kw">aes</span>(<span class="dt">x =</span> lstat, <span class="dt">y =</span> medv)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-22-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># thicker line</span>
<span class="kw">ggplot</span>(<span class="dt">data =</span> Boston, <span class="kw">aes</span>(<span class="dt">x =</span> lstat, <span class="dt">y =</span> medv)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-22-2.png" width="672" style="display: block; margin: auto;" /></p>
<p> </p>
<p>A continuación examinamos algunas gráficos de diagnóstico. Se producen automáticamente cuatro gráficas de diagnóstico aplicando la función <code>plot()</code> directamente a la salida de <code>lm()</code>. En general, este comando producirá un gráfico a la vez, y al presionar Enter se generará el siguiente gráfico. Sin embargo, a menudo es conveniente ver las cuatro parcelas juntas. Podemos lograr esto usando la función <code>par()</code>, que le dice a <code>R</code> que divida la pantalla en paneles separados para que se puedan ver múltiples gráficos simultáneamente. Por ejemplo, <code>par(mfrow = c(2, 2))</code> divide la región de trazado en una cuadrícula de paneles de 2$ por 2$.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))
<span class="kw">plot</span>(lm.fit)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-23-1.png" width="960" style="display: block; margin: auto;" /></p>
<p> </p>
<p>Alternatively, we can compute the residuals from a linear regression fit using the <code>residuals()</code> function. The function <code>rstudent()</code> will return the studentized residuals, and we can use this function to plot the residuals against the fitted values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))
<span class="kw">plot</span>(<span class="kw">predict</span>(lm.fit), <span class="kw">residuals</span>(lm.fit))
<span class="kw">plot</span>(<span class="kw">predict</span>(lm.fit), <span class="kw">rstudent</span>(lm.fit))</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-24-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p> </p>
<p>La biblioteca <code>car</code> tiene una función <code>residualPlots</code> para evaluar los residuos (calcula una prueba de curvatura para cada una de las parcelas añadiendo un término cuadrático y probando que la cuadrática sea cero). Ver <code>?residualPlots</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(car)</code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">residualPlots</span>(lm.fit)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-25-1.png" width="1152" style="display: block; margin: auto;" /></p>
<pre><code>##            Test stat Pr(&gt;|Test stat|)    
## lstat         11.627        &lt; 2.2e-16 ***
## Tukey test    11.627        &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Sobre la base de las gráficos de los residuos, hay alguna evidencia de no linealidad. Las estadísticas de apalancamiento pueden ser calculadas para cualquier número de predictores usando la función <code>hatvalues</code>. La función <code>influenceIndexPlot</code> del paquete <code>car</code> crea cuatro gráficos de diagnóstico que incluyen un gráfico de los valores de sombrero.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">hatvalues</span>(lm.fit))</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-26-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">which.max</span>(<span class="kw">hatvalues</span>(lm.fit))</code></pre></div>
<pre><code>## 375 
## 375</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">influenceIndexPlot</span>(lm.fit, <span class="dt">id.n =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## Warning in plot.window(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy, type, ...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not
## a graphical parameter

## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not
## a graphical parameter</code></pre>
<pre><code>## Warning in box(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in title(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter</code></pre>
<pre><code>## Warning in plot.window(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy, type, ...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not
## a graphical parameter

## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not
## a graphical parameter</code></pre>
<pre><code>## Warning in box(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in title(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter</code></pre>
<pre><code>## Warning in plot.window(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy, type, ...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not
## a graphical parameter

## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not
## a graphical parameter</code></pre>
<pre><code>## Warning in box(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in title(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter</code></pre>
<pre><code>## Warning in plot.window(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy, type, ...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not
## a graphical parameter

## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not
## a graphical parameter</code></pre>
<pre><code>## Warning in box(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in title(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter</code></pre>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-26-2.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="regresion-lineal-multiple" class="section level3">
<h3><span class="header-section-number">6.3.2</span> Regresión lineal múltiple</h3>
<p>Los modelos de correlación lineal múltiple requieren de las mismas condiciones que los modelos lineales simples más otras adicionales.</p>
<p>Para ajustar un modelo de regresión lineal múltiple usando mínimos cuadrados, utilizamos de nuevo la función <code>lm()</code>. La sintaxis <code>lm(y ~ x1 + x2 + x3)</code> se utiliza para ajustar un modelo con tres predictores, <code>x1</code>, <code>x2</code>, y <code>x3</code>. La función <code>summary()</code> produce ahora los coeficientes de regresión para todos los predictores.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ls.fit &lt;-<span class="st"> </span><span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span>lstat <span class="op">+</span><span class="st"> </span>age, <span class="dt">data =</span> Boston)
<span class="kw">summary</span>(ls.fit)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ lstat + age, data = Boston)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.981  -3.978  -1.283   1.968  23.158 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 33.22276    0.73085  45.458  &lt; 2e-16 ***
## lstat       -1.03207    0.04819 -21.416  &lt; 2e-16 ***
## age          0.03454    0.01223   2.826  0.00491 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.173 on 503 degrees of freedom
## Multiple R-squared:  0.5513, Adjusted R-squared:  0.5495 
## F-statistic:   309 on 2 and 503 DF,  p-value: &lt; 2.2e-16</code></pre>
<p> </p>
<p>El conjunto de datos <code>Boston</code> contiene 13 variables, por lo que sería engorroso tener que escribirlas todas para poder realizar una regresión utilizando todos los predictores. En su lugar, podemos utilizar la siguiente abreviatura:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ls.fit &lt;-<span class="st"> </span><span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> Boston)
<span class="kw">summary</span>(ls.fit)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ ., data = Boston)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.595  -2.730  -0.518   1.777  26.199 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.646e+01  5.103e+00   7.144 3.28e-12 ***
## crim        -1.080e-01  3.286e-02  -3.287 0.001087 ** 
## zn           4.642e-02  1.373e-02   3.382 0.000778 ***
## indus        2.056e-02  6.150e-02   0.334 0.738288    
## chas         2.687e+00  8.616e-01   3.118 0.001925 ** 
## nox         -1.777e+01  3.820e+00  -4.651 4.25e-06 ***
## rm           3.810e+00  4.179e-01   9.116  &lt; 2e-16 ***
## age          6.922e-04  1.321e-02   0.052 0.958229    
## dis         -1.476e+00  1.995e-01  -7.398 6.01e-13 ***
## rad          3.060e-01  6.635e-02   4.613 5.07e-06 ***
## tax         -1.233e-02  3.760e-03  -3.280 0.001112 ** 
## ptratio     -9.527e-01  1.308e-01  -7.283 1.31e-12 ***
## black        9.312e-03  2.686e-03   3.467 0.000573 ***
## lstat       -5.248e-01  5.072e-02 -10.347  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.745 on 492 degrees of freedom
## Multiple R-squared:  0.7406, Adjusted R-squared:  0.7338 
## F-statistic: 108.1 on 13 and 492 DF,  p-value: &lt; 2.2e-16</code></pre>
<p> </p>
<p>Podemos acceder a los componentes individuales de un objeto de resumen por nombre (escriea <code>?summary.lm</code> para ver qué hay disponible). Por lo tanto <code>summary(lm.fit)$r.sq</code> nos da los <span class="math inline">\(R^2\)</span>, y <code>summary(lm.fit)$sigma</code> nos da <span class="math inline">\(hat{sigma}\)</span>.</p>
<p> </p>
<p>Si queremos realizar una regresión usando todas las variables pero excepto una, podemos eliminarla usando <code>-</code>. Por ejemplo, en la salida de regresión anterior, <code>age</code> tiene un alto valor p. Así que tal vez queramos hacer una regresión excluyendo este predictor. La siguiente sintaxis resulta en una regresión usando todos los predictores excepto <code>age</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ls.fit1 &lt;-<span class="st"> </span><span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>age, <span class="dt">data =</span> Boston)
<span class="kw">summary</span>(ls.fit1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ . - age, data = Boston)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -15.6054  -2.7313  -0.5188   1.7601  26.2243 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  36.436927   5.080119   7.172 2.72e-12 ***
## crim         -0.108006   0.032832  -3.290 0.001075 ** 
## zn            0.046334   0.013613   3.404 0.000719 ***
## indus         0.020562   0.061433   0.335 0.737989    
## chas          2.689026   0.859598   3.128 0.001863 ** 
## nox         -17.713540   3.679308  -4.814 1.97e-06 ***
## rm            3.814394   0.408480   9.338  &lt; 2e-16 ***
## dis          -1.478612   0.190611  -7.757 5.03e-14 ***
## rad           0.305786   0.066089   4.627 4.75e-06 ***
## tax          -0.012329   0.003755  -3.283 0.001099 ** 
## ptratio      -0.952211   0.130294  -7.308 1.10e-12 ***
## black         0.009321   0.002678   3.481 0.000544 ***
## lstat        -0.523852   0.047625 -10.999  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.74 on 493 degrees of freedom
## Multiple R-squared:  0.7406, Adjusted R-squared:  0.7343 
## F-statistic: 117.3 on 12 and 493 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="interacciones" class="section level4">
<h4><span class="header-section-number">6.3.2.1</span> Interacciones</h4>
<p>Es fácil incluir términos de interacción en un modelo lineal usando la función <code>lm()</code>. La sintaxis <code>lstat:black</code> indica a <code>R</code> que incluya un término de interacción entre <code>lstat</code> y <code>black</code>. La sintaxis <code>lstat*age</code> incluye simultáneamente <code>lstat</code>,<code>age</code>, y el término de interacción <code>lstat</code> <span class="math inline">\(\times\)</span><code>age</code> como predictores; es una abreviatura de <code>lstat + age + lstat:age</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span>lstat<span class="op">*</span>age, <span class="dt">data =</span> Boston))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ lstat * age, data = Boston)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.806  -4.045  -1.333   2.085  27.552 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 36.0885359  1.4698355  24.553  &lt; 2e-16 ***
## lstat       -1.3921168  0.1674555  -8.313 8.78e-16 ***
## age         -0.0007209  0.0198792  -0.036   0.9711    
## lstat:age    0.0041560  0.0018518   2.244   0.0252 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.149 on 502 degrees of freedom
## Multiple R-squared:  0.5557, Adjusted R-squared:  0.5531 
## F-statistic: 209.3 on 3 and 502 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="transformaciones-no-lineales-para-los-pronosticadores" class="section level4">
<h4><span class="header-section-number">6.3.2.2</span> Transformaciones no lineales para los pronosticadores</h4>
<p>La función <code>lm()</code> también puede acomodar transformaciones no lineales de los predictores. Por ejemplo, dado un predictor <span class="math inline">\(X\)</span> podemos crear un predictor <span class="math inline">\(X^2\)</span> usando <code>I(X^2)</code>. La función <code>I()</code> es necesaria ya que <code>^</code> tiene un significado especial en una fórmula; envolviendo como lo hacemos permite el uso estándar en <code>R</code>, que es <code>I()</code> para elevar <span class="math inline">\(X\)</span> a la potencia 2. Ahora realizamos una regresión de <code>medv</code> sobre <code>lstat</code> y <code>lstat</code><span class="math inline">\(^2\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm.fit2 &lt;-<span class="st"> </span><span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span>lstat <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(lstat<span class="op">^</span><span class="dv">2</span>), <span class="dt">data =</span> Boston)
<span class="kw">summary</span>(lm.fit2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ lstat + I(lstat^2), data = Boston)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -15.2834  -3.8313  -0.5295   2.3095  25.4148 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 42.862007   0.872084   49.15   &lt;2e-16 ***
## lstat       -2.332821   0.123803  -18.84   &lt;2e-16 ***
## I(lstat^2)   0.043547   0.003745   11.63   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.524 on 503 degrees of freedom
## Multiple R-squared:  0.6407, Adjusted R-squared:  0.6393 
## F-statistic: 448.5 on 2 and 503 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot</span>
<span class="kw">visreg</span>(lm.fit2)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p> </p>
<p>El valor p cercano a cero asociado con el término cuadrático sugiere que conduce a un modelo mejorado. Usamos la función <code>anova()</code> para cuantificar aún más hasta qué punto el ajuste cuadrático es superior al ajuste lineal.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(lm.fit, lm.fit2)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: medv ~ lstat
## Model 2: medv ~ lstat + I(lstat^2)
##   Res.Df   RSS Df Sum of Sq     F    Pr(&gt;F)    
## 1    504 19472                                 
## 2    503 15347  1    4125.1 135.2 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p> </p>
<p>Aquí el Modelo 1 (<code>lm.fit</code>) representa el submodelo lineal que contiene sólo un predictor, <code>lstat</code>, mientras que el Modelo 2 (<code>lm.fit2</code>) corresponde al modelo cuadrático más grande que tiene dos predictores, <code>lstat</code> y <code>lstat</code><span class="math inline">\(^2\)</span> . La función <code>anova()</code> realiza una prueba de hipótesis comparando los dos modelos. La hipótesis nula es que los dos modelos se ajustan a los datos igualmente bien, y la hipótesis alternativa es que el modelo completo es superior. Aquí la estadística F es <code>135.1998221</code> y el valor p asociado es virtualmente cero. Esto proporciona una evidencia muy clara de que el modelo que contiene los predictores <code>lstat</code> y <code>lstat</code><span class="math inline">\(^2\)</span> es muy superior al modelo que sólo contiene el predictor <code>lstat</code>. Esto no es sorprendente, ya que antes vimos evidencia de no linealidad en la relación entre <code>medv</code> y <code>lstat</code>. Si escribimos</p>
<p> </p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(lm.fit2)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-33-1.png" width="1152" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</code></pre></div>
<p>entonces vemos que cuando el término <code>lstat</code><span class="math inline">\(^2\)</span> se incluye en el modelo, hay poco patrón discernible en los residuos.</p>
<p> </p>
<p>Para crear un ajuste cúbico, podemos incluir un predictor de la forma <code>I(X^3)</code>. Sin embargo, este enfoque puede empezar a ser engorroso para los polinomios de orden superior. Un mejor enfoque implica usar la función <code>poly()</code> para crear el polinomio dentro de <code>lm()</code>. Por ejemplo, el siguiente comando produce un ajuste polinómico de quinto orden:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm.fit5 &lt;-<span class="st"> </span><span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(lstat, <span class="dv">5</span>), <span class="dt">data =</span> Boston)
<span class="kw">summary</span>(lm.fit5)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ poly(lstat, 5), data = Boston)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.5433  -3.1039  -0.7052   2.0844  27.1153 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       22.5328     0.2318  97.197  &lt; 2e-16 ***
## poly(lstat, 5)1 -152.4595     5.2148 -29.236  &lt; 2e-16 ***
## poly(lstat, 5)2   64.2272     5.2148  12.316  &lt; 2e-16 ***
## poly(lstat, 5)3  -27.0511     5.2148  -5.187 3.10e-07 ***
## poly(lstat, 5)4   25.4517     5.2148   4.881 1.42e-06 ***
## poly(lstat, 5)5  -19.2524     5.2148  -3.692 0.000247 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.215 on 500 degrees of freedom
## Multiple R-squared:  0.6817, Adjusted R-squared:  0.6785 
## F-statistic: 214.2 on 5 and 500 DF,  p-value: &lt; 2.2e-16</code></pre>
<p> </p>
<p>Esto sugiere que incluir términos polinómicos adicionales, hasta el quinto orden, conduce a una mejora en el ajuste del modelo. Sin embargo, una investigación adicional de los datos revela que ningún término polinómico más allá del quinto orden tiene valores p significativos en un ajuste de regresión.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(<span class="dt">data =</span> Boston, <span class="kw">aes</span>(<span class="dt">x =</span> lstat, <span class="dt">y =</span> medv)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(x, <span class="dv">5</span>))</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-35-1.png" width="672" style="display: block; margin: auto;" /></p>
<p> </p>
<p>Por supuesto, no estamos restringidos a usar transformaciones polinómicas de los predictores. Aquí probamos una transformación logarítmica.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(medv <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(rm), <span class="dt">data =</span> Boston))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ log(rm), data = Boston)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -19.487  -2.875  -0.104   2.837  39.816 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -76.488      5.028  -15.21   &lt;2e-16 ***
## log(rm)       54.055      2.739   19.73   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.915 on 504 degrees of freedom
## Multiple R-squared:  0.4358, Adjusted R-squared:  0.4347 
## F-statistic: 389.3 on 1 and 504 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> Boston, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">log</span>(rm), <span class="dt">y =</span> medv)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-37-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="ejemplo" class="section level3">
<h3><span class="header-section-number">6.3.3</span> Ejemplo:</h3>
<p>Se desea conocer el gasto de alimentación mensual de una familia en función del ingreso mensual, el tamaño de la familia y el número de hijos en la universidad.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gastos &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1000</span>, <span class="dv">580</span>, <span class="dv">520</span>, <span class="dv">500</span>, <span class="dv">600</span>, <span class="dv">550</span>, <span class="dv">400</span>)
ingresos &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">50000</span>, <span class="dv">2500</span>, <span class="dv">2000</span>, <span class="dv">1900</span>, <span class="dv">3000</span>, <span class="dv">4000</span>, <span class="dv">2000</span>)
tamaño &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="dv">2</span>)
hijosU &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">0</span>)
datos &lt;-<span class="st"> </span><span class="kw">data.frame</span>(gastos,ingresos,tamaño,hijosU)
datos</code></pre></div>
<pre><code>##   gastos ingresos tamaño hijosU
## 1   1000    50000      7      3
## 2    580     2500      4      1
## 3    520     2000      3      1
## 4    500     1900      3      0
## 5    600     3000      6      1
## 6    550     4000      5      2
## 7    400     2000      2      0</code></pre>
<p>Vamos a ajustar un nuevo modelo de regresión lineal múltiple que explique el gasto de alimentación mensual en función de las variables descritas anteriormente.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reg_lin_mul &lt;-<span class="st"> </span><span class="kw">lm</span>(gastos <span class="op">~</span><span class="st"> </span>ingresos <span class="op">+</span><span class="st"> </span>tamaño <span class="op">+</span><span class="st"> </span>hijosU, <span class="dt">data=</span>datos)
<span class="kw">summary</span>(reg_lin_mul)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gastos ~ ingresos + tamaño + hijosU, data = datos)
## 
## Residuals:
##       1       2       3       4       5       6       7 
##   1.216  48.164  29.125  15.209 -10.134 -35.402 -48.178 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) 3.590e+02  6.291e+01   5.706   0.0107 *
## ingresos    7.247e-03  1.802e-03   4.021   0.0276 *
## tamaño      3.734e+01  2.046e+01   1.825   0.1655  
## hijosU      5.359e+00  4.061e+01   0.132   0.9034  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 48.57 on 3 degrees of freedom
## Multiple R-squared:  0.9677, Adjusted R-squared:  0.9353 
## F-statistic: 29.93 on 3 and 3 DF,  p-value: 0.009772</code></pre>
<p>En <code>Coefficients</code> se muestran los parámetros estimados de regresión <span class="math inline">\(\beta_0=\)</span> 359.009 . <span class="math inline">\(\beta_{\mbox{ingresos}}=\)</span> 0.007, <span class="math inline">\(\beta_{\mbox{tamaño}}=\)</span> 37.338 y <span class="math inline">\(\beta_{\mbox{hijosU}}=\)</span> 5.359.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">coef</span>(reg_lin_mul),<span class="dv">3</span>)</code></pre></div>
<pre><code>## (Intercept)    ingresos      tamaño      hijosU 
##     359.009       0.007      37.338       5.359</code></pre>
<ul>
<li>Los gastos estimados son iguales a 359.009 euros (constantes las demás variables)</li>
<li>Por cada mil euros de ingresos, los gastos aumentan en 0.007, supuesto que permanecen constantes las otras variables.</li>
<li>Por cada aumento del tamaño de la familia en un familiar, los gastos estimados aumentan en 37.338, suponiendo que se mantienen constantes las otras variables.</li>
<li>Por cada aumento del número de hijos estudiando en la Universidad, los gastos estimados aumentan en 5.359, suponiendo que se mantienen constantes las otras variables.</li>
</ul>
<p>Tanto la interpretación como la comprobación de la significación de los parámetros se realizan de forma similar al caso en que se cuenta con una única variable independiente. Igualmente, la validación se lleva a cabo del mismo modo que para la regresión lineal simple.</p>
<p>El p-valor asociado al contraste (0.009772) es menor que <span class="math inline">\(\alpha = 0.05\)</span>, por lo que rechazamos la hipótesis nula. Esto implica que al menos una de las variables independientes contribuye de forma significativa a la explicación de la variable respuesta.</p>
<p>Para las variables tamaño familiar y número de hijos en la Universidad, los p-valores son 0.1655 y 0.9034, respectivamente. Ambos mayores que 0.05, por lo que no rechazamos la hipótesis nula de significación de ambas variables. Estas variables no son válidas para predecir los gastos alimentación mensual de una familia y por tanto se pueden eliminar del modelo.</p>
<p>Con respecto a las representaciones gráficas, se pueden representar gráficos de dispersión de la variable dependiente con respecto a cada una de las variables independientes mediante el comando plot, como se ha mostrado anteriormente.</p>
<div id="otros-modelos-de-regresion-regresion-cuadratica" class="section level4">
<h4><span class="header-section-number">6.3.3.1</span> Otros modelos de regresión: regresión cuadrática</h4>
<p>Aunque los modelos de regresión lineal (tanto simple como múltiple) funcionan bien en una amplia mayoría de situaciones, en ocasiones es necesario considerar modelos más complejos para conseguir un mejor ajuste a los datos.</p>
<p>Un ejemplo de este tipo de modelos es la regresión cuadrática. El modelo más sencillo de regresión cuadrática es el siguiente:</p>
<p><span class="math display">\[
    \hat{y}_i  = \hat{\beta}_0 + \hat{\beta}_1 x_{1i} + \hat{\beta}_2 x_{2i}^2  + \epsilon_{i} 
\]</span></p>
<p>Para ajustar un modelo de regresión cuadrático, basta con indicar en el argumento formula de la función <code>lm</code> que una de las variables independientes está elevada al cuadrado mediante el símbolo <code>^2</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm</span>(<span class="dt">formula =</span> gastos <span class="op">~</span><span class="st"> </span>ingresos <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(tamaño<span class="op">^</span><span class="dv">2</span>),<span class="dt">data=</span>datos)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gastos ~ ingresos + I(tamaño^2), data = datos)
## 
## Coefficients:
## (Intercept)     ingresos  I(tamaño^2)  
##   4.341e+02    6.959e-03    4.435e+00</code></pre>
</div>
</div>
<div id="modelos-con-interacciones" class="section level3">
<h3><span class="header-section-number">6.3.4</span> Modelos con interacciones</h3>
<p>Supongamos que el departamento de ventas de una empresa quiere estudiar la influencia que tiene la publicidad a través de distintos canales sobre el número de ventas de un producto. Se dispone de un conjunto de datos que contiene los ingresos (en millones) conseguido por ventas en 200 regiones, así como la cantidad de presupuesto, también en millones, destinado a anuncios por radio, TV y periódicos en cada una de ellas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tv &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">230.1</span>, <span class="fl">44.5</span>, <span class="fl">17.2</span>, <span class="fl">151.5</span>, <span class="fl">180.8</span>, <span class="fl">8.7</span>, <span class="fl">57.5</span>, <span class="fl">120.2</span>, <span class="fl">8.6</span>, <span class="fl">199.8</span>, <span class="fl">66.1</span>, 
    <span class="fl">214.7</span>, <span class="fl">23.8</span>, <span class="fl">97.5</span>, <span class="fl">204.1</span>, <span class="fl">195.4</span>, <span class="fl">67.8</span>, <span class="fl">281.4</span>, <span class="fl">69.2</span>, <span class="fl">147.3</span>, <span class="fl">218.4</span>, <span class="fl">237.4</span>, 
    <span class="fl">13.2</span>, <span class="fl">228.3</span>, <span class="fl">62.3</span>, <span class="fl">262.9</span>, <span class="fl">142.9</span>, <span class="fl">240.1</span>, <span class="fl">248.8</span>, <span class="fl">70.6</span>, <span class="fl">292.9</span>, <span class="fl">112.9</span>, <span class="fl">97.2</span>, 
    <span class="fl">265.6</span>, <span class="fl">95.7</span>, <span class="fl">290.7</span>, <span class="fl">266.9</span>, <span class="fl">74.7</span>, <span class="fl">43.1</span>, <span class="dv">228</span>, <span class="fl">202.5</span>, <span class="dv">177</span>, <span class="fl">293.6</span>, <span class="fl">206.9</span>, <span class="fl">25.1</span>, 
    <span class="fl">175.1</span>, <span class="fl">89.7</span>, <span class="fl">239.9</span>, <span class="fl">227.2</span>, <span class="fl">66.9</span>, <span class="fl">199.8</span>, <span class="fl">100.4</span>, <span class="fl">216.4</span>, <span class="fl">182.6</span>, <span class="fl">262.7</span>, <span class="fl">198.9</span>, 
    <span class="fl">7.3</span>, <span class="fl">136.2</span>, <span class="fl">210.8</span>, <span class="fl">210.7</span>, <span class="fl">53.5</span>, <span class="fl">261.3</span>, <span class="fl">239.3</span>, <span class="fl">102.7</span>, <span class="fl">131.1</span>, <span class="dv">69</span>, <span class="fl">31.5</span>, <span class="fl">139.3</span>, 
    <span class="fl">237.4</span>, <span class="fl">216.8</span>, <span class="fl">199.1</span>, <span class="fl">109.8</span>, <span class="fl">26.8</span>, <span class="fl">129.4</span>, <span class="fl">213.4</span>, <span class="fl">16.9</span>, <span class="fl">27.5</span>, <span class="fl">120.5</span>, <span class="fl">5.4</span>, 
    <span class="dv">116</span>, <span class="fl">76.4</span>, <span class="fl">239.8</span>, <span class="fl">75.3</span>, <span class="fl">68.4</span>, <span class="fl">213.5</span>, <span class="fl">193.2</span>, <span class="fl">76.3</span>, <span class="fl">110.7</span>, <span class="fl">88.3</span>, <span class="fl">109.8</span>, <span class="fl">134.3</span>, 
    <span class="fl">28.6</span>, <span class="fl">217.7</span>, <span class="fl">250.9</span>, <span class="fl">107.4</span>, <span class="fl">163.3</span>, <span class="fl">197.6</span>, <span class="fl">184.9</span>, <span class="fl">289.7</span>, <span class="fl">135.2</span>, <span class="fl">222.4</span>, <span class="fl">296.4</span>, 
    <span class="fl">280.2</span>, <span class="fl">187.9</span>, <span class="fl">238.2</span>, <span class="fl">137.9</span>, <span class="dv">25</span>, <span class="fl">90.4</span>, <span class="fl">13.1</span>, <span class="fl">255.4</span>, <span class="fl">225.8</span>, <span class="fl">241.7</span>, <span class="fl">175.7</span>, 
    <span class="fl">209.6</span>, <span class="fl">78.2</span>, <span class="fl">75.1</span>, <span class="fl">139.2</span>, <span class="fl">76.4</span>, <span class="fl">125.7</span>, <span class="fl">19.4</span>, <span class="fl">141.3</span>, <span class="fl">18.8</span>, <span class="dv">224</span>, <span class="fl">123.1</span>, <span class="fl">229.5</span>, 
    <span class="fl">87.2</span>, <span class="fl">7.8</span>, <span class="fl">80.2</span>, <span class="fl">220.3</span>, <span class="fl">59.6</span>, <span class="fl">0.7</span>, <span class="fl">265.2</span>, <span class="fl">8.4</span>, <span class="fl">219.8</span>, <span class="fl">36.9</span>, <span class="fl">48.3</span>, <span class="fl">25.6</span>, 
    <span class="fl">273.7</span>, <span class="dv">43</span>, <span class="fl">184.9</span>, <span class="fl">73.4</span>, <span class="fl">193.7</span>, <span class="fl">220.5</span>, <span class="fl">104.6</span>, <span class="fl">96.2</span>, <span class="fl">140.3</span>, <span class="fl">240.1</span>, <span class="fl">243.2</span>, 
    <span class="dv">38</span>, <span class="fl">44.7</span>, <span class="fl">280.7</span>, <span class="dv">121</span>, <span class="fl">197.6</span>, <span class="fl">171.3</span>, <span class="fl">187.8</span>, <span class="fl">4.1</span>, <span class="fl">93.9</span>, <span class="fl">149.8</span>, <span class="fl">11.7</span>, <span class="fl">131.7</span>, 
    <span class="fl">172.5</span>, <span class="fl">85.7</span>, <span class="fl">188.4</span>, <span class="fl">163.5</span>, <span class="fl">117.2</span>, <span class="fl">234.5</span>, <span class="fl">17.9</span>, <span class="fl">206.8</span>, <span class="fl">215.4</span>, <span class="fl">284.3</span>, <span class="dv">50</span>, 
    <span class="fl">164.5</span>, <span class="fl">19.6</span>, <span class="fl">168.4</span>, <span class="fl">222.4</span>, <span class="fl">276.9</span>, <span class="fl">248.4</span>, <span class="fl">170.2</span>, <span class="fl">276.7</span>, <span class="fl">165.6</span>, <span class="fl">156.6</span>, <span class="fl">218.5</span>, 
    <span class="fl">56.2</span>, <span class="fl">287.6</span>, <span class="fl">253.8</span>, <span class="dv">205</span>, <span class="fl">139.5</span>, <span class="fl">191.1</span>, <span class="dv">286</span>, <span class="fl">18.7</span>, <span class="fl">39.5</span>, <span class="fl">75.5</span>, <span class="fl">17.2</span>, <span class="fl">166.8</span>, 
    <span class="fl">149.7</span>, <span class="fl">38.2</span>, <span class="fl">94.2</span>, <span class="dv">177</span>, <span class="fl">283.6</span>, <span class="fl">232.1</span>)
radio &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">37.8</span>, <span class="fl">39.3</span>, <span class="fl">45.9</span>, <span class="fl">41.3</span>, <span class="fl">10.8</span>, <span class="fl">48.9</span>, <span class="fl">32.8</span>, <span class="fl">19.6</span>, <span class="fl">2.1</span>, <span class="fl">2.6</span>, <span class="fl">5.8</span>, <span class="dv">24</span>, 
    <span class="fl">35.1</span>, <span class="fl">7.6</span>, <span class="fl">32.9</span>, <span class="fl">47.7</span>, <span class="fl">36.6</span>, <span class="fl">39.6</span>, <span class="fl">20.5</span>, <span class="fl">23.9</span>, <span class="fl">27.7</span>, <span class="fl">5.1</span>, <span class="fl">15.9</span>, <span class="fl">16.9</span>, <span class="fl">12.6</span>, 
    <span class="fl">3.5</span>, <span class="fl">29.3</span>, <span class="fl">16.7</span>, <span class="fl">27.1</span>, <span class="dv">16</span>, <span class="fl">28.3</span>, <span class="fl">17.4</span>, <span class="fl">1.5</span>, <span class="dv">20</span>, <span class="fl">1.4</span>, <span class="fl">4.1</span>, <span class="fl">43.8</span>, <span class="fl">49.4</span>, <span class="fl">26.7</span>, 
    <span class="fl">37.7</span>, <span class="fl">22.3</span>, <span class="fl">33.4</span>, <span class="fl">27.7</span>, <span class="fl">8.4</span>, <span class="fl">25.7</span>, <span class="fl">22.5</span>, <span class="fl">9.9</span>, <span class="fl">41.5</span>, <span class="fl">15.8</span>, <span class="fl">11.7</span>, <span class="fl">3.1</span>, <span class="fl">9.6</span>, 
    <span class="fl">41.7</span>, <span class="fl">46.2</span>, <span class="fl">28.8</span>, <span class="fl">49.4</span>, <span class="fl">28.1</span>, <span class="fl">19.2</span>, <span class="fl">49.6</span>, <span class="fl">29.5</span>, <span class="dv">2</span>, <span class="fl">42.7</span>, <span class="fl">15.5</span>, <span class="fl">29.6</span>, <span class="fl">42.8</span>, 
    <span class="fl">9.3</span>, <span class="fl">24.6</span>, <span class="fl">14.5</span>, <span class="fl">27.5</span>, <span class="fl">43.9</span>, <span class="fl">30.6</span>, <span class="fl">14.3</span>, <span class="dv">33</span>, <span class="fl">5.7</span>, <span class="fl">24.6</span>, <span class="fl">43.7</span>, <span class="fl">1.6</span>, <span class="fl">28.5</span>, 
    <span class="fl">29.9</span>, <span class="fl">7.7</span>, <span class="fl">26.7</span>, <span class="fl">4.1</span>, <span class="fl">20.3</span>, <span class="fl">44.5</span>, <span class="dv">43</span>, <span class="fl">18.4</span>, <span class="fl">27.5</span>, <span class="fl">40.6</span>, <span class="fl">25.5</span>, <span class="fl">47.8</span>, <span class="fl">4.9</span>, 
    <span class="fl">1.5</span>, <span class="fl">33.5</span>, <span class="fl">36.5</span>, <span class="dv">14</span>, <span class="fl">31.6</span>, <span class="fl">3.5</span>, <span class="dv">21</span>, <span class="fl">42.3</span>, <span class="fl">41.7</span>, <span class="fl">4.3</span>, <span class="fl">36.3</span>, <span class="fl">10.1</span>, <span class="fl">17.2</span>, <span class="fl">34.3</span>, 
    <span class="fl">46.4</span>, <span class="dv">11</span>, <span class="fl">0.3</span>, <span class="fl">0.4</span>, <span class="fl">26.9</span>, <span class="fl">8.2</span>, <span class="dv">38</span>, <span class="fl">15.4</span>, <span class="fl">20.6</span>, <span class="fl">46.8</span>, <span class="dv">35</span>, <span class="fl">14.3</span>, <span class="fl">0.8</span>, <span class="fl">36.9</span>, 
    <span class="dv">16</span>, <span class="fl">26.8</span>, <span class="fl">21.7</span>, <span class="fl">2.4</span>, <span class="fl">34.6</span>, <span class="fl">32.3</span>, <span class="fl">11.8</span>, <span class="fl">38.9</span>, <span class="dv">0</span>, <span class="dv">49</span>, <span class="dv">12</span>, <span class="fl">39.6</span>, <span class="fl">2.9</span>, <span class="fl">27.2</span>, 
    <span class="fl">33.5</span>, <span class="fl">38.6</span>, <span class="dv">47</span>, <span class="dv">39</span>, <span class="fl">28.9</span>, <span class="fl">25.9</span>, <span class="fl">43.9</span>, <span class="dv">17</span>, <span class="fl">35.4</span>, <span class="fl">33.2</span>, <span class="fl">5.7</span>, <span class="fl">14.8</span>, <span class="fl">1.9</span>, <span class="fl">7.3</span>, 
    <span class="dv">49</span>, <span class="fl">40.3</span>, <span class="fl">25.8</span>, <span class="fl">13.9</span>, <span class="fl">8.4</span>, <span class="fl">23.3</span>, <span class="fl">39.7</span>, <span class="fl">21.1</span>, <span class="fl">11.6</span>, <span class="fl">43.5</span>, <span class="fl">1.3</span>, <span class="fl">36.9</span>, <span class="fl">18.4</span>, 
    <span class="fl">18.1</span>, <span class="fl">35.8</span>, <span class="fl">18.1</span>, <span class="fl">36.8</span>, <span class="fl">14.7</span>, <span class="fl">3.4</span>, <span class="fl">37.6</span>, <span class="fl">5.2</span>, <span class="fl">23.6</span>, <span class="fl">10.6</span>, <span class="fl">11.6</span>, <span class="fl">20.9</span>, <span class="fl">20.1</span>, 
    <span class="fl">7.1</span>, <span class="fl">3.4</span>, <span class="fl">48.9</span>, <span class="fl">30.2</span>, <span class="fl">7.8</span>, <span class="fl">2.3</span>, <span class="dv">10</span>, <span class="fl">2.6</span>, <span class="fl">5.4</span>, <span class="fl">5.7</span>, <span class="dv">43</span>, <span class="fl">21.3</span>, <span class="fl">45.1</span>, <span class="fl">2.1</span>, 
    <span class="fl">28.7</span>, <span class="fl">13.9</span>, <span class="fl">12.1</span>, <span class="fl">41.1</span>, <span class="fl">10.8</span>, <span class="fl">4.1</span>, <span class="dv">42</span>, <span class="fl">35.6</span>, <span class="fl">3.7</span>, <span class="fl">4.9</span>, <span class="fl">9.3</span>, <span class="dv">42</span>, <span class="fl">8.6</span>)
periodico &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">69.2</span>, <span class="fl">45.1</span>, <span class="fl">69.3</span>, <span class="fl">58.5</span>, <span class="fl">58.4</span>, <span class="dv">75</span>, <span class="fl">23.5</span>, <span class="fl">11.6</span>, <span class="dv">1</span>, <span class="fl">21.2</span>, <span class="fl">24.2</span>, 
    <span class="dv">4</span>, <span class="fl">65.9</span>, <span class="fl">7.2</span>, <span class="dv">46</span>, <span class="fl">52.9</span>, <span class="dv">114</span>, <span class="fl">55.8</span>, <span class="fl">18.3</span>, <span class="fl">19.1</span>, <span class="fl">53.4</span>, <span class="fl">23.5</span>, <span class="fl">49.6</span>, <span class="fl">26.2</span>, <span class="fl">18.3</span>, 
    <span class="fl">19.5</span>, <span class="fl">12.6</span>, <span class="fl">22.9</span>, <span class="fl">22.9</span>, <span class="fl">40.8</span>, <span class="fl">43.2</span>, <span class="fl">38.6</span>, <span class="dv">30</span>, <span class="fl">0.3</span>, <span class="fl">7.4</span>, <span class="fl">8.5</span>, <span class="dv">5</span>, <span class="fl">45.7</span>, <span class="fl">35.1</span>, 
    <span class="dv">32</span>, <span class="fl">31.6</span>, <span class="fl">38.7</span>, <span class="fl">1.8</span>, <span class="fl">26.4</span>, <span class="fl">43.3</span>, <span class="fl">31.5</span>, <span class="fl">35.7</span>, <span class="fl">18.5</span>, <span class="fl">49.9</span>, <span class="fl">36.8</span>, <span class="fl">34.6</span>, <span class="fl">3.6</span>, 
    <span class="fl">39.6</span>, <span class="fl">58.7</span>, <span class="fl">15.9</span>, <span class="dv">60</span>, <span class="fl">41.4</span>, <span class="fl">16.6</span>, <span class="fl">37.7</span>, <span class="fl">9.3</span>, <span class="fl">21.4</span>, <span class="fl">54.7</span>, <span class="fl">27.3</span>, <span class="fl">8.4</span>, <span class="fl">28.9</span>, 
    <span class="fl">0.9</span>, <span class="fl">2.2</span>, <span class="fl">10.2</span>, <span class="dv">11</span>, <span class="fl">27.2</span>, <span class="fl">38.7</span>, <span class="fl">31.7</span>, <span class="fl">19.3</span>, <span class="fl">31.3</span>, <span class="fl">13.1</span>, <span class="fl">89.4</span>, <span class="fl">20.7</span>, <span class="fl">14.2</span>, 
    <span class="fl">9.4</span>, <span class="fl">23.1</span>, <span class="fl">22.3</span>, <span class="fl">36.9</span>, <span class="fl">32.5</span>, <span class="fl">35.6</span>, <span class="fl">33.8</span>, <span class="fl">65.7</span>, <span class="dv">16</span>, <span class="fl">63.2</span>, <span class="fl">73.4</span>, <span class="fl">51.4</span>, <span class="fl">9.3</span>, 
    <span class="dv">33</span>, <span class="dv">59</span>, <span class="fl">72.3</span>, <span class="fl">10.9</span>, <span class="fl">52.9</span>, <span class="fl">5.9</span>, <span class="dv">22</span>, <span class="fl">51.2</span>, <span class="fl">45.9</span>, <span class="fl">49.8</span>, <span class="fl">100.9</span>, <span class="fl">21.4</span>, <span class="fl">17.9</span>, 
    <span class="fl">5.3</span>, <span class="dv">59</span>, <span class="fl">29.7</span>, <span class="fl">23.2</span>, <span class="fl">25.6</span>, <span class="fl">5.5</span>, <span class="fl">56.5</span>, <span class="fl">23.2</span>, <span class="fl">2.4</span>, <span class="fl">10.7</span>, <span class="fl">34.5</span>, <span class="fl">52.7</span>, <span class="fl">25.6</span>, 
    <span class="fl">14.8</span>, <span class="fl">79.2</span>, <span class="fl">22.3</span>, <span class="fl">46.2</span>, <span class="fl">50.4</span>, <span class="fl">15.6</span>, <span class="fl">12.4</span>, <span class="fl">74.2</span>, <span class="fl">25.9</span>, <span class="fl">50.6</span>, <span class="fl">9.2</span>, <span class="fl">3.2</span>, <span class="fl">43.1</span>, 
    <span class="fl">8.7</span>, <span class="dv">43</span>, <span class="fl">2.1</span>, <span class="fl">45.1</span>, <span class="fl">65.6</span>, <span class="fl">8.5</span>, <span class="fl">9.3</span>, <span class="fl">59.7</span>, <span class="fl">20.5</span>, <span class="fl">1.7</span>, <span class="fl">12.9</span>, <span class="fl">75.6</span>, <span class="fl">37.9</span>, <span class="fl">34.4</span>, 
    <span class="fl">38.9</span>, <span class="dv">9</span>, <span class="fl">8.7</span>, <span class="fl">44.3</span>, <span class="fl">11.9</span>, <span class="fl">20.6</span>, <span class="dv">37</span>, <span class="fl">48.7</span>, <span class="fl">14.2</span>, <span class="fl">37.7</span>, <span class="fl">9.5</span>, <span class="fl">5.7</span>, <span class="fl">50.5</span>, <span class="fl">24.3</span>, 
    <span class="fl">45.2</span>, <span class="fl">34.6</span>, <span class="fl">30.7</span>, <span class="fl">49.3</span>, <span class="fl">25.6</span>, <span class="fl">7.4</span>, <span class="fl">5.4</span>, <span class="fl">84.8</span>, <span class="fl">21.6</span>, <span class="fl">19.4</span>, <span class="fl">57.6</span>, <span class="fl">6.4</span>, <span class="fl">18.4</span>, 
    <span class="fl">47.4</span>, <span class="dv">17</span>, <span class="fl">12.8</span>, <span class="fl">13.1</span>, <span class="fl">41.8</span>, <span class="fl">20.3</span>, <span class="fl">35.2</span>, <span class="fl">23.7</span>, <span class="fl">17.6</span>, <span class="fl">8.3</span>, <span class="fl">27.4</span>, <span class="fl">29.7</span>, <span class="fl">71.8</span>, 
    <span class="dv">30</span>, <span class="fl">19.6</span>, <span class="fl">26.6</span>, <span class="fl">18.2</span>, <span class="fl">3.7</span>, <span class="fl">23.4</span>, <span class="fl">5.8</span>, <span class="dv">6</span>, <span class="fl">31.6</span>, <span class="fl">3.6</span>, <span class="dv">6</span>, <span class="fl">13.8</span>, <span class="fl">8.1</span>, <span class="fl">6.4</span>, <span class="fl">66.2</span>, 
    <span class="fl">8.7</span>)
ventas &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">22.1</span>, <span class="fl">10.4</span>, <span class="fl">9.3</span>, <span class="fl">18.5</span>, <span class="fl">12.9</span>, <span class="fl">7.2</span>, <span class="fl">11.8</span>, <span class="fl">13.2</span>, <span class="fl">4.8</span>, <span class="fl">10.6</span>, <span class="fl">8.6</span>, <span class="fl">17.4</span>, 
    <span class="fl">9.2</span>, <span class="fl">9.7</span>, <span class="dv">19</span>, <span class="fl">22.4</span>, <span class="fl">12.5</span>, <span class="fl">24.4</span>, <span class="fl">11.3</span>, <span class="fl">14.6</span>, <span class="dv">18</span>, <span class="fl">12.5</span>, <span class="fl">5.6</span>, <span class="fl">15.5</span>, <span class="fl">9.7</span>, <span class="dv">12</span>, 
    <span class="dv">15</span>, <span class="fl">15.9</span>, <span class="fl">18.9</span>, <span class="fl">10.5</span>, <span class="fl">21.4</span>, <span class="fl">11.9</span>, <span class="fl">9.6</span>, <span class="fl">17.4</span>, <span class="fl">9.5</span>, <span class="fl">12.8</span>, <span class="fl">25.4</span>, <span class="fl">14.7</span>, <span class="fl">10.1</span>, 
    <span class="fl">21.5</span>, <span class="fl">16.6</span>, <span class="fl">17.1</span>, <span class="fl">20.7</span>, <span class="fl">12.9</span>, <span class="fl">8.5</span>, <span class="fl">14.9</span>, <span class="fl">10.6</span>, <span class="fl">23.2</span>, <span class="fl">14.8</span>, <span class="fl">9.7</span>, <span class="fl">11.4</span>, <span class="fl">10.7</span>, 
    <span class="fl">22.6</span>, <span class="fl">21.2</span>, <span class="fl">20.2</span>, <span class="fl">23.7</span>, <span class="fl">5.5</span>, <span class="fl">13.2</span>, <span class="fl">23.8</span>, <span class="fl">18.4</span>, <span class="fl">8.1</span>, <span class="fl">24.2</span>, <span class="fl">15.7</span>, <span class="dv">14</span>, <span class="dv">18</span>, 
    <span class="fl">9.3</span>, <span class="fl">9.5</span>, <span class="fl">13.4</span>, <span class="fl">18.9</span>, <span class="fl">22.3</span>, <span class="fl">18.3</span>, <span class="fl">12.4</span>, <span class="fl">8.8</span>, <span class="dv">11</span>, <span class="dv">17</span>, <span class="fl">8.7</span>, <span class="fl">6.9</span>, <span class="fl">14.2</span>, <span class="fl">5.3</span>, 
    <span class="dv">11</span>, <span class="fl">11.8</span>, <span class="fl">12.3</span>, <span class="fl">11.3</span>, <span class="fl">13.6</span>, <span class="fl">21.7</span>, <span class="fl">15.2</span>, <span class="dv">12</span>, <span class="dv">16</span>, <span class="fl">12.9</span>, <span class="fl">16.7</span>, <span class="fl">11.2</span>, <span class="fl">7.3</span>, <span class="fl">19.4</span>, 
    <span class="fl">22.2</span>, <span class="fl">11.5</span>, <span class="fl">16.9</span>, <span class="fl">11.7</span>, <span class="fl">15.5</span>, <span class="fl">25.4</span>, <span class="fl">17.2</span>, <span class="fl">11.7</span>, <span class="fl">23.8</span>, <span class="fl">14.8</span>, <span class="fl">14.7</span>, <span class="fl">20.7</span>, 
    <span class="fl">19.2</span>, <span class="fl">7.2</span>, <span class="fl">8.7</span>, <span class="fl">5.3</span>, <span class="fl">19.8</span>, <span class="fl">13.4</span>, <span class="fl">21.8</span>, <span class="fl">14.1</span>, <span class="fl">15.9</span>, <span class="fl">14.6</span>, <span class="fl">12.6</span>, <span class="fl">12.2</span>, <span class="fl">9.4</span>, 
    <span class="fl">15.9</span>, <span class="fl">6.6</span>, <span class="fl">15.5</span>, <span class="dv">7</span>, <span class="fl">11.6</span>, <span class="fl">15.2</span>, <span class="fl">19.7</span>, <span class="fl">10.6</span>, <span class="fl">6.6</span>, <span class="fl">8.8</span>, <span class="fl">24.7</span>, <span class="fl">9.7</span>, <span class="fl">1.6</span>, <span class="fl">12.7</span>, 
    <span class="fl">5.7</span>, <span class="fl">19.6</span>, <span class="fl">10.8</span>, <span class="fl">11.6</span>, <span class="fl">9.5</span>, <span class="fl">20.8</span>, <span class="fl">9.6</span>, <span class="fl">20.7</span>, <span class="fl">10.9</span>, <span class="fl">19.2</span>, <span class="fl">20.1</span>, <span class="fl">10.4</span>, <span class="fl">11.4</span>, 
    <span class="fl">10.3</span>, <span class="fl">13.2</span>, <span class="fl">25.4</span>, <span class="fl">10.9</span>, <span class="fl">10.1</span>, <span class="fl">16.1</span>, <span class="fl">11.6</span>, <span class="fl">16.6</span>, <span class="dv">19</span>, <span class="fl">15.6</span>, <span class="fl">3.2</span>, <span class="fl">15.3</span>, <span class="fl">10.1</span>, 
    <span class="fl">7.3</span>, <span class="fl">12.9</span>, <span class="fl">14.4</span>, <span class="fl">13.3</span>, <span class="fl">14.9</span>, <span class="dv">18</span>, <span class="fl">11.9</span>, <span class="fl">11.9</span>, <span class="dv">8</span>, <span class="fl">12.2</span>, <span class="fl">17.1</span>, <span class="dv">15</span>, <span class="fl">8.4</span>, <span class="fl">14.5</span>, 
    <span class="fl">7.6</span>, <span class="fl">11.7</span>, <span class="fl">11.5</span>, <span class="dv">27</span>, <span class="fl">20.2</span>, <span class="fl">11.7</span>, <span class="fl">11.8</span>, <span class="fl">12.6</span>, <span class="fl">10.5</span>, <span class="fl">12.2</span>, <span class="fl">8.7</span>, <span class="fl">26.2</span>, <span class="fl">17.6</span>, 
    <span class="fl">22.6</span>, <span class="fl">10.3</span>, <span class="fl">17.3</span>, <span class="fl">15.9</span>, <span class="fl">6.7</span>, <span class="fl">10.8</span>, <span class="fl">9.9</span>, <span class="fl">5.9</span>, <span class="fl">19.6</span>, <span class="fl">17.3</span>, <span class="fl">7.6</span>, <span class="fl">9.7</span>, <span class="fl">12.8</span>, 
    <span class="fl">25.5</span>, <span class="fl">13.4</span>)

datos &lt;-<span class="st"> </span><span class="kw">data.frame</span>(tv, radio, periodico, ventas)</code></pre></div>
<p>El modelo lineal múltiple que se obtiene empleando las variables <code>tv</code>, <code>radio</code> y <code>periodico</code> como predictores de ventas es el siguiente:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modelo &lt;-<span class="st"> </span><span class="kw">lm</span>(ventas <span class="op">~</span><span class="st"> </span>tv <span class="op">+</span><span class="st"> </span>radio <span class="op">+</span><span class="st"> </span>periodico, <span class="dt">data =</span> datos)
<span class="kw">summary</span>(modelo)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ventas ~ tv + radio + periodico, data = datos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.8277 -0.8908  0.2418  1.1893  2.8292 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.938889   0.311908   9.422   &lt;2e-16 ***
## tv           0.045765   0.001395  32.809   &lt;2e-16 ***
## radio        0.188530   0.008611  21.893   &lt;2e-16 ***
## periodico   -0.001037   0.005871  -0.177     0.86    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.686 on 196 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8956 
## F-statistic: 570.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>De acuerdo al p-value obtenido para el coeficiente parcial de regresión de <code>periodico</code>, esta variable no contribuye de forma significativa al modelo. Como resultado de este análisis se concluye que las variables <code>tv</code> y <code>radio</code> están asociadas con la cantidad de ventas.</p>
<p>Con el comando <code>update()</code>, podemos actualizar el <code>modelo</code>. Por ejemplo:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modelo &lt;-<span class="st"> </span><span class="kw">update</span>(modelo, .<span class="op">~</span>. <span class="op">-</span>periodico)
<span class="kw">summary</span>(modelo)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ventas ~ tv + radio, data = datos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.7977 -0.8752  0.2422  1.1708  2.8328 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.92110    0.29449   9.919   &lt;2e-16 ***
## tv           0.04575    0.00139  32.909   &lt;2e-16 ***
## radio        0.18799    0.00804  23.382   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.681 on 197 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8962 
## F-statistic: 859.6 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Al ser un modelo con dos predictores continuos se puede representar en 3D</p>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-45-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>El modelo lineal a partir del cual se han obtenido las conclusiones asume que el efecto sobre las ventas debido a un incremento en el presupuesto de uno de los medios de comunicación es independiente del presupuesto gastado en los otros. Por ejemplo, el modelo lineal considera que el efecto promedio sobre las ventas debido a aumentar en una unidad el presupuesto de anuncios en TV es siempre de 0.04575, independientemente de la cantidad invertida en anuncios por radio. Sin embargo, la representación gráfica muestra que el modelo tiende a sobrevalorar las ventas cuando el presupuesto es muy alto en uno de los medios pero muy bajo en el otro. Por contra, los valores de ventas predichos por el modelo están por debajo de las ventas reales cuando el presupuesto está repartido de forma equitativa entre ambos medios. Este comportamiento sugiere que existe interacción entre los predictores, por lo que el efecto de cada uno de ellos sobre la variable respuesta depende en cierta medida del valor que tome el otro predictor.</p>
<p>Tal y como se ha definido previamente, un modelo lineal con dos predictores sigue la ecuación:</p>
<p><span class="math display">\[
Y={\beta}_0+ \beta_1 X_1+ \beta_2 X_2+ \epsilon
\]</span></p>
<p>De acuerdo a esta definición, el incremento de una unidad en el predictor <span class="math inline">\(X_1\)</span> produce un incremento promedio de la variable <span class="math inline">\(Y\)</span> de <span class="math inline">\(\beta_1\)</span>. Modificaciones en el predictor <span class="math inline">\(X_2\)</span> no alteran este hecho, y lo mismo ocurre con <span class="math inline">\(X_2\)</span> respecto a <span class="math inline">\(X_1\)</span>. Para que el modelo pueda contemplar la interacción se introduce un tercer predictor, que se construye con el producto de los predictores <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span>.</p>
<p><span class="math display">\[
Y=\beta_0+\beta_1 X_1+\beta_2 X_2+ \beta_3 X_1X_2+\epsilon
\]</span> La reorganización de los términos resulta en:</p>
<p><span class="math display">\[
  Y=\beta_0+(\beta_1+\beta_3 X_2)X_1+\beta_2X_2+\epsilon
\]</span> El efecto de <span class="math inline">\(X_1\)</span> sobre <span class="math inline">\(Y\)</span> ya no es constante, sino que depende del valor que tome <span class="math inline">\(X_2\)</span>.</p>
<p>En <code>R</code> se puede introducir interacción entre predictores de dos formas, indicando los predictores individuales y entre cuales se quiere evaluar la interacción, o bien de forma directa.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modelo_interaccion &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> ventas <span class="op">~</span><span class="st"> </span>tv <span class="op">+</span><span class="st"> </span>radio <span class="op">+</span><span class="st"> </span>tv<span class="op">:</span>radio, <span class="dt">data =</span> datos)
<span class="kw">summary</span>(modelo_interaccion)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ventas ~ tv + radio + tv:radio, data = datos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.3366 -0.4028  0.1831  0.5948  1.5246 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 6.750e+00  2.479e-01  27.233   &lt;2e-16 ***
## tv          1.910e-02  1.504e-03  12.699   &lt;2e-16 ***
## radio       2.886e-02  8.905e-03   3.241   0.0014 ** 
## tv:radio    1.086e-03  5.242e-05  20.727   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9435 on 196 degrees of freedom
## Multiple R-squared:  0.9678, Adjusted R-squared:  0.9673 
## F-statistic:  1963 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># O tambien</span>
<span class="co"># lm(formula = ventas ~ tv * radio, data = datos) es equivalente.</span></code></pre></div>
<p><img src="cursoR_Euskaltel_files/figure-html/unnamed-chunk-47-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Los resultados muestran una evidencia clara de que la interacción <code>tv:radio</code> es significativa y de que el modelo que incorpora la interacción (Adjusted R-squared = 0.9673) es superior al modelo que solo contemplaba el efecto de los predictores por separado (Adjusted R-squared = 0.8956).</p>
<p>Se puede emplear un ANOVA para realizar un test de hipótesis y obtener un p-value que evalúe la hipótesis nula de que ambos modelos se ajustan a los datos igual de bien.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(modelo, modelo_interaccion)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: ventas ~ tv + radio
## Model 2: ventas ~ tv + radio + tv:radio
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    197 556.91                                  
## 2    196 174.48  1    382.43 429.59 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>En los modelos de regresión lineal múltiple que incorporan interacciones entre predictores hay que tener en cuenta que si se incorpora al modelo una interacción entre predictores, se deben incluir siempre los predictores individuales que participan en la interacción, independientemente de que su p-value sega significativo o no.</p>
<p>La interacción entre predictores no está limitada a predictores cuantitativos, también puede crearse interacción entre predictor cuantitativo y cualitativo.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="distribuciones-de-probabilidad-en-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regresion-logistica.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"download": ["cursoR_Euskaltel.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
