<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title> 5 Probability distributions | Introducción al software estadístico R</title>
  <meta name="description" content="Material del curso de Formación en R Euskaltel">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content=" 5 Probability distributions | Introducción al software estadístico R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Material del curso de Formación en R Euskaltel" />
  <meta name="github-repo" content="idaejin/xxx" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 5 Probability distributions | Introducción al software estadístico R" />
  
  <meta name="twitter:description" content="Material del curso de Formación en R Euskaltel" />
  

<meta name="author" content="Dae-Jin Lee &lt; dlee@bcamath.org &gt;">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="introduccion-a-la-programacion-basica-con-r.html">
<link rel="next" href="casos-de-estudio.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Curso de formación en R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Información y pre-requisitos</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introducción al software estadístico <code>R</code></a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#instalar-un-paquete-de-r"><i class="fa fa-check"></i><b>2.1</b> Instalar un paquete de <code>R</code></a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#empezando-con-r"><i class="fa fa-check"></i><b>2.2</b> Empezando con <code>R</code></a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#instalar-y-cargar-librerias-en-r"><i class="fa fa-check"></i><b>2.3</b> Instalar y cargar librerías en <code>R</code></a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#lectura-de-datos"><i class="fa fa-check"></i><b>2.4</b> Lectura de datos</a></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#importar-datos"><i class="fa fa-check"></i><b>2.5</b> Importar datos</a></li>
<li class="chapter" data-level="2.6" data-path="intro.html"><a href="intro.html#exportar-datos"><i class="fa fa-check"></i><b>2.6</b> Exportar datos</a></li>
<li class="chapter" data-level="2.7" data-path="intro.html"><a href="intro.html#vectores"><i class="fa fa-check"></i><b>2.7</b> Vectores</a></li>
<li class="chapter" data-level="2.8" data-path="intro.html"><a href="intro.html#estadistica-basica"><i class="fa fa-check"></i><b>2.8</b> Estadística básica</a></li>
<li class="chapter" data-level="2.9" data-path="intro.html"><a href="intro.html#vectores-caracteres-y-variables-factor"><i class="fa fa-check"></i><b>2.9</b> Vectores caracteres y variables factor</a></li>
<li class="chapter" data-level="2.10" data-path="intro.html"><a href="intro.html#data-frames"><i class="fa fa-check"></i><b>2.10</b> Data frames</a></li>
<li class="chapter" data-level="2.11" data-path="intro.html"><a href="intro.html#trabajando-con-data-frames"><i class="fa fa-check"></i><b>2.11</b> Trabajando con data frames</a></li>
<li class="chapter" data-level="2.12" data-path="intro.html"><a href="intro.html#vectores-logicos"><i class="fa fa-check"></i><b>2.12</b> Vectores lógicos</a></li>
<li class="chapter" data-level="2.13" data-path="intro.html"><a href="intro.html#trabajando-con-vectores"><i class="fa fa-check"></i><b>2.13</b> Trabajando con vectores</a></li>
<li class="chapter" data-level="2.14" data-path="intro.html"><a href="intro.html#matrices-y-arrays"><i class="fa fa-check"></i><b>2.14</b> Matrices y arrays</a></li>
<li class="chapter" data-level="2.15" data-path="intro.html"><a href="intro.html#factores"><i class="fa fa-check"></i><b>2.15</b> Factores</a></li>
<li class="chapter" data-level="2.16" data-path="intro.html"><a href="intro.html#indexando-vectores-con-condiciones-logicas"><i class="fa fa-check"></i><b>2.16</b> Indexando vectores con condiciones lógicas</a></li>
<li class="chapter" data-level="2.17" data-path="intro.html"><a href="intro.html#valores-faltantes"><i class="fa fa-check"></i><b>2.17</b> Valores faltantes</a></li>
<li class="chapter" data-level="2.18" data-path="intro.html"><a href="intro.html#trabajando-con-data-frames-1"><i class="fa fa-check"></i><b>2.18</b> Trabajando con data frames</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="analisis-de-datos-basico-en-r.html"><a href="analisis-de-datos-basico-en-r.html"><i class="fa fa-check"></i><b>3</b> Análisis de datos básico en <code>R</code></a><ul>
<li class="chapter" data-level="3.1" data-path="analisis-de-datos-basico-en-r.html"><a href="analisis-de-datos-basico-en-r.html#graficos-sencillos"><i class="fa fa-check"></i><b>3.1</b> Gráficos sencillos</a></li>
<li class="chapter" data-level="3.2" data-path="analisis-de-datos-basico-en-r.html"><a href="analisis-de-datos-basico-en-r.html#scatterplots"><i class="fa fa-check"></i><b>3.2</b> Scatterplots</a></li>
<li class="chapter" data-level="3.3" data-path="analisis-de-datos-basico-en-r.html"><a href="analisis-de-datos-basico-en-r.html#mas-opciones-graficas"><i class="fa fa-check"></i><b>3.3</b> más opciones gráficas</a></li>
<li class="chapter" data-level="3.4" data-path="analisis-de-datos-basico-en-r.html"><a href="analisis-de-datos-basico-en-r.html#tablas-de-clasificacion-cruzada-o-de-contigencia"><i class="fa fa-check"></i><b>3.4</b> Tablas de clasificación cruzada o de contigencia</a></li>
<li class="chapter" data-level="3.5" data-path="analisis-de-datos-basico-en-r.html"><a href="analisis-de-datos-basico-en-r.html#calculos-sobre-tablas-de-contigencia"><i class="fa fa-check"></i><b>3.5</b> cálculos sobre tablas de contigencia</a></li>
<li class="chapter" data-level="3.6" data-path="analisis-de-datos-basico-en-r.html"><a href="analisis-de-datos-basico-en-r.html#datos-cualitativos"><i class="fa fa-check"></i><b>3.6</b> Datos cualitativos</a></li>
<li class="chapter" data-level="3.7" data-path="analisis-de-datos-basico-en-r.html"><a href="analisis-de-datos-basico-en-r.html#datos-cuantitativos"><i class="fa fa-check"></i><b>3.7</b> Datos cuantitativos</a><ul>
<li class="chapter" data-level="3.7.1" data-path="analisis-de-datos-basico-en-r.html"><a href="analisis-de-datos-basico-en-r.html#distribuciones-de-frecuencias"><i class="fa fa-check"></i><b>3.7.1</b> Distribuciones de frecuencias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html"><i class="fa fa-check"></i><b>4</b> Introducción a la programación básica con <code>R</code></a><ul>
<li class="chapter" data-level="4.1" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#condicionales"><i class="fa fa-check"></i><b>4.1</b> Condicionales</a></li>
<li class="chapter" data-level="4.2" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#operadores-logicos"><i class="fa fa-check"></i><b>4.2</b> Operadores Lógicos</a></li>
<li class="chapter" data-level="4.3" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#if-statements"><i class="fa fa-check"></i><b>4.3</b> <code>if</code> statements</a></li>
<li class="chapter" data-level="4.4" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#ifelse"><i class="fa fa-check"></i><b>4.4</b> <code>ifelse</code></a></li>
<li class="chapter" data-level="4.5" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#while"><i class="fa fa-check"></i><b>4.5</b> <code>while</code></a></li>
<li class="chapter" data-level="4.6" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#loops-o-bucles"><i class="fa fa-check"></i><b>4.6</b> Loops o Bucles</a><ul>
<li class="chapter" data-level="4.6.1" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#for"><i class="fa fa-check"></i><b>4.6.1</b> <code>for</code></a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#while-1"><i class="fa fa-check"></i><b>4.7</b> <code>while</code></a></li>
<li class="chapter" data-level="4.8" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#famila-de-funciones-apply"><i class="fa fa-check"></i><b>4.8</b> Famila de funciones <code>apply</code></a></li>
<li class="chapter" data-level="4.9" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#other-loops"><i class="fa fa-check"></i><b>4.9</b> Other Loops</a></li>
<li class="chapter" data-level="4.10" data-path="introduccion-a-la-programacion-basica-con-r.html"><a href="introduccion-a-la-programacion-basica-con-r.html#improving-speed-performance-of-loops"><i class="fa fa-check"></i><b>4.10</b> Improving Speed Performance of Loops</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="probability-distributions.html"><a href="probability-distributions.html"><i class="fa fa-check"></i><b>5</b> Probability distributions</a><ul>
<li class="chapter" data-level="5.1" data-path="probability-distributions.html"><a href="probability-distributions.html#binomial-distribution-binnp"><i class="fa fa-check"></i><b>5.1</b> Binomial distribution <span class="math inline">\(Bin(n,p)\)</span></a></li>
<li class="chapter" data-level="5.2" data-path="probability-distributions.html"><a href="probability-distributions.html#poisson-distribution-poislambda"><i class="fa fa-check"></i><b>5.2</b> Poisson distribution <span class="math inline">\(Pois(\lambda)\)</span></a><ul>
<li class="chapter" data-level="5.2.1" data-path="probability-distributions.html"><a href="probability-distributions.html#aproximation-of-binomial-as-poisson"><i class="fa fa-check"></i><b>5.2.1</b> Aproximation of Binomial as Poisson</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="probability-distributions.html"><a href="probability-distributions.html#exponential-distribution-explambda"><i class="fa fa-check"></i><b>5.3</b> Exponential distribution <span class="math inline">\(Exp(\lambda)\)</span></a></li>
<li class="chapter" data-level="5.4" data-path="probability-distributions.html"><a href="probability-distributions.html#the-normal-distribution-mathcalnmusigma2"><i class="fa fa-check"></i><b>5.4</b> The Normal distribution <span class="math inline">\(\mathcal{N}(\mu,\sigma^2)\)</span></a></li>
<li class="chapter" data-level="5.5" data-path="probability-distributions.html"><a href="probability-distributions.html#uniform-distribution-uab"><i class="fa fa-check"></i><b>5.5</b> Uniform distribution <span class="math inline">\(U(a,b)\)</span></a><ul>
<li class="chapter" data-level="5.5.1" data-path="probability-distributions.html"><a href="probability-distributions.html#exercises"><i class="fa fa-check"></i><b>5.5.1</b> Exercises</a></li>
<li class="chapter" data-level="5.5.2" data-path="probability-distributions.html"><a href="probability-distributions.html#qq-plot"><i class="fa fa-check"></i><b>5.5.2</b> QQ-plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="casos-de-estudio.html"><a href="casos-de-estudio.html"><i class="fa fa-check"></i><b>6</b> Casos de estudio</a><ul>
<li class="chapter" data-level="6.1" data-path="casos-de-estudio.html"><a href="casos-de-estudio.html#el-ranking-forbes-2000-de-las-mayores-empresas-del-mundo-ano-2004"><i class="fa fa-check"></i><b>6.1</b> El ranking Forbes 2000 de las mayores empresas del mundo (año 2004)</a></li>
<li class="chapter" data-level="6.2" data-path="casos-de-estudio.html"><a href="casos-de-estudio.html#melanoma-maligno-en-los-estados-unidos"><i class="fa fa-check"></i><b>6.2</b> Melanoma maligno en los Estados Unidos</a></li>
<li class="chapter" data-level="6.3" data-path="casos-de-estudio.html"><a href="casos-de-estudio.html#mapeo-de-las-tasas-de-mortalidad"><i class="fa fa-check"></i><b>6.3</b> Mapeo de las tasas de mortalidad</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://idaejin.github.io/" target="blank">Mi página personal</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introducción al software estadístico <code>R</code></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="probability-distributions" class="section level1">
<h1><span class="header-section-number"> 5</span> Probability distributions</h1>
<ul>
<li><p>We look at some of the basic operations associated with probability distributions.</p></li>
<li><p>There are a large number of probability distributions available, but we only look at a few.</p></li>
<li><p>To get a full list of the distributions available in R you can use the following command:</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">help</span>(<span class="st">&quot;Distributions&quot;</span>)</code></pre></div>
<ul>
<li><p>For every distribution there are four commands. The commands for each distribution are prepended with a letter to indicate the functionality:</p>
<ul>
<li><code>d</code>: returns the probability density function</li>
<li><code>p</code>: returns the cumulative density function</li>
<li><code>q</code>: returns the inverse cumulative density function (quantiles)</li>
<li><code>r</code>: returns randomly generated numbers</li>
</ul></li>
</ul>
<div id="binomial-distribution-binnp" class="section level2">
<h2><span class="header-section-number">5.1</span> Binomial distribution <span class="math inline">\(Bin(n,p)\)</span></h2>
<ul>
<li>The binomial distribution is a discrete probability distribution. It describes the outcome of <span class="math inline">\(n\)</span> independent trials in an experiment. Each trial is assumed to have only two outcomes, either success or failure. If the probability of a successful trial is <span class="math inline">\(p\)</span>, then the probability of having <span class="math inline">\(k\)</span> successful outcomes in an experiment of <span class="math inline">\(n\)</span> independent trials is given by the <strong>probability mass function</strong>:.</li>
</ul>
<p><span class="math display">\[
{
f(k,n,p) = \mbox{Pr}(X=k)=\binom{n}{k} p^k (1-p)^{n-k}, \quad k=0,1,2,...,n
}
\]</span></p>
<p>The <strong>cumulative distribution function</strong> can be expressed as:</p>
<p><span class="math display">\[
{
F(k;n,p) = \mbox{Pr}(X\leq k) = \sum_{i=0}^{k}\binom{n}{i} p^i (1-p)^{n-i}
}
\]</span> <img src="curso_Euskaltel_files/figure-html/unnamed-chunk-2-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>with <em>mean</em> <span class="math inline">\(np\)</span> and <em>variance</em> <span class="math inline">\(np(1-p)\)</span>.</p>
<p><strong>Question:</strong></p>
<p>Suppose there are twelve multiple choice questions in an Maths class quiz. Each question has five possible answers, and only one of them is correct. Find the probability of having four or less correct answers if a student attempts to answer every question at random.</p>
<p><em>Solution</em></p>
<p>Since only one out of five possible answers is correct, the probability of answering a question correctly by random is <span class="math inline">\(1/5=0.2\)</span>. We can find the probability of having exactly 4 correct answers by random attempts as follows.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p =<span class="st"> </span><span class="dv">1</span><span class="op">/</span><span class="dv">5</span>
n =<span class="st"> </span><span class="dv">12</span>
k =<span class="st"> </span><span class="dv">4</span>
<span class="kw">dbinom</span>(k,<span class="dt">size=</span>n,<span class="dt">prob=</span><span class="fl">0.2</span>)</code></pre></div>
<pre><code>## [1] 0.1328756</code></pre>
<p>To find the probability of having four or less correct answers by random attempts, we apply the function <code>dbinom</code> with <code>k=0,1,2,4</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prob &lt;-<span class="st"> </span><span class="ot">NULL</span>
<span class="cf">for</span>(k <span class="cf">in</span> <span class="dv">0</span><span class="op">:</span><span class="dv">4</span>){
prob &lt;-<span class="st"> </span><span class="kw">c</span>(prob,<span class="kw">dbinom</span>(k,n,p))
prob
}
prob</code></pre></div>
<pre><code>## [1] 0.06871948 0.20615843 0.28346784 0.23622320 0.13287555</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(prob)</code></pre></div>
<pre><code>## [1] 0.9274445</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># or simply</span>
<span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">4</span>,n,p))</code></pre></div>
<pre><code>## [1] 0.9274445</code></pre>
<p>Alternative, we can use the cumulative probability function for the binomial distribution <code>pbinom</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pbinom</span>(<span class="dv">4</span>,<span class="dt">size=</span>n,<span class="dt">prob=</span><span class="fl">0.2</span>)</code></pre></div>
<pre><code>## [1] 0.9274445</code></pre>
<p><strong>Solution:</strong> the probability of four or less questions answered correctly by random in a twelve question multiple choice quiz is 92.7%.</p>
<p>What is the probability of 2 or 3 questions answered correctly?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">2</span><span class="op">:</span><span class="dv">3</span>,n,p))</code></pre></div>
<pre><code>## [1] 0.519691</code></pre>
<p><strong>Question:</strong></p>
<p>Suppose company <strong>A</strong> produced a product <strong>B</strong> which have probability 0.005 of being defective. Suppose product <strong>B</strong> is shipped in boxed containing 25 <strong>B</strong> items. What is the probability that a randomly chosen box contains exactly one defective product?</p>
<p><strong>Solution:</strong> Question Rephrased: What is <span class="math inline">\(P(X = 1)\)</span> when <span class="math inline">\(X\)</span> has the <span class="math inline">\(Bin(25, 0.005)\)</span> distribution? <span class="math display">\[
  P(X=1) = \binom{25}{1} 0.005^{1} (1-0.005)^{(25-1)}
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p=<span class="fl">0.005</span>
<span class="kw">choose</span>(<span class="dv">25</span>,<span class="dv">1</span>)<span class="op">*</span>p<span class="op">^</span><span class="dv">1</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p)<span class="op">^</span>(<span class="dv">25</span><span class="op">-</span><span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] 0.1108317</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># or</span>
<span class="kw">dbinom</span>(<span class="dv">1</span>,<span class="dv">25</span>,<span class="fl">0.005</span>)</code></pre></div>
<pre><code>## [1] 0.1108317</code></pre>
<p>What is the probability that a randomly chosen box contains no more than one defective item?</p>
<p><em>Solution:</em></p>
<p><span class="math display">\[
P(X\leq 1) = P(X=0) + P(X=1)
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>,<span class="dv">25</span>,p))</code></pre></div>
<pre><code>## [1] 0.9930519</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># or</span>
<span class="kw">pbinom</span>(<span class="dv">1</span>,<span class="dv">25</span>,<span class="fl">0.005</span>)</code></pre></div>
<pre><code>## [1] 0.9930519</code></pre>
</div>
<div id="poisson-distribution-poislambda" class="section level2">
<h2><span class="header-section-number">5.2</span> Poisson distribution <span class="math inline">\(Pois(\lambda)\)</span></h2>
<p>The Poisson distribution is the probability distribution of independent event occurrences in an interval. If <span class="math inline">\(\lambda\)</span> is the mean occurrence per interval, then the probability of having <span class="math inline">\(k\)</span> occurrences within a given interval is the probability mass function given by:</p>
<p><span class="math display">\[
\mbox{Pr}(\mbox{$k$ events in interval}) = \frac{\lambda^k e^{-\lambda}}{k!}
\]</span></p>
<p>The <strong>cumulative density function</strong> for the Poisson cumulative probability function is <span class="math display">\[
P(X\leq x ~|~\lambda ) = \frac{e^{-\lambda} \lambda ^x}{x!}\quad \mbox{for $x=0,1,2,...$}
\]</span></p>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-9-1.png" width="960" style="display: block; margin: auto;" /></p>
<p><strong>Question:</strong></p>
<p>Suppose the number of individual plants of a given species we expect to find in a one meter square quadrat follows the Poisson distribution with mean <span class="math inline">\(\lambda= 10\)</span>. Find the probability of finding exactly <span class="math inline">\(12\)</span> individuals.</p>
<p><strong>Question:</strong></p>
<p>If there are twelve cars crossing a bridge per minute on average, find the probability of having seventeen or more cars crossing the bridge in a particular minute.</p>
<p><strong>Solutions <a href="soluciones.html">here</a></strong></p>
<div id="aproximation-of-binomial-as-poisson" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Aproximation of Binomial as Poisson</h3>
<p><strong>Example</strong></p>
<p>Five percent (5%) of Christmas tree light bulbs manufactured by a company are defective. The company’s Quality Control Manager is quite concerned and therefore randomly samples 100 bulbs coming off of the assembly line. Let <span class="math inline">\(X\)</span> denote the number in the sample that are defective. What is the probability that the sample contains at most three defective bulbs?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p =<span class="st"> </span><span class="fl">0.05</span>
k =<span class="st"> </span><span class="dv">3</span>
n =<span class="st"> </span><span class="dv">100</span>
<span class="kw">pbinom</span>(k,<span class="dt">size=</span>n,<span class="dt">prob=</span>p)</code></pre></div>
<pre><code>## [1] 0.2578387</code></pre>
<p>It can be demonstrated that the Binomial distribution can be approximated with the Poisson probability mass function when <span class="math inline">\(n\)</span> is large. Using the Poisson distribution, the mean <span class="math inline">\(\lambda = np\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lambda &lt;-<span class="st"> </span>n<span class="op">*</span>p
<span class="kw">sum</span>(<span class="kw">dpois</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">3</span>,lambda))</code></pre></div>
<pre><code>## [1] 0.2650259</code></pre>
<p>It is important to keep in mind that the Poisson approximation to the binomial distribution works well only when <span class="math inline">\(n\)</span> is large and <span class="math inline">\(p\)</span> is small. In general, the approximation works well if <span class="math inline">\(n \geq 20\)</span> and <span class="math inline">\(p\leq0.05\)</span>, or if <span class="math inline">\(n\geq 100\)</span> and <span class="math inline">\(p\leq 0.10\)</span>.</p>
</div>
</div>
<div id="exponential-distribution-explambda" class="section level2">
<h2><span class="header-section-number">5.3</span> Exponential distribution <span class="math inline">\(Exp(\lambda)\)</span></h2>
<ul>
<li><p>The exponential distribution is the probability distribution that describes the time between events in a Poisson process, i.e. a process in which events occur continuously and independently at a constant average rate.</p></li>
<li><p>It is a particular case of the gamma distribution. It is the continuous analogue of the geometric distribution, and it has the key property of being memoryless. In addition to being used for the analysis of Poisson processes, it is found in various other contexts.</p></li>
<li><p>The probability density function (pdf) of an exponential distribution as</p></li>
</ul>
<p><span class="math display">\[
f(x;\lambda) =  \lambda \exp(-\lambda x)
\]</span></p>
<p>where <span class="math inline">\(\lambda&gt;0\)</span> is the event rate (also known as rate parameter, arrival rate, death rate, failure rate, transition rate). The exponential variable <span class="math inline">\(x \in [0,\infty)\)</span></p>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-12-1.png" width="960" style="display: block; margin: auto;" /></p>
<ul>
<li>Cumulative distribution function of the exponential distribution is</li>
</ul>
<p><span class="math display">\[
F(x) = \mbox{Pr}(X\leq x) = 
  \left\{
    \begin{array}{lcc}
      1- e^{-\lambda x} &amp; &amp; x\geq 0 \\
      0                 &amp; &amp; x &lt; 0
    \end{array}
  \right.
\]</span></p>
<p>Mean <span class="math inline">\(\mathbb{E}(X) = 1/\lambda\)</span>, and <span class="math inline">\(\mathbb{V}ar(X) = 1/\lambda^2\)</span>.</p>
<p><strong>Question:</strong></p>
<p>Suppose that the amount of time one spends in a bank is exponentially distributed with mean 10 minutes, <span class="math inline">\(\lambda=1/10\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li>What is the probability that a customer will spend more than 15 minutes in the bank?</li>
<li>What is the probability that a customer will spend more than 15 minutes in the bank given that he is still in the bank after 10 minutes?</li>
</ol>
<p><strong>Solutions</strong></p>
<ol style="list-style-type: lower-alpha">
<li></li>
</ol>
<p><span class="math display">\[
P(X&gt;15)=e^{-15\lambda}=e^{-3/2}=0.2231
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pexp</span>(<span class="dv">15</span>,<span class="dt">rate=</span><span class="dv">1</span><span class="op">/</span><span class="dv">10</span>,<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>) <span class="co"># or 1-pexp(15,rate=1/10)</span></code></pre></div>
<pre><code>## [1] 0.2231302</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li><span class="math display">\[
P(X&gt;15 | X&gt;10)=P(X&gt;5)=e^{-1/2}=0.606
\]</span></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pexp</span>(<span class="dv">5</span>,<span class="dt">rate=</span><span class="dv">1</span><span class="op">/</span><span class="dv">10</span>,<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## [1] 0.6065307</code></pre>
</div>
<div id="the-normal-distribution-mathcalnmusigma2" class="section level2">
<h2><span class="header-section-number">5.4</span> The Normal distribution <span class="math inline">\(\mathcal{N}(\mu,\sigma^2)\)</span></h2>
<ul>
<li>The probability density function of the Normal distribution is:</li>
</ul>
<p><span class="math display">\[
f(x | \mu,\sigma^2) = \frac{1}{\sqrt{2\sigma^2\pi}} e ^{-\frac{(x-\mu)^2}{2\sigma^2}},
\]</span> where</p>
<ul>
<li><span class="math inline">\(\mu\)</span> is the mean of the distribution (also the median and the mode).</li>
<li><span class="math inline">\(\sigma\)</span> is the standard deviation (<span class="math inline">\(\sigma&gt;0\)</span>).</li>
<li><p><span class="math inline">\(\sigma^2\)</span> is the variance.</p></li>
<li><p>The process to standardized Normal distribution consists in transforming the Normal variable <span class="math inline">\(N(\mu,\sigma)\)</span> to <span class="math inline">\(N(0,1)\)</span>, i.e.</p></li>
</ul>
<p><span class="math display">\[
Z = \frac{X-\mu}{\sigma} \sim N(0,1)
\]</span></p>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-15-1.png" width="960" style="display: block; margin: auto;" /></p>
<p><strong>Question:</strong></p>
<p><span class="math inline">\(X\)</span> is a normally distributed variable with mean <span class="math inline">\(\mu = 30\)</span> and standard deviation <span class="math inline">\(\sigma = 4\)</span>. Find</p>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math inline">\(P(x&lt;40)\)</span></p></li>
<li><p><span class="math inline">\(P(x&gt;21)\)</span></p></li>
<li><p><span class="math inline">\(P(30&lt;x&lt;35)\)</span></p></li>
</ol>
<p><strong>Solution:</strong></p>
<ol style="list-style-type: lower-alpha">
<li>For <span class="math inline">\(x=40\)</span>, the standardized <span class="math inline">\(z\)</span> is <span class="math inline">\((40-30)/4=2.5\)</span> and hence</li>
</ol>
<p><span class="math display">\[
P(X&lt;40)=P(Z&lt;2.5)=0.9938
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="fl">2.5</span>) <span class="co"># or </span></code></pre></div>
<pre><code>## [1] 0.9937903</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">40</span>,<span class="dt">mean=</span><span class="dv">30</span>,<span class="dt">sd=</span><span class="dv">4</span>,<span class="dt">lower.tail=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 0.9937903</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li><span class="math inline">\(P(x&gt;21)\)</span></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">21</span>,<span class="dt">mean=</span><span class="dv">30</span>,<span class="dt">sd=</span><span class="dv">4</span>,<span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## [1] 0.9877755</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li><span class="math inline">\(P(30&lt;x&lt;35)\)</span></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">35</span>,<span class="dt">mean=</span><span class="dv">30</span>,<span class="dt">sd=</span><span class="dv">4</span>,<span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)<span class="op">-</span><span class="kw">pnorm</span>(<span class="dv">30</span>,<span class="dt">mean=</span><span class="dv">30</span>,<span class="dt">sd=</span><span class="dv">4</span>,<span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 0.3943502</code></pre>
<p><strong>Question:</strong></p>
<p>Entry to a certain University is determined by a national test. The scores on this test are normally distributed with a mean of 500 and a standard deviation of 100. Tom wants to be admitted to this university and he knows that he must score better than at least 70% of the students who took the test. Tom takes the test and scores 585. Will he be admitted to this university?</p>
<p><strong>Solution:</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">N =<span class="st"> </span><span class="dv">1000</span>
<span class="kw">hist</span>(<span class="kw">rnorm</span>(N,<span class="dv">500</span>,<span class="dv">100</span>),<span class="dv">20</span>,<span class="dt">col=</span><span class="st">&quot;grey&quot;</span>)
<span class="kw">abline</span>(<span class="dt">v=</span><span class="dv">585</span>,<span class="dt">col=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Is <span class="math inline">\(P(X&lt;585)\)</span> &gt;70%?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">585</span>,<span class="dt">mean=</span><span class="dv">500</span>,<span class="dt">sd=</span><span class="dv">100</span>)</code></pre></div>
<pre><code>## [1] 0.8023375</code></pre>
<p>Tom scored better than 80.23% of the students who took the test and he will be admitted to this University.</p>
</div>
<div id="uniform-distribution-uab" class="section level2">
<h2><span class="header-section-number">5.5</span> Uniform distribution <span class="math inline">\(U(a,b)\)</span></h2>
<ul>
<li>The continuous uniform distribution is the probability distribution of random number selection from the continuous interval between a and b. Its density function is defined by the following.</li>
</ul>
<p><span class="math display">\[
f(x) = \left\{
\begin{aligned}
\frac{1}{a-b} &amp; \quad a \leq x \leq b\\
0 ~~~~&amp;\quad  \mbox{elsewhere}
\end{aligned}\right.
\]</span></p>
<ul>
<li>The <code>runif()</code> function can be used to simulate <span class="math inline">\(n\)</span> independent uniform random variables. For example, we can generate 5 uniform random numbers on <span class="math inline">\([0,1]\)</span> as follows:</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)
<span class="kw">runif</span>(<span class="dv">5</span>)</code></pre></div>
<pre><code>## [1] 0.1137034 0.6222994 0.6092747 0.6233794 0.8609154</code></pre>
<ul>
<li>In order to generate uniform numbers on an interval of the form <span class="math inline">\([a,b]\)</span>, we use the arguments <code>min=a</code> and <code>max=b</code>. For example,</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)
<span class="kw">runif</span>(<span class="dv">3</span>, <span class="fl">1.2</span>, <span class="fl">5.8</span>)</code></pre></div>
<pre><code>## [1] 1.723036 4.062577 4.002664</code></pre>
<p>gives 3 uniform numbers on <span class="math inline">\([1.2,5.8]\)</span>.</p>
<ul>
<li>In the next example, we will assign 100 independent uniform numbers on the interval <span class="math inline">\([1,5]\)</span> to a vector object called <code>U</code>:</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)
U &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">100</span>, <span class="dv">1</span>, <span class="dv">5</span>)
<span class="kw">hist</span>(U)</code></pre></div>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<ul>
<li>The density function can be calculated using <code>dunif()</code></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">curve</span>(<span class="kw">dunif</span>(x, <span class="dv">1</span>, <span class="dv">5</span>), <span class="dt">from=</span><span class="dv">0</span>, <span class="dt">to=</span><span class="dv">6</span>)</code></pre></div>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-24-1.png" width="960" /></p>
<p>Mean of <span class="math inline">\(U\)</span> is <span class="math inline">\(\mathbb{E}[U]=\frac{1}{2}(a+b)\)</span>, median is <span class="math inline">\(\mathbb{Med}[U]=\frac{1}{2}(a+b)\)</span> and Variance is <span class="math inline">\(\mathbb{Var}[U]=\frac{1}{12}(b-a)^2\)</span>.</p>
<!-- ## Gamma distribution -->
<!-- ## Beta distribution -->
<!-- # Central Limit Theorem -->
<!-- ```{r} -->
<!-- library(TeachingDemos) -->
<!-- clt.examp(5) -->
<!-- clt.examp(50) -->
<!-- ``` -->
<!-- # Estimation -->
<div id="exercises" class="section level3">
<h3><span class="header-section-number">5.5.1</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li>A dice is thrown at random. What is the expectation of number on it? (Or) If x denotes the number of points on a dice, find the expectation and the variance of x.</li>
</ol>
<p><span class="math display">\[
E(X) = \sum_{i=1}^6 x_iP(X=x_i)
\]</span></p>
<p><span class="math display">\[
Var[X]  = E[X]^2 - E[X^2]
\]</span></p>
<p>where <span class="math inline">\(E[X^2] = \sum_{i=1}^6 x_iP(X=x_i)\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x =<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">6</span>

prob &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">/</span><span class="dv">6</span>  <span class="co"># probability to obtain any number of the dice</span>

 E  &lt;-<span class="st"> </span><span class="kw">sum</span>(x<span class="op">*</span><span class="kw">rep</span>(prob,<span class="kw">length</span>(x)))
 E</code></pre></div>
<pre><code>## [1] 3.5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> E2 &lt;-<span class="st"> </span>E<span class="op">^</span><span class="dv">2</span>
 Ex2 &lt;-<span class="st"> </span><span class="kw">sum</span>(x<span class="op">^</span><span class="dv">2</span><span class="op">*</span><span class="kw">rep</span>(prob,<span class="kw">length</span>(x)))
 
Var &lt;-<span class="st"> </span>Ex2<span class="op">-</span>E2
Var</code></pre></div>
<pre><code>## [1] 2.916667</code></pre>
</div>
<div id="qq-plot" class="section level3">
<h3><span class="header-section-number">5.5.2</span> QQ-plot</h3>
<p>A Q-Q plot is a plot of the quantiles of two distributions against each other, or a plot based on estimates of the quantiles. The pattern of points in the plot is used to compare the two distributions.</p>
<p><code>qqnorm</code> is used to determine if your data is close to being normally distributed. You cannot be sure that the data is normally distributed, but you can rule out if it is not normally distributed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)

<span class="kw">require</span>(graphics)
y &lt;-<span class="st"> </span><span class="kw">rt</span>(<span class="dv">200</span>, <span class="dt">df =</span> <span class="dv">5</span>)
<span class="kw">qqnorm</span>(y); 
<span class="kw">qqline</span>(y, <span class="dt">col =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-26-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">200</span>,<span class="dt">mean=</span><span class="dv">0</span>,<span class="dt">sd=</span><span class="dv">1</span>)
<span class="kw">qqnorm</span>(z)
<span class="kw">qqline</span>(z, <span class="dt">col =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-26-2.png" width="672" style="display: block; margin: auto;" /></p>
<p>To compare two distributions</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)
<span class="kw">qqplot</span>(<span class="kw">qchisq</span>(<span class="kw">ppoints</span>(<span class="dv">500</span>), <span class="dt">df =</span> <span class="dv">3</span>), y,
       <span class="dt">main =</span> <span class="kw">expression</span>(<span class="st">&quot;Q-Q plot for&quot;</span> <span class="op">~</span><span class="er">~</span><span class="st"> </span>{chi<span class="op">^</span><span class="dv">2</span>}[nu <span class="op">==</span><span class="st"> </span><span class="dv">3</span>]))
<span class="kw">qqline</span>(y, <span class="dt">distribution =</span> <span class="cf">function</span>(p) <span class="kw">qchisq</span>(p, <span class="dt">df =</span> <span class="dv">3</span>),
       <span class="dt">prob =</span> <span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.6</span>), <span class="dt">col =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-27-1.png" width="672" /> If the two distributions being compared are identical, the Q-Q plot follows the <span class="math inline">\(45º\)</span> line <span class="math inline">\(y = x\)</span>.</p>
<p><strong>Probability concept</strong></p>
<p>In a randomized experiment, when the number of times it is repeated increases, the relative frequency is</p>
<p><span class="math display">\[
    f_n(A) = \frac{\# \mbox{times A happens}}{n}
\]</span> converges to a quantity denoted as probability <span class="math display">\[
\mathbb{Pr}(A) = \lim_{n \rightarrow\infty} f_n(A)
\]</span> This notion of probability is not used in practice, because we would need <span class="math inline">\(n \rightarrow \infty\)</span>. But in practice we can simulate with the computer.</p>
<p><strong>Example:</strong></p>
<p>The relative frequency of the number of faces obtained in successive coin tosses</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)
prob &lt;-<span class="st"> </span><span class="ot">NULL</span>
<span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>){
prob &lt;-<span class="st"> </span><span class="kw">c</span>(prob,<span class="kw">mean</span>(<span class="kw">rbinom</span>(i,<span class="dv">1</span>,<span class="fl">0.5</span>)))
}
<span class="kw">plot</span>(prob,<span class="dt">t=</span><span class="st">&quot;l&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Tosses&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Probability of head&quot;</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))
<span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.5</span>,<span class="dv">1</span>),<span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;grey&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;grey&quot;</span>),<span class="dt">lwd=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">1</span>))</code></pre></div>
<p><img src="curso_Euskaltel_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<!-- 2. If a person gains or loses an amount equal to the number appearing when a balanced die is rolled once, according to whether the number is even or odd, how much money can be expect per game in the long run?  -->
<!-- Let $x$ indicate the amount that the person wins  -->
<!-- The amount gained by the person would be -->
<!-- -  `- Rs. 1` if the dice shows up ONE -->
<!-- -  `+ Rs. 2` if the dice shows up TWO -->
<!-- -  `- Rs. 3` if the dice shows up THREE -->
<!-- -  `+ Rs. 4` if the dice shows up FOUR -->
<!-- -  `- Rs. 5` if the dice shows up FIVE -->
<!-- -  `+ Rs. 6` if the dice shows up SIX -->
<!-- ```{r} -->
<!-- x = c(1:6)*c(-1,1,-1,1,-1,1) -->
<!-- pr <- rep(1/6,6) -->
<!--  Ex <- sum(x*pr) -->
<!-- Ex2 <- sum(x^2*pr) -->
<!-- Var <- Ex2-Ex^2 -->
<!-- Ex -->
<!-- Var -->
<!-- ``` -->

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduccion-a-la-programacion-basica-con-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="casos-de-estudio.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/idaejin/master/04-prob-distr.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["curso_Euskaltel.pdf", "curso_Euskaltel.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
