<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 7 Regresión logística | Introducción al software estadístico R</title>
  <meta name="description" content=" 7 Regresión logística | Introducción al software estadístico R" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content=" 7 Regresión logística | Introducción al software estadístico R" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="idaejin/xxx" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 7 Regresión logística | Introducción al software estadístico R" />
  
  
  

<meta name="author" content="Dae-Jin Lee &lt; dlee@bcamath.org &gt;" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modelos-lineales-y-análisis-de-la-varianza.html"/>
<link rel="next" href="modelos-aditivos-generalizados.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="http://idaejin.github.io/courses/R/2019/ehu/index.html">Curso de formación en R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Información y pre-requisitos</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introducción al software estadístico <code>R</code></a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#algunas-cuestiones-a-tener-en-cuenta-sobre-r"><i class="fa fa-check"></i><b>2.1</b> Algunas cuestiones a tener en cuenta sobre <code>R</code></a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#rstudio"><i class="fa fa-check"></i><b>2.2</b> Rstudio</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#instalar-un-paquete-de-r"><i class="fa fa-check"></i><b>2.3</b> Instalar un paquete de <code>R</code></a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#empezando-con-r"><i class="fa fa-check"></i><b>2.4</b> Empezando con <code>R</code></a></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#cargar-librerías-en-r"><i class="fa fa-check"></i><b>2.5</b> Cargar librerías en <code>R</code></a></li>
<li class="chapter" data-level="2.6" data-path="intro.html"><a href="intro.html#lectura-de-datos"><i class="fa fa-check"></i><b>2.6</b> Lectura de datos</a></li>
<li class="chapter" data-level="2.7" data-path="intro.html"><a href="intro.html#importar-datos"><i class="fa fa-check"></i><b>2.7</b> Importar datos</a></li>
<li class="chapter" data-level="2.8" data-path="intro.html"><a href="intro.html#exportar-datos"><i class="fa fa-check"></i><b>2.8</b> Exportar datos</a></li>
<li class="chapter" data-level="2.9" data-path="intro.html"><a href="intro.html#vectores"><i class="fa fa-check"></i><b>2.9</b> Vectores</a></li>
<li class="chapter" data-level="2.10" data-path="intro.html"><a href="intro.html#estadística-básica"><i class="fa fa-check"></i><b>2.10</b> Estadística básica</a></li>
<li class="chapter" data-level="2.11" data-path="intro.html"><a href="intro.html#vectores-caracteres-y-variables-factor"><i class="fa fa-check"></i><b>2.11</b> Vectores caracteres y variables factor</a></li>
<li class="chapter" data-level="2.12" data-path="intro.html"><a href="intro.html#data-frames"><i class="fa fa-check"></i><b>2.12</b> Data frames</a><ul>
<li class="chapter" data-level="2.12.1" data-path="intro.html"><a href="intro.html#trabajando-con-data-frames"><i class="fa fa-check"></i><b>2.12.1</b> Trabajando con data frames</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="intro.html"><a href="intro.html#vectores-lógicos"><i class="fa fa-check"></i><b>2.13</b> Vectores lógicos</a></li>
<li class="chapter" data-level="2.14" data-path="intro.html"><a href="intro.html#trabajando-con-vectores"><i class="fa fa-check"></i><b>2.14</b> Trabajando con vectores</a></li>
<li class="chapter" data-level="2.15" data-path="intro.html"><a href="intro.html#matrices-y-arrays"><i class="fa fa-check"></i><b>2.15</b> Matrices y arrays</a></li>
<li class="chapter" data-level="2.16" data-path="intro.html"><a href="intro.html#factores"><i class="fa fa-check"></i><b>2.16</b> Factores</a></li>
<li class="chapter" data-level="2.17" data-path="intro.html"><a href="intro.html#indexando-vectores-con-condiciones-lógicas"><i class="fa fa-check"></i><b>2.17</b> Indexando vectores con condiciones lógicas</a></li>
<li class="chapter" data-level="2.18" data-path="intro.html"><a href="intro.html#valores-faltantes"><i class="fa fa-check"></i><b>2.18</b> Valores faltantes</a></li>
<li class="chapter" data-level="2.19" data-path="intro.html"><a href="intro.html#trabajando-con-data-frames-1"><i class="fa fa-check"></i><b>2.19</b> Trabajando con data frames</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basic.html"><a href="basic.html"><i class="fa fa-check"></i><b>3</b> Análisis de datos básico en <code>R</code></a><ul>
<li class="chapter" data-level="3.1" data-path="basic.html"><a href="basic.html#gráficos-sencillos"><i class="fa fa-check"></i><b>3.1</b> Gráficos sencillos</a></li>
<li class="chapter" data-level="3.2" data-path="basic.html"><a href="basic.html#scatterplots"><i class="fa fa-check"></i><b>3.2</b> Scatterplots</a></li>
<li class="chapter" data-level="3.3" data-path="basic.html"><a href="basic.html#más-opciones-gráficas"><i class="fa fa-check"></i><b>3.3</b> Más opciones gráficas</a></li>
<li class="chapter" data-level="3.4" data-path="basic.html"><a href="basic.html#tablas-de-clasificación-cruzada-o-de-contigencia"><i class="fa fa-check"></i><b>3.4</b> Tablas de clasificación cruzada o de contigencia</a></li>
<li class="chapter" data-level="3.5" data-path="basic.html"><a href="basic.html#datos-cualitativos"><i class="fa fa-check"></i><b>3.5</b> Datos cualitativos</a></li>
<li class="chapter" data-level="3.6" data-path="basic.html"><a href="basic.html#datos-cuantitativos"><i class="fa fa-check"></i><b>3.6</b> Datos cuantitativos</a><ul>
<li class="chapter" data-level="3.6.1" data-path="basic.html"><a href="basic.html#distribuciones-de-frecuencias"><i class="fa fa-check"></i><b>3.6.1</b> Distribuciones de frecuencias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html"><i class="fa fa-check"></i><b>4</b> Introducción a la programación básica con <code>R</code></a><ul>
<li class="chapter" data-level="4.1" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#condicionales"><i class="fa fa-check"></i><b>4.1</b> Condicionales</a></li>
<li class="chapter" data-level="4.2" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#operadores-lógicos"><i class="fa fa-check"></i><b>4.2</b> Operadores Lógicos</a></li>
<li class="chapter" data-level="4.3" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#if"><i class="fa fa-check"></i><b>4.3</b> <code>if</code></a></li>
<li class="chapter" data-level="4.4" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#ifelse"><i class="fa fa-check"></i><b>4.4</b> <code>ifelse</code></a></li>
<li class="chapter" data-level="4.5" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#loops-o-bucles"><i class="fa fa-check"></i><b>4.5</b> Loops o Bucles</a><ul>
<li class="chapter" data-level="4.5.1" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#for"><i class="fa fa-check"></i><b>4.5.1</b> <code>for</code></a></li>
<li class="chapter" data-level="4.5.2" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#while"><i class="fa fa-check"></i><b>4.5.2</b> <code>while</code></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#famila-de-funciones-apply"><i class="fa fa-check"></i><b>4.6</b> Famila de funciones <code>apply</code></a></li>
<li class="chapter" data-level="4.7" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#other-loops"><i class="fa fa-check"></i><b>4.7</b> Other Loops</a></li>
<li class="chapter" data-level="4.8" data-path="introducción-a-la-programación-básica-con-r.html"><a href="introducción-a-la-programación-básica-con-r.html#improving-speed-performance-of-loops"><i class="fa fa-check"></i><b>4.8</b> Improving Speed Performance of Loops</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html"><i class="fa fa-check"></i><b>5</b> Distribuciones de probabilidad en R</a><ul>
<li class="chapter" data-level="5.1" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribución-binomial-binnp"><i class="fa fa-check"></i><b>5.1</b> Distribución binomial <span class="math inline">\(Bin(n,p)\)</span></a></li>
<li class="chapter" data-level="5.2" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribución-de-poisson-poislambda"><i class="fa fa-check"></i><b>5.2</b> Distribución de Poisson <span class="math inline">\(Pois(\lambda)\)</span></a><ul>
<li class="chapter" data-level="5.2.1" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#aproximación-de-binomial-como-poisson"><i class="fa fa-check"></i><b>5.2.1</b> Aproximación de Binomial como Poisson</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribution-exponencial-explambda"><i class="fa fa-check"></i><b>5.3</b> Distribution Exponencial <span class="math inline">\(Exp(\lambda)\)</span></a></li>
<li class="chapter" data-level="5.4" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribution-normal-mathcalnmusigma2"><i class="fa fa-check"></i><b>5.4</b> Distribution Normal <span class="math inline">\(\mathcal{N}(\mu,\sigma^2)\)</span></a></li>
<li class="chapter" data-level="5.5" data-path="distribuciones-de-probabilidad-en-r.html"><a href="distribuciones-de-probabilidad-en-r.html#distribución-uniforme-uab"><i class="fa fa-check"></i><b>5.5</b> Distribución Uniforme <span class="math inline">\(U(a,b)\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelos-lineales-y-análisis-de-la-varianza.html"><a href="modelos-lineales-y-análisis-de-la-varianza.html"><i class="fa fa-check"></i><b>6</b> Modelos lineales y análisis de la varianza</a><ul>
<li class="chapter" data-level="6.1" data-path="modelos-lineales-y-análisis-de-la-varianza.html"><a href="modelos-lineales-y-análisis-de-la-varianza.html#principios-de-la-modelización-estadística"><i class="fa fa-check"></i><b>6.1</b> Principios de la modelización estadística</a><ul>
<li class="chapter" data-level="6.1.1" data-path="modelos-lineales-y-análisis-de-la-varianza.html"><a href="modelos-lineales-y-análisis-de-la-varianza.html#identificar-y-caracterizar-variables"><i class="fa fa-check"></i><b>6.1.1</b> Identificar y Caracterizar Variables</a></li>
<li class="chapter" data-level="6.1.2" data-path="modelos-lineales-y-análisis-de-la-varianza.html"><a href="modelos-lineales-y-análisis-de-la-varianza.html#tipos-de-variables-y-tipo-de-modelo"><i class="fa fa-check"></i><b>6.1.2</b> Tipos de variables y tipo de modelo</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="modelos-lineales-y-análisis-de-la-varianza.html"><a href="modelos-lineales-y-análisis-de-la-varianza.html#el-modelo-lineal-general"><i class="fa fa-check"></i><b>6.2</b> El modelo lineal general</a></li>
<li class="chapter" data-level="6.3" data-path="modelos-lineales-y-análisis-de-la-varianza.html"><a href="modelos-lineales-y-análisis-de-la-varianza.html#definición-de-modelos-en-r"><i class="fa fa-check"></i><b>6.3</b> Definición de modelos en <code>R</code></a><ul>
<li class="chapter" data-level="6.3.1" data-path="modelos-lineales-y-análisis-de-la-varianza.html"><a href="modelos-lineales-y-análisis-de-la-varianza.html#ejemplo-datos-de-precios-de-viviendas-en-boston"><i class="fa fa-check"></i><b>6.3.1</b> Ejemplo: Datos de precios de viviendas en Boston</a></li>
<li class="chapter" data-level="6.3.2" data-path="modelos-lineales-y-análisis-de-la-varianza.html"><a href="modelos-lineales-y-análisis-de-la-varianza.html#regresión-lineal-múltiple"><i class="fa fa-check"></i><b>6.3.2</b> Regresión lineal múltiple</a></li>
<li class="chapter" data-level="6.3.3" data-path="modelos-lineales-y-análisis-de-la-varianza.html"><a href="modelos-lineales-y-análisis-de-la-varianza.html#modelos-con-interacciones"><i class="fa fa-check"></i><b>6.3.3</b> Modelos con interacciones</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regresión-logística.html"><a href="regresión-logística.html"><i class="fa fa-check"></i><b>7</b> Regresión logística</a><ul>
<li class="chapter" data-level="7.1" data-path="regresión-logística.html"><a href="regresión-logística.html#ejemplo-datos-de-crédito-en-alemania-credit-scoring"><i class="fa fa-check"></i><b>7.1</b> Ejemplo: Datos de crédito en Alemania (<em>Credit scoring</em>)</a></li>
<li class="chapter" data-level="7.2" data-path="regresión-logística.html"><a href="regresión-logística.html#ejemplo-predecir-el-salario-de-los-trabajadores"><i class="fa fa-check"></i><b>7.2</b> Ejemplo: Predecir el salario de los trabajadores</a></li>
<li class="chapter" data-level="7.3" data-path="regresión-logística.html"><a href="regresión-logística.html#ejemplo-datos-de-los-supervivientes-del-titanic"><i class="fa fa-check"></i><b>7.3</b> Ejemplo: Datos de los supervivientes del Titanic</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html"><i class="fa fa-check"></i><b>8</b> Modelos Aditivos Generalizados</a><ul>
<li class="chapter" data-level="8.1" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html#suavizado"><i class="fa fa-check"></i><b>8.1</b> Suavizado</a><ul>
<li class="chapter" data-level="8.1.1" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html#regresión-polinomial"><i class="fa fa-check"></i><b>8.1.1</b> Regresión polinomial</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html#gams"><i class="fa fa-check"></i><b>8.2</b> GAMs</a><ul>
<li class="chapter" data-level="8.2.1" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html#ejemplo-salarios"><i class="fa fa-check"></i><b>8.2.1</b> Ejemplo: Salarios</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html#modelos-semi-paramétricos"><i class="fa fa-check"></i><b>8.3</b> Modelos semi-paramétricos</a><ul>
<li class="chapter" data-level="8.3.1" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html#ejemplo"><i class="fa fa-check"></i><b>8.3.1</b> Ejemplo:</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="modelos-aditivos-generalizados.html"><a href="modelos-aditivos-generalizados.html#ejemplo-calidad-del-aire"><i class="fa fa-check"></i><b>8.4</b> Ejemplo: Calidad del Aire</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="análisis-multivariante.html"><a href="análisis-multivariante.html"><i class="fa fa-check"></i><b>9</b> Análisis multivariante</a><ul>
<li class="chapter" data-level="9.1" data-path="análisis-multivariante.html"><a href="análisis-multivariante.html#análisis-de-componentes-principales"><i class="fa fa-check"></i><b>9.1</b> Análisis de Componentes Principales</a></li>
<li class="chapter" data-level="9.2" data-path="análisis-multivariante.html"><a href="análisis-multivariante.html#k-medias"><i class="fa fa-check"></i><b>9.2</b> K-medias</a></li>
<li class="chapter" data-level="9.3" data-path="análisis-multivariante.html"><a href="análisis-multivariante.html#cluster-jerárquico"><i class="fa fa-check"></i><b>9.3</b> Cluster jerárquico</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="introduccion-a-las-redes-neuronales-artificiales.html"><a href="introduccion-a-las-redes-neuronales-artificiales.html"><i class="fa fa-check"></i><b>10</b> Introduccion a las redes neuronales artificiales</a><ul>
<li class="chapter" data-level="10.1" data-path="introduccion-a-las-redes-neuronales-artificiales.html"><a href="introduccion-a-las-redes-neuronales-artificiales.html#arquitecturas-de-las-rna"><i class="fa fa-check"></i><b>10.1</b> Arquitecturas de las RNA</a></li>
<li class="chapter" data-level="10.2" data-path="introduccion-a-las-redes-neuronales-artificiales.html"><a href="introduccion-a-las-redes-neuronales-artificiales.html#ejemplo-datos-boston-housing"><i class="fa fa-check"></i><b>10.2</b> Ejemplo: datos Boston housing</a></li>
<li class="chapter" data-level="10.3" data-path="introduccion-a-las-redes-neuronales-artificiales.html"><a href="introduccion-a-las-redes-neuronales-artificiales.html#ajuste-de-la-red-neuronal"><i class="fa fa-check"></i><b>10.3</b> Ajuste de la red neuronal</a></li>
<li class="chapter" data-level="10.4" data-path="introduccion-a-las-redes-neuronales-artificiales.html"><a href="introduccion-a-las-redes-neuronales-artificiales.html#predicción-con-una-red-neuronal"><i class="fa fa-check"></i><b>10.4</b> Predicción con una red neuronal</a></li>
<li class="chapter" data-level="10.5" data-path="introduccion-a-las-redes-neuronales-artificiales.html"><a href="introduccion-a-las-redes-neuronales-artificiales.html#evaluando-la-predicción-mediante-validación-cruzada"><i class="fa fa-check"></i><b>10.5</b> Evaluando la predicción mediante validación cruzada</a><ul>
<li class="chapter" data-level="10.5.1" data-path="introduccion-a-las-redes-neuronales-artificiales.html"><a href="introduccion-a-las-redes-neuronales-artificiales.html#comparación-de-modelos-rna"><i class="fa fa-check"></i><b>10.5.1</b> Comparación de modelos RNA</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://idaejin.github.io/" target="blank">Mi página personal</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introducción al software estadístico <code>R</code></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regresión-logística" class="section level1">
<h1><span class="header-section-number"> 7</span> Regresión logística</h1>
<p>Una regresión logística se utiliza típicamente cuando hay una variable de resultado dicotómica (como ganar o perder), y una variable predictiva continua que está relacionada con la probabilidad o “odds” de la variable de resultado. También se puede utilizar con predictores categóricos y con múltiples predictores.</p>
<p> </p>
<p>Si usamos una regresión lineal para modelar una variable dicotómica (como <span class="math inline">\(Y\)</span>), es posible que el modelo resultante no restrinja los <span class="math inline">\(Y\)</span> pronosticados dentro de <span class="math inline">\(0\)</span> y <span class="math inline">\(1\)</span>. Además, otros supuestos de regresión lineal como la normalidad del error pueden ser violados. Así que en vez de eso, modelamos las probabilidades del evento de $log (logit) o logit, donde, <span class="math inline">\(p\)</span> es la probabilidad del evento.</p>
<p><span class="math display">\[
    z_i = \ln(\frac{p_i}{1-p_i}) =   \beta_0 + \beta_1 x_1 + ... + \beta_p x_p
\]</span></p>
<p> </p>
<p>La ecuación anterior puede ser modelada usando <code>glm()</code> mediante el argumento <code>family=&quot;binomial</code>. Pero estamos más interesados en la probabilidad del evento que en las probabilidades logarítmicas del evento. Por lo tanto, los valores pronosticados del modelo anterior, es decir, las probabilidades logarítmicas del evento, pueden convertirse a probabilidad de evento de la siguiente manera:</p>
<p><span class="math display">\[
  p_i =1-\frac{1}{1 + \exp(z_i)}
\]</span></p>
<p>A esto se le llama la <em>logit-inversa</em>, <code>?plogis</code>.</p>
<p> </p>
<p>El siguiente gráfico relaciona <code>p</code> y <code>logit(p)</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dt">l=</span><span class="dv">1000</span>)
logitp &lt;-<span class="st"> </span><span class="kw">log</span>(p<span class="op">/</span>(<span class="dv">1</span><span class="op">-</span>p))
<span class="kw">plot</span>(logitp,p,<span class="dt">t=</span><span class="st">&#39;l&#39;</span>,<span class="dt">xlab=</span><span class="st">&quot;log(p/1-p)&quot;</span>)
<span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.5</span>,<span class="dv">1</span>),<span class="dt">v=</span><span class="dv">0</span>,<span class="dt">col=</span><span class="st">&quot;grey&quot;</span>)
<span class="kw">points</span>(<span class="dv">0</span>,<span class="fl">0.5</span>,<span class="dt">pch=</span><span class="dv">19</span>,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="cursoR_files/figure-html/logit-06-1.png" width="672" style="display: block; margin: auto;" /></p>
<div id="ejemplo-datos-de-crédito-en-alemania-credit-scoring" class="section level2">
<h2><span class="header-section-number">7.1</span> Ejemplo: Datos de crédito en Alemania (<em>Credit scoring</em>)</h2>
<p>Cuando un banco recibe una solicitud de préstamo, basada en el perfil del solicitante, el banco tiene que tomar una decisión sobre si procede o no con la aprobación del préstamo. Hay dos tipos de riesgos asociados a la decisión del banco:</p>
<ul>
<li><p>Si el solicitante tiene un buen riesgo de crédito, es decir, es probable que pague el préstamo, entonces no aprobar el préstamo a la persona resulta en una pérdida de negocio para el banco.</p></li>
<li><p>Si el solicitante tiene un riesgo de crédito malo, es decir, no es probable que pague el préstamo, entonces la aprobación del préstamo a la persona resulta en una pérdida financiera para el banco.</p></li>
</ul>
<p> </p>
<p>El objetivo de este tipo de análisis es <strong>minimizar el riesgo y maximizar el beneficio del banco</strong>.</p>
<p>Para minimizar las pérdidas desde la perspectiva del banco, el banco necesita una regla de decisión sobre a quién dar la aprobación del préstamo y a quién no. Los perfiles demográficos y socioeconómicos de un solicitante son considerados por los administradores de préstamos antes de que se tome una decisión sobre su solicitud de préstamo.</p>
<p> </p>
<p>Los datos <a href="https://archive.ics.uci.edu/ml/datasets/statlog+(german+credit+data)">German Credit Data</a> contiene datos sobre 20 variables y la clasificación de si un solicitante es considerado un <em>Bueno</em> o un <em>Malo</em> riesgo de crédito para 1000 solicitantes de préstamos.</p>
<p> </p>
<p>Se espera que un <em>modelo predictivo</em> elaborado a partir de estos datos sirva de guía al gerente del banco para tomar una decisión sobre la aprobación de un préstamo a un posible solicitante en función de su perfil.</p>
<p><a href="ftp.ics.uci.edu/pub/machine-learning-databases/statlog/german/german.doc">Ver descripción (en inglés)</a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># German Credit Data</span>
gcreditdata &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data&quot;</span>, <span class="dt">header =</span> <span class="ot">FALSE</span>)

<span class="kw">colnames</span>(gcreditdata)&lt;-<span class="kw">c</span>(<span class="st">&quot;account.status&quot;</span>,<span class="st">&quot;months&quot;</span>,
                <span class="st">&quot;credit.history&quot;</span>,<span class="st">&quot;purpose&quot;</span>,<span class="st">&quot;credit.amount&quot;</span>,
                <span class="st">&quot;savings&quot;</span>,<span class="st">&quot;employment&quot;</span>,<span class="st">&quot;installment.rate&quot;</span>,<span class="st">&quot;personal.status&quot;</span>,
                <span class="st">&quot;guarantors&quot;</span>,<span class="st">&quot;residence&quot;</span>,<span class="st">&quot;property&quot;</span>,<span class="st">&quot;age&quot;</span>,<span class="st">&quot;other.installments&quot;</span>,
                <span class="st">&quot;housing&quot;</span>,<span class="st">&quot;credit.cards&quot;</span>,<span class="st">&quot;job&quot;</span>,<span class="st">&quot;dependents&quot;</span>,<span class="st">&quot;phone&quot;</span>,<span class="st">&quot;foreign.worker&quot;</span>,<span class="st">&quot;credit.rating&quot;</span>)

<span class="kw">head</span>(gcreditdata)</code></pre></div>
<pre><code>##   account.status months credit.history purpose credit.amount savings
## 1            A11      6            A34     A43          1169     A65
## 2            A12     48            A32     A43          5951     A61
## 3            A14     12            A34     A46          2096     A61
## 4            A11     42            A32     A42          7882     A61
## 5            A11     24            A33     A40          4870     A61
## 6            A14     36            A32     A46          9055     A65
##   employment installment.rate personal.status guarantors residence
## 1        A75                4             A93       A101         4
## 2        A73                2             A92       A101         2
## 3        A74                2             A93       A101         3
## 4        A74                2             A93       A103         4
## 5        A73                3             A93       A101         4
## 6        A73                2             A93       A101         4
##   property age other.installments housing credit.cards  job dependents
## 1     A121  67               A143    A152            2 A173          1
## 2     A121  22               A143    A152            1 A173          1
## 3     A121  49               A143    A152            1 A172          2
## 4     A122  45               A143    A153            1 A173          2
## 5     A124  53               A143    A153            2 A173          2
## 6     A124  35               A143    A153            1 A172          2
##   phone foreign.worker credit.rating
## 1  A192           A201             1
## 2  A191           A201             2
## 3  A191           A201             1
## 4  A191           A201             1
## 5  A191           A201             2
## 6  A192           A201             1</code></pre>
<p> </p>
<p>Cambie el nombre de algunos niveles de factor:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(gcreditdata<span class="op">$</span>credit.rating) <span class="co"># Good = 1 / Bad = 2</span></code></pre></div>
<pre><code>## 
##   1   2 
## 700 300</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gcreditdata<span class="op">$</span>credit.rating &lt;-<span class="st"> </span><span class="kw">ifelse</span>(gcreditdata<span class="op">$</span>credit.rating<span class="op">==</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>)
<span class="kw">table</span>(gcreditdata<span class="op">$</span>credit.rating) <span class="co"># Good = 1 / Bad = 0</span></code></pre></div>
<pre><code>## 
##   0   1 
## 300 700</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">levels</span>(gcreditdata<span class="op">$</span>account.status) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;&lt;0DM&quot;</span>,<span class="st">&quot;&lt;200DM&quot;</span>,<span class="st">&quot;&gt;200DM&quot;</span>,<span class="st">&quot;NoStatus&quot;</span>)
<span class="kw">levels</span>(gcreditdata<span class="op">$</span>credit.history) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;No&quot;</span>,<span class="st">&quot;Allpaid&quot;</span>,<span class="st">&quot;Allpaidtillnow&quot;</span>,<span class="st">&quot;Delayinpaying&quot;</span>,<span class="st">&quot;Critical&quot;</span>)
<span class="kw">levels</span>(gcreditdata<span class="op">$</span>purpose) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;car(new)&quot;</span>,<span class="st">&quot;car(used)&quot;</span>,<span class="st">&quot;furniture/equipment&quot;</span>,<span class="st">&quot;radio/television&quot;</span>,<span class="st">&quot;domesticappliances&quot;</span>,
<span class="st">&quot;repairs&quot;</span>,<span class="st">&quot;education&quot;</span>,<span class="st">&quot;vacation-doesnotexist?&quot;</span>,<span class="st">&quot;retraining&quot;</span>,<span class="st">&quot;business&quot;</span>,<span class="st">&quot;others&quot;</span>)</code></pre></div>
<p> </p>
<p>Dividamos los datos en dos grupos (entrenamiento y prueba), 70%/30%.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n&lt;-<span class="st"> </span><span class="kw">dim</span>(gcreditdata)[<span class="dv">1</span>]

<span class="kw">set.seed</span>(<span class="dv">1234</span>) <span class="co"># select a random sample with</span>
 train &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span>n , <span class="fl">0.7</span><span class="op">*</span>n)
 
 gcreditdata.test &lt;-<span class="st"> </span>gcreditdata[<span class="op">-</span>train,]
gcreditdata.train &lt;-<span class="st"> </span>gcreditdata[train,]

ytrain &lt;-<span class="st"> </span>gcreditdata<span class="op">$</span>credit.rating[train]
 ytest &lt;-<span class="st"> </span>gcreditdata<span class="op">$</span>credit.rating[<span class="op">-</span>train]</code></pre></div>
<p> </p>
<p>Un modelo logístico puede ser ajustado con la función <code>glm</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m1 &lt;-<span class="st"> </span><span class="kw">glm</span>(credit.rating <span class="op">~</span><span class="st"> </span>. , <span class="dt">family =</span> binomial, <span class="dt">data=</span> gcreditdata.train)
<span class="kw">summary</span>(m1)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = credit.rating ~ ., family = binomial, data = gcreditdata.train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.8353  -0.6178   0.3415   0.6729   2.0514  
## 
## Coefficients:
##                                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                    5.259e-01  1.371e+00   0.384 0.701257    
## account.status&lt;200DM           3.532e-01  2.719e-01   1.299 0.193876    
## account.status&gt;200DM           8.198e-01  4.626e-01   1.772 0.076353 .  
## account.statusNoStatus         1.487e+00  2.782e-01   5.344 9.08e-08 ***
## months                        -3.687e-02  1.156e-02  -3.189 0.001428 ** 
## credit.historyAllpaid         -1.347e-01  6.539e-01  -0.206 0.836779    
## credit.historyAllpaidtillnow   5.296e-01  4.975e-01   1.065 0.287038    
## credit.historyDelayinpaying    7.156e-01  5.575e-01   1.284 0.199266    
## credit.historyCritical         1.439e+00  5.073e-01   2.837 0.004559 ** 
## purposecar(used)               1.838e+00  4.856e-01   3.786 0.000153 ***
## purposefurniture/equipment     1.095e+00  9.231e-01   1.186 0.235728    
## purposeradio/television        8.879e-01  3.289e-01   2.700 0.006944 ** 
## purposedomesticappliances      9.928e-01  3.107e-01   3.196 0.001395 ** 
## purposerepairs                 5.399e-01  9.006e-01   0.599 0.548881    
## purposeeducation              -4.889e-01  6.587e-01  -0.742 0.457933    
## purposevacation-doesnotexist? -1.800e-01  4.648e-01  -0.387 0.698616    
## purposeretraining              2.093e+00  1.266e+00   1.653 0.098417 .  
## purposebusiness                5.772e-01  3.985e-01   1.448 0.147489    
## credit.amount                 -1.107e-04  5.456e-05  -2.028 0.042526 *  
## savingsA62                     5.219e-01  3.548e-01   1.471 0.141326    
## savingsA63                     8.722e-01  5.710e-01   1.528 0.126623    
## savingsA64                     1.746e+00  6.533e-01   2.673 0.007514 ** 
## savingsA65                     1.354e+00  3.350e-01   4.042 5.30e-05 ***
## employmentA72                  1.729e-01  5.327e-01   0.324 0.745566    
## employmentA73                  2.462e-01  5.116e-01   0.481 0.630356    
## employmentA74                  1.182e+00  5.660e-01   2.089 0.036736 *  
## employmentA75                  4.924e-02  5.076e-01   0.097 0.922712    
## installment.rate              -4.157e-01  1.098e-01  -3.787 0.000152 ***
## personal.statusA92             5.279e-02  4.718e-01   0.112 0.910902    
## personal.statusA93             6.791e-01  4.577e-01   1.484 0.137906    
## personal.statusA94             2.017e-01  5.550e-01   0.363 0.716253    
## guarantorsA102                 1.880e-01  5.068e-01   0.371 0.710613    
## guarantorsA103                 1.024e+00  5.814e-01   1.761 0.078259 .  
## residence                      5.357e-02  1.047e-01   0.512 0.608926    
## propertyA122                  -4.618e-01  3.142e-01  -1.470 0.141584    
## propertyA123                  -4.679e-01  2.906e-01  -1.610 0.107366    
## propertyA124                  -7.642e-01  5.658e-01  -1.351 0.176834    
## age                            1.872e-02  1.172e-02   1.598 0.110121    
## other.installmentsA142        -1.259e-01  5.197e-01  -0.242 0.808648    
## other.installmentsA143         3.400e-01  2.892e-01   1.176 0.239669    
## housingA152                    5.768e-01  2.935e-01   1.965 0.049384 *  
## housingA153                    7.825e-01  6.261e-01   1.250 0.211387    
## credit.cards                  -3.720e-01  2.456e-01  -1.515 0.129882    
## jobA172                       -8.402e-01  8.307e-01  -1.011 0.311822    
## jobA173                       -9.497e-01  7.970e-01  -1.192 0.233388    
## jobA174                       -9.513e-01  8.262e-01  -1.152 0.249525    
## dependents                    -2.108e-01  3.080e-01  -0.685 0.493620    
## phoneA192                      4.876e-01  2.556e-01   1.908 0.056400 .  
## foreign.workerA202             9.540e-01  7.550e-01   1.264 0.206386    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 839.40  on 699  degrees of freedom
## Residual deviance: 596.11  on 651  degrees of freedom
## AIC: 694.11
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p> </p>
<p>Variables significativas:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sig.var&lt;-<span class="st"> </span><span class="kw">summary</span>(m1)<span class="op">$</span>coeff[<span class="op">-</span><span class="dv">1</span>,<span class="dv">4</span>] <span class="op">&lt;</span><span class="fl">0.01</span>
<span class="kw">names</span>(sig.var)[sig.var <span class="op">==</span><span class="st"> </span><span class="ot">TRUE</span>]</code></pre></div>
<pre><code>## [1] &quot;account.statusNoStatus&quot;    &quot;months&quot;                   
## [3] &quot;credit.historyCritical&quot;    &quot;purposecar(used)&quot;         
## [5] &quot;purposeradio/television&quot;   &quot;purposedomesticappliances&quot;
## [7] &quot;savingsA64&quot;                &quot;savingsA65&quot;               
## [9] &quot;installment.rate&quot;</code></pre>
<p> </p>
<p>Con <code>predict</code> podemos predecir con el modelo logístico el conjunto de test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pred1&lt;-<span class="st"> </span><span class="kw">predict.glm</span>(m1,<span class="dt">newdata =</span> gcreditdata.test, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
result1&lt;-<span class="st"> </span><span class="kw">table</span>(ytest, <span class="kw">floor</span>(pred1<span class="op">+</span><span class="fl">0.5</span>))
result1</code></pre></div>
<pre><code>##      
## ytest   0   1
##     0  48  51
##     1  25 176</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">error1&lt;-<span class="st"> </span><span class="kw">sum</span>(result1[<span class="dv">1</span>,<span class="dv">2</span>], result1[<span class="dv">2</span>,<span class="dv">1</span>])<span class="op">/</span><span class="kw">sum</span>(result1)
error1</code></pre></div>
<pre><code>## [1] 0.2533333</code></pre>
<p> </p>
<p>Curva ROC con la librería <code>ROCR</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ROCR)</code></pre></div>
<pre><code>## Loading required package: gplots</code></pre>
<pre><code>## 
## Attaching package: &#39;gplots&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     lowess</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pred =<span class="st"> </span>ROCR<span class="op">::</span><span class="kw">prediction</span>(pred1,ytest)
perf &lt;-<span class="st"> </span><span class="kw">performance</span>(pred, <span class="st">&quot;tpr&quot;</span>, <span class="st">&quot;fpr&quot;</span>)
<span class="kw">plot</span>(perf)</code></pre></div>
<p><img src="cursoR_files/figure-html/ROCR-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AUCLog1=<span class="kw">performance</span>(pred, <span class="dt">measure =</span> <span class="st">&quot;auc&quot;</span>)<span class="op">@</span>y.values[[<span class="dv">1</span>]]
<span class="kw">cat</span>(<span class="st">&quot;AUC: &quot;</span>,AUCLog1,<span class="st">&quot;n&quot;</span>)</code></pre></div>
<pre><code>## AUC:  0.7699382 n</code></pre>
</div>
<div id="ejemplo-predecir-el-salario-de-los-trabajadores" class="section level2">
<h2><span class="header-section-number">7.2</span> Ejemplo: Predecir el salario de los trabajadores</h2>
<p>Consideremos los datos <code>adult.csv</code>. Intentaremos predecir la variable de respuesta <code>ABOVE50k</code> (Salario &gt;50k) mediante una regresión logística basada en variables demográficas explicativas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">inputData &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://idaejin.github.io/courses/R/data/adult.csv&quot;</span>)
<span class="kw">head</span>(inputData)</code></pre></div>
<pre><code>##   AGE         WORKCLASS FNLWGT  EDUCATION EDUCATIONNUM       MARITALSTATUS
## 1  39         State-gov  77516  Bachelors           13       Never-married
## 2  50  Self-emp-not-inc  83311  Bachelors           13  Married-civ-spouse
## 3  38           Private 215646    HS-grad            9            Divorced
## 4  53           Private 234721       11th            7  Married-civ-spouse
## 5  28           Private 338409  Bachelors           13  Married-civ-spouse
## 6  37           Private 284582    Masters           14  Married-civ-spouse
##           OCCUPATION   RELATIONSHIP   RACE     SEX CAPITALGAIN CAPITALLOSS
## 1       Adm-clerical  Not-in-family  White    Male        2174           0
## 2    Exec-managerial        Husband  White    Male           0           0
## 3  Handlers-cleaners  Not-in-family  White    Male           0           0
## 4  Handlers-cleaners        Husband  Black    Male           0           0
## 5     Prof-specialty           Wife  Black  Female           0           0
## 6    Exec-managerial           Wife  White  Female           0           0
##   HOURSPERWEEK  NATIVECOUNTRY ABOVE50K
## 1           40  United-States        0
## 2           13  United-States        0
## 3           40  United-States        0
## 4           40  United-States        0
## 5           40           Cuba        0
## 6           40  United-States        0</code></pre>
<p><strong>Verificar sesgo de clase</strong></p>
<p>Idealmente, la proporción de eventos y no eventos en la variable <span class="math inline">\(Y\)</span> debería ser aproximadamente la misma. Por lo tanto, primero verifiquemos la proporción de clases en la variable dependiente <code>ABOVE50K</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(inputData<span class="op">$</span>ABOVE50K)</code></pre></div>
<pre><code>## 
##     0     1 
## 24720  7841</code></pre>
<p>Claramente, existe un sesgo de clase, una condición observada cuando la proporción de eventos es mucho menor que la proporción de no eventos. Por lo tanto, debemos muestrear las observaciones en proporciones aproximadamente iguales para obtener mejores modelos.</p>
<p><strong>Crear Muestras de Entrenamiento y Pruebas</strong></p>
<p>Una manera de abordar el problema del sesgo de clase es muestrear los 0 y 1 para los <code>trainingData</code> (muestra de entrenamiento) en proporciones iguales. Al hacerlo, pondremos el resto de los <code>inputData</code> no incluidos para la formación en <code>testData</code> (muestra de validación). Como resultado, el tamaño de la muestra de entrenamiento será menor que el de la validación, lo que está bien, porque hay un gran número de observaciones (<code>&gt;10K</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Create Training Data</span>
 input_ones &lt;-<span class="st"> </span>inputData[<span class="kw">which</span>(inputData<span class="op">$</span>ABOVE50K <span class="op">==</span><span class="st"> </span><span class="dv">1</span>), ]  <span class="co"># all 1&#39;s</span>
input_zeros &lt;-<span class="st"> </span>inputData[<span class="kw">which</span>(inputData<span class="op">$</span>ABOVE50K <span class="op">==</span><span class="st"> </span><span class="dv">0</span>), ]  <span class="co"># all 0&#39;s</span>

<span class="kw">set.seed</span>(<span class="dv">100</span>)  <span class="co"># for repeatability of samples</span>

input_ones_training_rows &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(input_ones), <span class="fl">0.7</span><span class="op">*</span><span class="kw">nrow</span>(input_ones))  <span class="co"># 1&#39;s for training</span>
input_zeros_training_rows &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(input_zeros), <span class="fl">0.7</span><span class="op">*</span><span class="kw">nrow</span>(input_ones))  <span class="co"># 0&#39;s for training. </span>

<span class="co"># Pick as many 0&#39;s as 1&#39;s</span>
training_ones &lt;-<span class="st"> </span>input_ones[input_ones_training_rows, ]  
training_zeros &lt;-<span class="st"> </span>input_zeros[input_zeros_training_rows, ]
trainingData &lt;-<span class="st"> </span><span class="kw">rbind</span>(training_ones, training_zeros)  <span class="co"># row bind the 1&#39;s and 0&#39;s </span>

<span class="co"># Create Test Data</span>
 test_ones &lt;-<span class="st"> </span>input_ones[<span class="op">-</span>input_ones_training_rows, ]
test_zeros &lt;-<span class="st"> </span>input_zeros[<span class="op">-</span>input_zeros_training_rows, ]

testData &lt;-<span class="st"> </span><span class="kw">rbind</span>(test_ones, test_zeros)  <span class="co"># row bind the 1&#39;s and 0&#39;s </span></code></pre></div>
<p><strong>Construir modelos de Logit y predecir</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">logitMod &lt;-<span class="st"> </span><span class="kw">glm</span>(ABOVE50K <span class="op">~</span><span class="st"> </span>RELATIONSHIP <span class="op">+</span><span class="st"> </span>AGE <span class="op">+</span><span class="st"> </span>CAPITALGAIN <span class="op">+</span><span class="st"> </span>OCCUPATION <span class="op">+</span><span class="st"> </span>EDUCATIONNUM, <span class="dt">data=</span>trainingData, <span class="dt">family=</span><span class="kw">binomial</span>(<span class="dt">link=</span><span class="st">&quot;logit&quot;</span>))</code></pre></div>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">predicted &lt;-<span class="st"> </span><span class="kw">plogis</span>(<span class="kw">predict</span>(logitMod, testData))  <span class="co"># predicted scores</span>
<span class="co"># or</span>
predicted &lt;-<span class="st"> </span><span class="kw">predict</span>(logitMod, testData, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)  <span class="co"># predicted scores</span></code></pre></div>
<p> </p>
<p>Cuando usamos la función de predicción en este modelo, predecirá las probabilidades de la variable <span class="math inline">\(Y\)</span>. Para convertirlo en una probabilidad de predicción que esté entre 0 y 1, usamos el <code>plogis()</code>.</p>
<p> </p>
<p><strong>Decidir la probabilidad de corte de predicción óptima para el modelo.</strong></p>
<p>El puntaje de probabilidad de la predicción de corte por defecto es de <span class="math inline">\(0.5\)</span> o la proporción de 1’s y 0’s en los datos de entrenamiento. Pero a veces, afinar el corte de probabilidad puede mejorar la precisión tanto en las muestras de desarrollo como en las de validación. La función <code>InformationValue::optimalCutoff</code> proporciona formas de encontrar el punto de corte óptimo para mejorar la predicción de 1, 0, 1 y 0 y reducir el error de clasificación. Permite calcular la puntuación óptima que minimiza el error de clasificación para el modelo anterior.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(InformationValue)
optCutOff &lt;-<span class="st"> </span><span class="kw">optimalCutoff</span>(testData<span class="op">$</span>ABOVE50K, predicted)[<span class="dv">1</span>] 
optCutOff</code></pre></div>
<pre><code>## [1] 0.89</code></pre>
<p> </p>
<p><strong>Error de clasificación</strong></p>
<p>El error de clasificación errónea es el desajuste porcentual de los valores predefinidos frente a los reales, independientemente de que sean 1 o 0. Cuanto menor sea el error de clasificación, mejor será su modelo.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">misClassError</span>(testData<span class="op">$</span>ABOVE50K, predicted, <span class="dt">threshold =</span> optCutOff)</code></pre></div>
<pre><code>## [1] 0.0892</code></pre>
<p><strong>ROC</strong></p>
<p><strong>Receiver Operating Characteristics</strong> a curva traza el porcentaje de verdaderos positivos pronosticados con precisión por un modelo logit dado a medida que la probabilidad de corte de la predicción se reduce de 1 a 0. Para un buen modelo, a medida que se reduce el corte, debería marcar más de 1 real como positivo y menos de 0 real como 1. Por lo tanto, para un buen modelo, la curva debería subir bruscamente, indicando que el TPR (eje Y) aumenta más rápido que el FPR (eje X) a medida que disminuye la puntuación de corte. Cuanto mayor sea el área bajo la curva ROC, mejor será la capacidad de predicción del modelo.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plotROC</span>(testData<span class="op">$</span>ABOVE50K, predicted)</code></pre></div>
<p><img src="cursoR_files/figure-html/plotROC-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><strong>Especificidad y sensibilidad</strong></p>
<p>La <strong>Sensibilidad</strong> (o <code>Tasa Verdaderos Positivos</code>) es el porcentaje de 1’s (reales) correctamente predichos por el modelo, mientras que, <strong>especificidad</strong> es el porcentaje de 0’s (reales) correctamente predicho. <strong>La especificidad</strong> también puede calcularse como <code>1-Tasa Falsos Positivos</code>.</p>
<p><span class="math display">\[
\text{Sensitivity}=\frac{\#\text{Actual 1&#39;s and Predicted as 1&#39;s}}{\# \text{of Actual 1&#39;s}}
\]</span> <span class="math display">\[
\text{Specificity}=\frac{\#\text{Actual 0&#39;s and Predicted as 0&#39;s}}{\# \text{of Actual 0&#39;s}}
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sensitivity</span>(testData<span class="op">$</span>ABOVE50K, predicted, <span class="dt">threshold =</span> optCutOff)</code></pre></div>
<pre><code>## [1] 0.3442414</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">specificity</span>(testData<span class="op">$</span>ABOVE50K, predicted, <span class="dt">threshold =</span> optCutOff)</code></pre></div>
<pre><code>## [1] 0.9800853</code></pre>
<p>Los números anteriores se calculan a partir de la muestra de validación que no se utilizó para la formación del modelo. Así que, una tasa de detección de la verdad de 34.42% en los datos de prueba es bueno.</p>
<p><strong>Matriz de Confusión</strong> Las columnas son reales, mientras que las filas son predicciones.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confusionMatrix</span>(testData<span class="op">$</span>ABOVE50K, predicted, <span class="dt">threshold =</span> optCutOff)</code></pre></div>
<pre><code>##       0    1
## 0 18849 1543
## 1   383  810</code></pre>
</div>
<div id="ejemplo-datos-de-los-supervivientes-del-titanic" class="section level2">
<h2><span class="header-section-number">7.3</span> Ejemplo: Datos de los supervivientes del Titanic</h2>
<p>El conjunto de datos es una colección de datos sobre algunos de los pasajeros, y el objetivo es predecir la supervivencia (1 si el pasajero sobrevivió o 0 si no lo hizo) basándose en algunas características como la clase de servicio, el sexo, la edad, etc. Como puede ver, vamos a utilizar variables categóricas y continuas.</p>
<pre><code>VARIABLE DESCRIPTIONS:
pclass          Passenger Class
                (1 = 1st; 2 = 2nd; 3 = 3rd)
survival        Survival
                (0 = No; 1 = Yes)
name            Name
sex             Sex
age             Age
sibsp           Number of Siblings/Spouses Aboard
parch           Number of Parents/Children Aboard
ticket          Ticket Number
fare            Passenger Fare
cabin           Cabin
embarked        Port of Embarkation
                (C = Cherbourg; Q = Queenstown; S = Southampton)
boat            Lifeboat
body            Body Identification Number
home_dest       Home/Destination</code></pre>
<p>Descripción completa <a href="http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3info.txt">(Aquí)</a></p>
<p>Descarga los datos <a href="http://idaejin.github.io/courses/R/data/titanic.zip">aquí</a></p>
<p>Leemos los datos de entreamiento <code>train</code> y <code>test</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">train &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;http://idaejin.github.io/courses/R/data/titanic_train.csv&#39;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">row.names=</span><span class="dv">1</span>)
 test &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;http://idaejin.github.io/courses/R/data/titanic_test.csv&#39;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">row.names=</span><span class="dv">1</span>)</code></pre></div>
<p><strong>Questions:</strong></p>
<ul>
<li><p>Ajustar un modelo logístico con <code>pclass</code> como variable explicativa. ¿Cuál es la interpretación del modelo ajustado?</p></li>
<li><p>Encontrar el mejor modelo de regresión logística posible basado en todas las variables disponibles.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">glm</span>(Survived <span class="op">~</span>.,<span class="dt">family=</span><span class="kw">binomial</span>(<span class="dt">link=</span><span class="st">&#39;logit&#39;</span>),<span class="dt">data=</span>train)
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Survived ~ ., family = binomial(link = &quot;logit&quot;), 
##     data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.6064  -0.5954  -0.4254   0.6220   2.4165  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  5.137627   0.594998   8.635  &lt; 2e-16 ***
## Pclass      -1.087156   0.151168  -7.192 6.40e-13 ***
## Sexmale     -2.756819   0.212026 -13.002  &lt; 2e-16 ***
## Age         -0.037267   0.008195  -4.547 5.43e-06 ***
## SibSp       -0.292920   0.114642  -2.555   0.0106 *  
## Parch       -0.116576   0.128127  -0.910   0.3629    
## Fare         0.001528   0.002353   0.649   0.5160    
## EmbarkedQ   -0.002656   0.400882  -0.007   0.9947    
## EmbarkedS   -0.318786   0.252960  -1.260   0.2076    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1065.39  on 799  degrees of freedom
## Residual deviance:  709.39  on 791  degrees of freedom
## AIC: 727.39
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(model, <span class="dt">test=</span><span class="st">&quot;Chisq&quot;</span>)</code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: Survived
## 
## Terms added sequentially (first to last)
## 
## 
##          Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                       799    1065.39              
## Pclass    1   83.607       798     981.79 &lt; 2.2e-16 ***
## Sex       1  240.014       797     741.77 &lt; 2.2e-16 ***
## Age       1   17.495       796     724.28 2.881e-05 ***
## SibSp     1   10.842       795     713.43  0.000992 ***
## Parch     1    0.863       794     712.57  0.352873    
## Fare      1    0.994       793     711.58  0.318717    
## Embarked  2    2.187       791     709.39  0.334990    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod1 &lt;-<span class="st"> </span><span class="kw">glm</span>(Survived <span class="op">~</span><span class="st"> </span><span class="kw">as.factor</span>(Pclass), <span class="dt">family=</span>binomial, <span class="dt">data=</span>train)
<span class="kw">summary</span>(mod1)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Survived ~ as.factor(Pclass), family = binomial, 
##     data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3787  -0.7515  -0.7515   0.9887   1.6747  
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)          0.4616     0.1474   3.131  0.00174 ** 
## as.factor(Pclass)2  -0.5455     0.2138  -2.551  0.01074 *  
## as.factor(Pclass)3  -1.5816     0.1844  -8.575  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1065.39  on 799  degrees of freedom
## Residual deviance:  979.94  on 797  degrees of freedom
## AIC: 985.94
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(mod1,<span class="dt">test=</span><span class="st">&quot;Chisq&quot;</span>)</code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: Survived
## 
## Terms added sequentially (first to last)
## 
## 
##                   Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                                799    1065.39              
## as.factor(Pclass)  2   85.452       797     979.94 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>efecto de interacción entre la clase de pasajero y el sexo, ya que la clase de pasajero mostró una diferencia mucho mayor en la tasa de supervivencia entre las mujeres en comparación con los hombres (es decir, las mujeres de clase superior tenían muchas más probabilidades de sobrevivir que las mujeres de clase inferior, mientras que los hombres de primera clase tenían más probabilidades de sobrevivir que los hombres de segunda o tercera clase, pero no por el mismo margen que las mujeres).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod2 &lt;-<span class="st"> </span><span class="kw">glm</span>(Survived <span class="op">~</span><span class="st"> </span>Pclass <span class="op">+</span><span class="st"> </span>Sex  <span class="op">+</span><span class="st"> </span>Age <span class="op">+</span><span class="st"> </span>SibSp, <span class="dt">family =</span> <span class="kw">binomial</span>(logit), <span class="dt">data =</span> train)
<span class="kw">summary</span>(mod2)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Survived ~ Pclass + Sex + Age + SibSp, family = binomial(logit), 
##     data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.6595  -0.6125  -0.4247   0.6149   2.4302  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  5.05604    0.50130  10.086  &lt; 2e-16 ***
## Pclass      -1.14391    0.12585  -9.089  &lt; 2e-16 ***
## Sexmale     -2.75564    0.20471 -13.461  &lt; 2e-16 ***
## Age         -0.03725    0.00812  -4.588 4.48e-06 ***
## SibSp       -0.33075    0.10892  -3.037  0.00239 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1065.39  on 799  degrees of freedom
## Residual deviance:  713.43  on 795  degrees of freedom
## AIC: 723.43
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(mod2,<span class="dt">test=</span><span class="st">&quot;Chisq&quot;</span>)</code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: Survived
## 
## Terms added sequentially (first to last)
## 
## 
##        Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                     799    1065.39              
## Pclass  1   83.607       798     981.79 &lt; 2.2e-16 ***
## Sex     1  240.014       797     741.77 &lt; 2.2e-16 ***
## Age     1   17.495       796     724.28 2.881e-05 ***
## SibSp   1   10.842       795     713.43  0.000992 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod3 &lt;-<span class="st">  </span><span class="kw">glm</span>(Survived <span class="op">~</span><span class="st"> </span>Pclass <span class="op">+</span><span class="st"> </span>Sex <span class="op">+</span><span class="st"> </span>Pclass<span class="op">:</span>Sex <span class="op">+</span><span class="st"> </span>Age <span class="op">+</span><span class="st"> </span>SibSp, <span class="dt">family =</span> <span class="kw">binomial</span>(logit), <span class="dt">data =</span> train)
<span class="kw">summary</span>(mod3)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Survived ~ Pclass + Sex + Pclass:Sex + Age + SibSp, 
##     family = binomial(logit), data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.1993  -0.6265  -0.4770   0.4485   2.3093  
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     7.606411   0.960804   7.917 2.44e-15 ***
## Pclass         -2.108360   0.316024  -6.672 2.53e-11 ***
## Sexmale        -5.887480   0.920417  -6.397 1.59e-10 ***
## Age            -0.038063   0.008498  -4.479 7.50e-06 ***
## SibSp          -0.310269   0.109370  -2.837 0.004556 ** 
## Pclass:Sexmale  1.254202   0.338241   3.708 0.000209 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1065.39  on 799  degrees of freedom
## Residual deviance:  695.66  on 794  degrees of freedom
## AIC: 707.66
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(mod3,<span class="dt">test=</span><span class="st">&quot;Chisq&quot;</span>)</code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: Survived
## 
## Terms added sequentially (first to last)
## 
## 
##            Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                         799    1065.39              
## Pclass      1   83.607       798     981.79 &lt; 2.2e-16 ***
## Sex         1  240.014       797     741.77 &lt; 2.2e-16 ***
## Age         1   17.495       796     724.28 2.881e-05 ***
## SibSp       1   10.842       795     713.43  0.000992 ***
## Pclass:Sex  1   17.779       794     695.66 2.481e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>En los pasos anteriores, evaluamos brevemente el ajuste del modelo, ahora nos gustaría ver cómo lo está haciendo el modelo al predecir <span class="math inline">\(y\)</span> en un nuevo conjunto de datos. Estableciendo el parámetro <code>type='response'</code>, <code>R</code> producirá probabilidades en la forma de <span class="math inline">\(P(y=1|X)\)</span>. Nuestro límite de decisión será de <span class="math inline">\(0.5\)</span>.</p>
<p>Si <span class="math inline">\(P(y=1|X) &gt; 0.5\)</span> entonces <span class="math inline">\(y = 1\)</span> en caso contrario <span class="math inline">\(y=0\)</span>. Tener en cuenta que para algunas aplicaciones diferentes límites de decisión podría ser una mejor opción.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fitted.results &lt;-<span class="st"> </span><span class="kw">predict</span>(mod3,<span class="dt">newdata=</span>test,<span class="dt">type=</span><span class="st">&#39;response&#39;</span>)
fitted.results &lt;-<span class="st"> </span><span class="kw">ifelse</span>(fitted.results <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>,<span class="dv">1</span>,<span class="dv">0</span>)

misClasificError &lt;-<span class="st"> </span><span class="kw">mean</span>(fitted.results <span class="op">!=</span><span class="st"> </span>test<span class="op">$</span>Survived)
<span class="kw">print</span>(<span class="kw">paste</span>(<span class="st">&#39;Accuracy&#39;</span>,<span class="dv">1</span><span class="op">-</span>misClasificError))</code></pre></div>
<pre><code>## [1] &quot;Accuracy 0.8075&quot;</code></pre>
<p>La precisión de 0.8075 en el conjunto de test es un buen resultado. Sin embargo, hay que tener en cuenta que este resultado depende en cierta medida de la división manual de los datos que hice anteriormente, por lo tanto, si deseamos una puntuación más precisa, sería mejor realizar algún tipo de validación cruzada, como la validación cruzada k-fold.</p>
<p><strong>Evaluar la capacidad predictiva</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ROCR)
p &lt;-<span class="st"> </span><span class="kw">predict</span>(mod3, <span class="dt">newdata=</span><span class="kw">subset</span>(test,<span class="dt">select=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>)), <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
pr &lt;-<span class="st"> </span>ROCR<span class="op">::</span><span class="kw">prediction</span>(p, test<span class="op">$</span>Survived)
prf &lt;-<span class="st"> </span><span class="kw">performance</span>(pr, <span class="dt">measure =</span> <span class="st">&quot;tpr&quot;</span>, <span class="dt">x.measure =</span> <span class="st">&quot;fpr&quot;</span>)
<span class="kw">plot</span>(prf)</code></pre></div>
<p><img src="cursoR_files/figure-html/ROCR2-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auc &lt;-<span class="st"> </span><span class="kw">performance</span>(pr, <span class="dt">measure =</span> <span class="st">&quot;auc&quot;</span>)
auc &lt;-<span class="st"> </span>auc<span class="op">@</span>y.values[[<span class="dv">1</span>]]
auc</code></pre></div>
<pre><code>## [1] 0.8543155</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modelos-lineales-y-análisis-de-la-varianza.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelos-aditivos-generalizados.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"download": ["cursoR.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
